COMP_hack: libcomp::ScriptEngine Class Reference
libcomp::ScriptEngine Class Reference
Represents a Sqrat based Squirrel virtual machine handler to facilitate script execution and bind Object instances to the VM.
#include <ScriptEngine.h>
Public Member Functions
ScriptEngine (bool useRawPrint=false)
Create the VM.
~ScriptEngine ()
Clean up the VM.
bool Eval (const String &source, const String &sourceName=String())
Evaluate a Squirrel script block as a string.
HSQUIRRELVM GetVM ()
Get the Sqrat VM.
template<>
ScriptEngine & Using ()
template<class T >
ScriptEngine & Using ()
Signifies that the templated type will be used in the VM instance.
template<>
ScriptEngine & Using ()
template<>
ScriptEngine & Using ()
template<>
ScriptEngine & Using ()
Private Member Functions
template<class T >
void Bind (const std::string &name, Sqrat::Class< T > &binding)
Utility function to complete the binding of an object via ScriptEngine::Using.
bool BindingExists (const std::string &name, bool lockBinding=false)
Check if an object has already been bound.
Private Attributes
std::set< std::string > mBindings
Bindings that have already been made to objects via ScriptEngine::Using.
HSQUIRRELVM mVM
The Sqrat VM.
Detailed Description
Represents a Sqrat based Squirrel virtual machine handler to facilitate script execution and bind Object instances to the VM.
Definition at line 52 of file ScriptEngine.h.
Constructor & Destructor Documentation
ScriptEngine::ScriptEngine (bool useRawPrint = false)
Create the VM.
Parameters
useRawPrint Set this to not prefix messages with "SQUIRREL: ".
Definition at line 151 of file src/ScriptEngine.cpp.
References LOG_ERROR, SQUIRREL_STACK_SIZE, SquirrelErrorFunction(), SquirrelErrorFunctionRaw(), SquirrelPrintFunction(), and SquirrelPrintFunctionRaw().
ScriptEngine::~ScriptEngine ()
Clean up the VM.
Definition at line 181 of file src/ScriptEngine.cpp.
Member Function Documentation
template<class T > void libcomp::ScriptEngine::Bind (const std::string & name, Sqrat::Class< T > & binding) inline private
Utility function to complete the binding of an object via ScriptEngine::Using.
Parameters
name The name of the binding which should match a class name
binding The object binding
Definition at line 94 of file ScriptEngine.h.
References BindingExists(), mBindings, and mVM.
bool ScriptEngine::BindingExists (const std::string & name, bool lockBinding = false) private
Check if an object has already been bound.
Parameters
name The name of the binding to check
lockBinding Optional parameter to mark the binding as known now instead of waiting until calling ScriptEngine::Bind. Useful for static functions or when circular references can occur.
Returns
true if it was bound already, false if it was not
Definition at line 214 of file src/ScriptEngine.cpp.
Referenced by Bind().
bool ScriptEngine::Eval (const String & source, const String & sourceName = String())
Evaluate a Squirrel script block as a string.
Parameters
source Squirrel script block as a string
Returns
true on success, false on failure
Definition at line 186 of file src/ScriptEngine.cpp.
References libcomp::String::C(), NO_RETURN_VALUE, ONE_PARAM, RAISE_ERROR, and libcomp::String::Size().
Referenced by libcomp::ServerDataManager::LoadScript(), and TEST().
HSQUIRRELVM ScriptEngine::GetVM ()
Get the Sqrat VM.
Returns
The Sqrat VM
Definition at line 209 of file src/ScriptEngine.cpp.
Referenced by libcomp::ServerDataManager::LoadScript(), and TEST().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 41 of file Randomizer.cpp.
template<class T > ScriptEngine& libcomp::ScriptEngine::Using ()
Signifies that the templated type will be used in the VM instance.
Implementations of this function are generated by objgen when the object is flagged as "scriptEnabled". Multiple calls to this function will not bind the object multiple times.
Returns
Reference back to the engine so they can be chained
Referenced by libcomp::ServerDataManager::LoadScript(), and TEST().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 264 of file ServerDataManager.cpp.
References libcomp::ServerScript::Name, and libcomp::ServerScript::Type.
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 622 of file src/Packet.cpp.
References libcomp::Packet::WriteArray(), libcomp::Packet::WriteBlank(), and libcomp::Packet::WriteU16Little().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 917 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::HexDump(), libcomp::ReadOnlyPacket::ReadArray(), libcomp::ReadOnlyPacket::Rewind(), and libcomp::ReadOnlyPacket::Size().
Member Data Documentation
std::set<std::string> libcomp::ScriptEngine::mBindings private
Bindings that have already been made to objects via ScriptEngine::Using.
Definition at line 114 of file ScriptEngine.h.
Referenced by Bind().
HSQUIRRELVM libcomp::ScriptEngine::mVM private
The Sqrat VM.
Definition at line 111 of file ScriptEngine.h.
Referenced by Bind().
The documentation for this class was generated from the following files:
ScriptEngine.h
src/Packet.cpp
Randomizer.cpp
ReadOnlyPacket.cpp
src/ScriptEngine.cpp
ServerDataManager.cpp