COMP_hack: libcomp::Worker Class Reference
libcomp::Worker Class Reference
Generic worker assigned to a message queue used to handle messages as they are received.
#include <Worker.h>
Public Member Functions
Worker ()
Create a new worker.
virtual ~Worker ()
Cleanup the worker.
void AddManager (const std::shared_ptr< Manager > &manager)
Add a manager to process messages.
long AssignmentCount () const
Get the number of active references to the message queue assigned to the worker.
template<typename Function , typename... Args>
bool ExecuteInWorker (Function &&f, Args &&...args) const
Executes code in the worker thread.
std::shared_ptr< libcomp::MessageQueue< libcomp::Message::Message * > > GetMessageQueue () const
Get the message queue assinged to the worker.
bool IsRunning () const
Check if the worker is currently running.
virtual void Join ()
Join the thread used for asynchronous execution.
virtual void Run (libcomp::MessageQueue< libcomp::Message::Message * > *pMessageQueue)
Wait for a message to enter the queue then handle it with the appropriate Manager configured for the worker.
virtual void Shutdown ()
Signal that the worker should shutdown by sending a Message::Shutdown.
void Start (const libcomp::String &name, bool blocking=false)
Loop until stopped, making a call to Worker::Run.
Protected Member Functions
virtual void Cleanup ()
Clean up the worker, deleting the thread if it exists and resetting the message queue.
Private Attributes
EnumMap< Message::MessageType, std::shared_ptr< Manager > > mManagers
Map of pointers to message handlers mapped by message type.
std::shared_ptr< libcomp::MessageQueue< libcomp::Message::Message * > > mMessageQueue
Message queue to retrieve messages from.
bool mRunning
Signifier that the worker should continue running.
std::thread * mThread
Thread used to handle asynchronous execution.
Detailed Description
Generic worker assigned to a message queue used to handle messages as they are received.
Workers can run syncronously or in their own thread and should be shutdown at the same time the executing server does.
See also
BaseServer
Definition at line 52 of file Worker.h.
Constructor & Destructor Documentation
Worker::Worker ()
Create a new worker.
Definition at line 39 of file Worker.cpp.
Worker::~Worker () virtual
Cleanup the worker.
Definition at line 44 of file Worker.cpp.
References Cleanup().
Member Function Documentation
void Worker::AddManager (const std::shared_ptr< Manager > & manager)
Add a manager to process messages.
Parameters
manager A message manager
Definition at line 49 of file Worker.cpp.
References mManagers.
Referenced by libcomp::BaseServer::Initialize().
long Worker::AssignmentCount () const
Get the number of active references to the message queue assigned to the worker.
See also
BaseServer::GetNextConnectionWorker
Returns
The number of active references to the message queue
Definition at line 198 of file Worker.cpp.
References mMessageQueue.
void Worker::Cleanup () protected virtual
Clean up the worker, deleting the thread if it exists and resetting the message queue.
This is called by the destructor.
Definition at line 164 of file Worker.cpp.
References mMessageQueue, and mThread.
Referenced by ExecuteInWorker(), and ~Worker().
template<typename Function , typename... Args> bool libcomp::Worker::ExecuteInWorker (Function && f, Args &&... args) const inline
Executes code in the worker thread.
Parameters
f Function (lambda) to execute in the worker thread.
args Arguments to pass to the function when it is executed.
Returns
true on success, false on failure
Definition at line 126 of file Worker.h.
References Cleanup(), and GetMessageQueue().
Referenced by libcomp::BaseServer::QueueWork().
std::shared_ptr< MessageQueue< Message::Message * > > Worker::GetMessageQueue () const
Get the message queue assinged to the worker.
Returns
Assigned message queue
Definition at line 193 of file Worker.cpp.
References mMessageQueue.
Referenced by ExecuteInWorker(), and libcomp::BaseServer::Initialize().
bool Worker::IsRunning () const
Check if the worker is currently running.
Returns
true if it is running, false if it is not
Definition at line 188 of file Worker.cpp.
References mRunning.
void Worker::Join () virtual
Join the thread used for asynchronous execution.
Definition at line 156 of file Worker.cpp.
References mThread.
void Worker::Run (libcomp::MessageQueue< libcomp::Message::Message * > * pMessageQueue) virtual
Wait for a message to enter the queue then handle it with the appropriate Manager configured for the worker.
Parameters
pMessageQueue Queue to check for messages
Definition at line 95 of file Worker.cpp.
References libcomp::MessageQueue< T >::DequeueAll(), LOG_ERROR, mManagers, mRunning, and libcomp::Message::Execute::Run().
Referenced by Start().
void Worker::Shutdown () virtual
Signal that the worker should shutdown by sending a Message::Shutdown.
Definition at line 151 of file Worker.cpp.
References mMessageQueue.
Referenced by libcomp::BaseServer::Shutdown().
void Worker::Start (const libcomp::String & name, bool blocking = false)
Loop until stopped, making a call to Worker::Run.
Parameters
blocking If false a new thread will be started to run this function asynchronously
Definition at line 57 of file Worker.cpp.
References libcomp::String::C(), mMessageQueue, mRunning, mThread, libcomp::Exception::RegisterSignalHandler(), and Run().
Referenced by libcomp::BaseServer::Run().
Member Data Documentation
EnumMap<Message::MessageType, std::shared_ptr<Manager> > libcomp::Worker::mManagers private
Map of pointers to message handlers mapped by message type.
Definition at line 159 of file Worker.h.
Referenced by AddManager(), and Run().
std::shared_ptr<libcomp::MessageQueue< libcomp::Message::Message*> > libcomp::Worker::mMessageQueue private
Message queue to retrieve messages from.
Definition at line 155 of file Worker.h.
Referenced by AssignmentCount(), Cleanup(), GetMessageQueue(), Shutdown(), and Start().
bool libcomp::Worker::mRunning private
Signifier that the worker should continue running.
Definition at line 151 of file Worker.h.
Referenced by IsRunning(), Run(), and Start().
std::thread* libcomp::Worker::mThread private
Thread used to handle asynchronous execution.
Definition at line 162 of file Worker.h.
Referenced by Cleanup(), Join(), and Start().
The documentation for this class was generated from the following files:
Worker.h
Worker.cpp