COMP_hack: libcomp::BaseServer Class Reference
libcomp::BaseServer Class Reference
Base class for all servers that run workers to handle incoming messages in the message queue.
#include <BaseServer.h>
Public Types
typedef std::unordered_map< std::string, std::list< std::shared_ptr< libcomp::PersistentObject > > > PersistentObjectMap
Map of PersistentObject pointers by object type name.
Public Member Functions
BaseServer (const char *szProgram, std::shared_ptr< objects::ServerConfig > config, std::shared_ptr< ServerCommandLineParser > commandLine)
Create a new base server.
virtual ~BaseServer ()
Clean up the server workers and send out the the server shutdown message.
virtual void Cleanup ()
This is called before Run() ends giving a derived class the chance to do additional cleanup.
virtual void FinishInitialize ()
Do any initialize that should happen after the server is listening and fully started.
std::shared_ptr< objects::ServerConfig > GetConfig () const
Get the server config file read during the constructor steps.
std::shared_ptr< Database > GetDatabase (const EnumMap< objects::ServerConfig::DatabaseType_t, std::shared_ptr< objects::DatabaseConfig >> &configMap, bool performSetup)
Get an open database connection of the database type associated to the server.
gsl::not_null< DataStore * > GetDataStore ()
Get the data store for the server.
virtual std::list< libcomp::Message::MessageType > GetSupportedTypes () const
Get the different types of messages handled by this manager.
gsl::not_null< TimerManager * > GetTimerManager ()
Get the timer manager for the server.
virtual bool Initialize ()
Initialize the database connection and do anything else that can fail to execute that needs to be handled outside of a constructor.
virtual bool ProcessMessage (const libcomp::Message::Message *pMessage)
Process a message from the queue.
template<typename Function , typename... Args>
bool QueueWork (Function &&f, Args &&...args) const
Queue up code to be executed in the main worker thread.
void RemoveConnection (std::shared_ptr< TcpConnection > &connection)
Remove a connection from the list of client connections.
virtual void Shutdown ()
Call the Shutdown function on each worker.
virtual int Start ()
Start a thread that listens for incoming network connections.
Static Public Member Functions
static DH * CopyDiffieHellman (const DH *pDiffieHellman)
Copy a Diffie-Hellman key pair.
static DH * GenerateDiffieHellman ()
Generate a Diffie-Hellman key pair.
static std::string GetConfigPath ()
Get the current config directory path to use.
static std::shared_ptr< Database > GetDatabase (objects::ServerConfig::DatabaseType_t dbType, const EnumMap< objects::ServerConfig::DatabaseType_t, std::shared_ptr< objects::DatabaseConfig >> &configMap)
Get an open database connection of the database type associated to the server.
static std::string GetDefaultConfigPath ()
Get the OS specific default path to look for config files.
static DH * LoadDiffieHellman (const String &prime)
Create a Diffie-Helman key pair given the hex encoded prime.
static DH * LoadDiffieHellman (const std::vector< char > &data)
Create a Diffie-Helman key pair given the binary encoded prime.
static DH * LoadDiffieHellman (const void *pData, size_t dataSize)
Create a Diffie-Helman key pair given the binary encoded prime.
static bool ReadConfig (std::shared_ptr< objects::ServerConfig > config, libcomp::String filePath)
Read the config file from the path and parse into an XML document to be read in the virtual ReadConfig function.
static bool ReadConfig (std::shared_ptr< objects::ServerConfig > config, tinyxml2::XMLDocument &doc)
Read the config file values from an XML document and populates the config passed in.
static std::vector< char > SaveDiffieHellman (const DH *pDiffieHellman)
Save a Diffie-Hellman key pair (the prime) to a binary buffer.
static void SetConfigPath (const std::string &path)
Set a custom config directory path.
Protected Member Functions
void AcceptHandler (asio::error_code errorCode, asio::ip::tcp::socket &socket)
Called to handle a new connection to the server.
bool AssignMessageQueue (const std::shared_ptr< libcomp::EncryptedConnection > &connection)
Retrieve and assign a message queue to use for a new connection.
virtual std::shared_ptr< TcpConnection > CreateConnection (asio::ip::tcp::socket &socket)
Create a connection to a newly active socket.
void CreateWorkers ()
Create one or many workers to handle connection requests based upon the server config allowing mutliple workers as well as how many cores are available on the executing machine's CPU.
const DH * GetDiffieHellman () const
Get the Diffie-Hellman key pair used by this server.
virtual std::shared_ptr< libcomp::Worker > GetNextConnectionWorker ()
Get the next worker to use for new connections.
bool InsertDataFromFile (const libcomp::String &filePath, const std::shared_ptr< Database > &db, const std::set< std::string > &specificTypes={})
Dynamicaly instantiate and insert data from an XML config file.
bool LoadDataFromFile (const libcomp::String &filePath, PersistentObjectMap &records, bool registerRecords, const std::set< std::string > &specificTypes={})
Dynamicaly instantiate data from an XML config file.
virtual int Run ()
Runs the server until a shutdown message is received or the program is forcefully closed.
virtual void ServerReady ()
Called when the server has started.
void SetDiffieHellman (DH *pDiffieHellman)
Set the Diffie-Hellman key pair used by this server.
Protected Attributes
std::shared_ptr< ServerCommandLineParser > mCommandLine
Command line options for the server.
std::shared_ptr< objects::ServerConfig > mConfig
A shared pointer to the config used to set up the server.
std::list< std::shared_ptr< TcpConnection > > mConnections
List of connections managed by this server.
std::mutex mConnectionsLock
Lock for the connection list.
libcomp::DataStore mDataStore
Data store for the server.
libcomp::Worker mMainWorker
Worker that blocks and runs in the main thread.
libcomp::Worker mQueueWorker
Worker used for async processing.
asio::io_service mService
ASIO service used to handle network operations.
libcomp::TimerManager mTimerManager
Manager for timer events.
std::list< std::shared_ptr< libcomp::Worker > > mWorkers
List of workers to handle incoming connection packet based work.
Static Protected Attributes
static std::string sConfigPath
Custom config path to use during execution.
Detailed Description
Base class for all servers that run workers to handle incoming messages in the message queue.
Each of these servers is instantiated via a dedicated config file and are responsible for choosing which of the workers it manages will be assigned to each incoming connection.
Definition at line 56 of file BaseServer.h.
Member Typedef Documentation
typedef std::unordered_map<std::string, std::list< std::shared_ptr<libcomp::PersistentObject> > > libcomp::BaseServer::PersistentObjectMap
Map of PersistentObject pointers by object type name.
Definition at line 62 of file BaseServer.h.
Constructor & Destructor Documentation
BaseServer::BaseServer (const char * szProgram, std::shared_ptr< objects::ServerConfig > config, std::shared_ptr< ServerCommandLineParser > commandLine)
Create a new base server.
Parameters
szProgram First command line argument for the application.
config Pointer to a config container that will hold properties every server has in common.
Definition at line 53 of file BaseServer.cpp.
BaseServer::~BaseServer () virtual
Clean up the server workers and send out the the server shutdown message.
Definition at line 262 of file BaseServer.cpp.
References mWorkers.
Member Function Documentation
void TcpServer::AcceptHandler (asio::error_code errorCode, asio::ip::tcp::socket & socket) protected inherited
Called to handle a new connection to the server.
This will call CreateConnection and then add the connection to the list.
Parameters
errorCode Error code of the last accept operation.
socket Socket that was bound to the new connection.
Definition at line 164 of file TcpServer.cpp.
References libcomp::TcpServer::CreateConnection(), LOG_CRITICAL, LOG_DEBUG, LOG_ERROR, libcomp::TcpServer::mAcceptor, libcomp::TcpServer::mConnections, libcomp::TcpServer::mConnectionsLock, and libcomp::TcpServer::mDiffieHellman.
Referenced by libcomp::TcpServer::Start().
bool BaseServer::AssignMessageQueue (const std::shared_ptr< libcomp::EncryptedConnection > & connection) protected
Retrieve and assign a message queue to use for a new connection.
The method of deciding which worker to use is not contained in this function but the actual assignment and starting of workers not yet running is handled.
Returns
true on success, false on failure
Definition at line 446 of file BaseServer.cpp.
References GetNextConnectionWorker(), LOG_CRITICAL, and mWorkers.
Referenced by QueueWork().
void BaseServer::Cleanup () virtual
This is called before Run() ends giving a derived class the chance to do additional cleanup.
Definition at line 635 of file BaseServer.cpp.
Referenced by Run().
DH * TcpServer::CopyDiffieHellman (const DH * pDiffieHellman) static inherited
Copy a Diffie-Hellman key pair.
Note
This will not copy the private key (just the base and prime).
Parameters
pDiffieHellman Diffie-Hellman key pair to copy.
Returns
Copied key pair or nullptr on failure.
Definition at line 334 of file TcpServer.cpp.
Referenced by libcomp::TcpServer::CreateConnection(), and TEST().
std::shared_ptr< TcpConnection > TcpServer::CreateConnection (asio::ip::tcp::socket & socket) protected virtual inherited
Create a connection to a newly active socket.
Parameters
socket A new socket connection.
Returns
Pointer to the newly created connection
Definition at line 157 of file TcpServer.cpp.
References libcomp::TcpServer::CopyDiffieHellman(), and libcomp::TcpServer::mDiffieHellman.
Referenced by libcomp::TcpServer::AcceptHandler().
void BaseServer::CreateWorkers () protected
Create one or many workers to handle connection requests based upon the server config allowing mutliple workers as well as how many cores are available on the executing machine's CPU.
Definition at line 415 of file BaseServer.cpp.
References LOG_WARNING, mConfig, and mWorkers.
Referenced by Initialize(), and QueueWork().
void BaseServer::FinishInitialize () virtual
Do any initialize that should happen after the server is listening and fully started.
Definition at line 146 of file BaseServer.cpp.
Referenced by ProcessMessage().
DH * TcpServer::GenerateDiffieHellman () static inherited
Generate a Diffie-Hellman key pair.
Returns
Generated key pair or nullptr on failure.
Definition at line 225 of file TcpServer.cpp.
References DH_BASE_INT, DH_KEY_BIT_SIZE, and DH_SHARED_DATA_SIZE.
Referenced by libcomp::TcpServer::Start(), and TEST().
std::shared_ptr< objects::ServerConfig > BaseServer::GetConfig () const
Get the server config file read during the constructor steps.
Returns
Pointer to the server config
Definition at line 486 of file BaseServer.cpp.
References mConfig.
std::string BaseServer::GetConfigPath () static
Get the current config directory path to use.
If a value is passed to SetConfigPath, that will be used, if not GetDefaultConfigPath will be used instead.
Returns
Current config directory path to use
Definition at line 327 of file BaseServer.cpp.
References GetDefaultConfigPath(), and sConfigPath.
Referenced by GetDatabase(), and Initialize().
std::shared_ptr< Database > BaseServer::GetDatabase (objects::ServerConfig::DatabaseType_t dbType, const EnumMap< objects::ServerConfig::DatabaseType_t, std::shared_ptr< objects::DatabaseConfig >> & configMap) static
Get an open database connection of the database type associated to the server.
Parameters
dbType Database type to use.
configMap Map of the available database configs by type
Returns
Pointer to the new database connection or nullptr on failure
Definition at line 150 of file BaseServer.cpp.
References LOG_CRITICAL.
Referenced by GetDatabase().
std::shared_ptr< Database > BaseServer::GetDatabase (const EnumMap< objects::ServerConfig::DatabaseType_t, std::shared_ptr< objects::DatabaseConfig >> & configMap, bool performSetup)
Get an open database connection of the database type associated to the server.
Parameters
configMap Map of the available database configs by type
performSetup If true, Database::Setup will be executed
Returns
Pointer to the new database connection or nullptr on failure
Definition at line 208 of file BaseServer.cpp.
References GetConfigPath(), GetDatabase(), InsertDataFromFile(), LOG_CRITICAL, and mConfig.
gsl::not_null< DataStore * > BaseServer::GetDataStore ()
Get the data store for the server.
Returns
Pointer to the data store. This shold never be deleted.
Definition at line 272 of file BaseServer.cpp.
References mDataStore.
std::string BaseServer::GetDefaultConfigPath () static
Get the OS specific default path to look for config files.
Returns
The default path to a config folder
Definition at line 344 of file BaseServer.cpp.
Referenced by GetConfigPath().
const DH * TcpServer::GetDiffieHellman () const protected inherited
Get the Diffie-Hellman key pair used by this server.
Returns
Key pair or nullptr if one is not set.
Definition at line 210 of file TcpServer.cpp.
References libcomp::TcpServer::mDiffieHellman.
Referenced by Initialize().
std::shared_ptr< libcomp::Worker > BaseServer::GetNextConnectionWorker () protected virtual
Get the next worker to use for new connections.
This implementation uses a "least busy" method to decide which worker to assign but it is meant to be overridden by anything with a different method of assignment.
Returns
Pointer to the worker whose message queue should be assigned to a new connection
Definition at line 462 of file BaseServer.cpp.
References mWorkers.
Referenced by AssignMessageQueue(), and QueueWork().
std::list< libcomp::Message::MessageType > BaseServer::GetSupportedTypes () const virtual
Get the different types of messages handled by this manager.
Returns
List of supported message types
Implements libcomp::Manager.
Definition at line 491 of file BaseServer.cpp.
References libcomp::Message::MESSAGE_TYPE_SYSTEM.
gsl::not_null< TimerManager * > BaseServer::GetTimerManager ()
Get the timer manager for the server.
Returns
Pointer to the timer manager. This shold never be deleted.
Definition at line 277 of file BaseServer.cpp.
References mTimerManager.
bool BaseServer::Initialize () virtual
Initialize the database connection and do anything else that can fail to execute that needs to be handled outside of a constructor.
Parameters
self Pointer to this server to be used as a reference in packet handling code.
Returns
true on success, false on failure
Definition at line 61 of file BaseServer.cpp.
References libcomp::Worker::AddManager(), libcomp::DataStore::AddSearchPaths(), libcomp::String::Arg(), CreateWorkers(), GetConfigPath(), libcomp::TcpServer::GetDiffieHellman(), libcomp::Worker::GetMessageQueue(), libcomp::ServerConstants::Initialize(), libcomp::String::IsEmpty(), libcomp::TcpServer::LoadDiffieHellman(), LOG_CRITICAL, LOG_DEBUG, LOG_WARNING, mConfig, mDataStore, mMainWorker, and libcomp::TcpServer::SetDiffieHellman().
bool BaseServer::InsertDataFromFile (const libcomp::String & filePath, const std::shared_ptr< Database > & db, const std::set< std::string > & specificTypes = {}) protected
Dynamicaly instantiate and insert data from an XML config file.
Records will be created in the order they are listed in the file and are assumed to be valid for the database loaded for the server.
Parameters
filePath Path to the XML config file
db Pointer to the database connection
specificTypes Optional parameter to only load the specified types
Returns
true on success, false if an error occurred
Definition at line 515 of file BaseServer.cpp.
References libcomp::String::C(), LoadDataFromFile(), and LOG_DEBUG.
Referenced by GetDatabase(), and QueueWork().
bool BaseServer::LoadDataFromFile (const libcomp::String & filePath, PersistentObjectMap & records, bool registerRecords, const std::set< std::string > & specificTypes = {}) protected
Dynamicaly instantiate data from an XML config file.
Records will be created in the order they are listed in the file.
Parameters
filePath Path to the XML config file
records Output map of records created by object type
registerRecords If true the loaded records will be registered in the cache when the UID is specified
specificTypes Optional parameter to only load the specified types
Returns
true on success, false if an error occurred
Definition at line 545 of file BaseServer.cpp.
References libcomp::String::C(), libcomp::Decrypt::GenerateRandom(), libcomp::PersistentObject::GetTypeHashByName(), libcomp::Decrypt::HashPassword(), LOG_DEBUG, LOG_ERROR, and libcomp::PersistentObject::New().
Referenced by InsertDataFromFile(), and QueueWork().
DH * TcpServer::LoadDiffieHellman (const String & prime) static inherited
Create a Diffie-Helman key pair given the hex encoded prime.
Parameters
prime Hex encoded string representing the prime.
Returns
Generated key pair or nullptr on failure.
Definition at line 247 of file TcpServer.cpp.
References libcomp::String::C(), DH_BASE_STRING, DH_KEY_HEX_SIZE, DH_SHARED_DATA_SIZE, libcomp::String::Length(), LOG_DEBUG, and LOG_ERROR.
Referenced by Initialize(), libcomp::TcpServer::LoadDiffieHellman(), libcomp::EncryptedConnection::ParseClientEncryptionStart(), and TEST().
DH * TcpServer::LoadDiffieHellman (const std::vector< char > & data) static inherited
Create a Diffie-Helman key pair given the binary encoded prime.
Parameters
data Binary data representing the prime.
Returns
Generated key pair or nullptr on failure.
Definition at line 285 of file TcpServer.cpp.
References libcomp::TcpServer::LoadDiffieHellman().
DH * TcpServer::LoadDiffieHellman (const void * pData, size_t dataSize) static inherited
Create a Diffie-Helman key pair given the binary encoded prime.
Parameters
pData Pointer to buffer containing data representing the prime.
dataSize Size of the data buffer.
Returns
Generated key pair or nullptr on failure.
Definition at line 290 of file TcpServer.cpp.
References DH_BASE_STRING, and DH_SHARED_DATA_SIZE.
bool BaseServer::ProcessMessage (const libcomp::Message::Message * pMessage) virtual
Process a message from the queue.
Parameters
pMessage Message to be processed
Returns
true on success, false on failure
Implements libcomp::Manager.
Definition at line 500 of file BaseServer.cpp.
References FinishInitialize().
template<typename Function , typename... Args> bool libcomp::BaseServer::QueueWork (Function && f, Args &&... args) const inline
Queue up code to be executed in the main worker thread.
Parameters
f Function (lambda) to execute in the worker thread.
args Arguments to pass to the function when it is executed.
Returns
true on success, false on failure
Definition at line 208 of file BaseServer.h.
References AssignMessageQueue(), CreateWorkers(), libcomp::Worker::ExecuteInWorker(), GetNextConnectionWorker(), InsertDataFromFile(), LoadDataFromFile(), mQueueWorker, Run(), and ServerReady().
bool BaseServer::ReadConfig (std::shared_ptr< objects::ServerConfig > config, libcomp::String filePath) static
Read the config file from the path and parse into an XML document to be read in the virtual ReadConfig function.
Messages will print to the console on both success and failure.
Parameters
config Pointer to a config file that will contain properties every server has in common.
configPath File path to the location of the config to be loaded.
Returns
true on success, false on failure
Definition at line 359 of file BaseServer.cpp.
References libcomp::String::C(), LOG_DEBUG, and LOG_WARNING.
bool BaseServer::ReadConfig (std::shared_ptr< objects::ServerConfig > config, tinyxml2::XMLDocument & doc) static
Read the config file values from an XML document and populates the config passed in.
Parameters
config Pointer to a config file that will contain properties every server has in common.
doc XML file containing the config values.
Returns
true on success, false on failure
Definition at line 376 of file BaseServer.cpp.
References libcomp::Log::GetSingletonPtr(), libcomp::Log::LOG_LEVEL_CRITICAL, libcomp::Log::LOG_LEVEL_DEBUG, libcomp::Log::LOG_LEVEL_ERROR, libcomp::Log::LOG_LEVEL_INFO, and libcomp::Log::LOG_LEVEL_WARNING.
void TcpServer::RemoveConnection (std::shared_ptr< TcpConnection > & connection) inherited
Remove a connection from the list of client connections.
Parameters
connection Connection to remove.
Definition at line 127 of file TcpServer.cpp.
References libcomp::TcpServer::mConnections, and libcomp::TcpServer::mConnectionsLock.
int BaseServer::Run () protected virtual
Runs the server until a shutdown message is received or the program is forcefully closed.
Returns
0 on success, 1 on failure
Reimplemented from libcomp::TcpServer.
Definition at line 282 of file BaseServer.cpp.
References Cleanup(), mMainWorker, mQueueWorker, libcomp::TcpServer::mService, and libcomp::Worker::Start().
Referenced by QueueWork().
std::vector< char > TcpServer::SaveDiffieHellman (const DH * pDiffieHellman) static inherited
Save a Diffie-Hellman key pair (the prime) to a binary buffer.
Parameters
pDiffieHellman Key pair to save.
Returns
Buffer containing the prime (empty on failure).
Definition at line 317 of file TcpServer.cpp.
References DH_SHARED_DATA_SIZE.
Referenced by TEST().
void BaseServer::ServerReady () protected virtual
Called when the server has started.
Reimplemented from libcomp::TcpServer.
Definition at line 299 of file BaseServer.cpp.
References LOG_DEBUG, mCommandLine, and libcomp::TcpServer::ServerReady().
Referenced by QueueWork().
void BaseServer::SetConfigPath (const std::string & path) static
Set a custom config directory path.
Parameters
path Config directory path to use during execution
Definition at line 339 of file BaseServer.cpp.
References sConfigPath.
void TcpServer::SetDiffieHellman (DH * pDiffieHellman) protected inherited
Set the Diffie-Hellman key pair used by this server.
Parameters
pDiffieHellman Pointer to the key pair to use.
Definition at line 215 of file TcpServer.cpp.
References libcomp::TcpServer::mDiffieHellman.
Referenced by Initialize().
void BaseServer::Shutdown () virtual
Call the Shutdown function on each worker.
This should be called only before preparing to stop the application.
Definition at line 316 of file BaseServer.cpp.
References mMainWorker, mQueueWorker, mWorkers, and libcomp::Worker::Shutdown().
Referenced by ShutdownSignalHandler().
int TcpServer::Start () virtual inherited
Start a thread that listens for incoming network connections.
This call will block until the server is stopped. This will call Run for the main loop. In the BaseServer implementation this will run a main worker thread.
See also
BaseServer
Worker
Returns
Code indicating the exit status.
Definition at line 58 of file TcpServer.cpp.
References libcomp::TcpServer::AcceptHandler(), libcomp::TcpServer::GenerateDiffieHellman(), libcomp::TcpConnection::GetDiffieHellmanPrime(), libcomp::String::IsEmpty(), LOG_CRITICAL, LOG_WARNING, libcomp::TcpServer::mAcceptor, libcomp::TcpServer::mDiffieHellman, libcomp::TcpServer::mListenAddress, libcomp::TcpServer::mPort, libcomp::TcpServer::mService, libcomp::TcpServer::mServiceThread, libcomp::TcpServer::Run(), libcomp::TcpServer::ServerReady(), libcomp::String::ToLower(), and libcomp::String::ToUtf8().
Member Data Documentation
std::shared_ptr<ServerCommandLineParser> libcomp::BaseServer::mCommandLine protected
Command line options for the server.
Definition at line 284 of file BaseServer.h.
Referenced by ServerReady().
std::shared_ptr<objects::ServerConfig> libcomp::BaseServer::mConfig protected
A shared pointer to the config used to set up the server.
Definition at line 281 of file BaseServer.h.
Referenced by CreateWorkers(), GetConfig(), GetDatabase(), and Initialize().
std::list<std::shared_ptr<TcpConnection> > libcomp::TcpServer::mConnections protected inherited
List of connections managed by this server.
Definition at line 179 of file TcpServer.h.
Referenced by libcomp::TcpServer::AcceptHandler(), and libcomp::TcpServer::RemoveConnection().
std::mutex libcomp::TcpServer::mConnectionsLock protected inherited
Lock for the connection list.
Definition at line 176 of file TcpServer.h.
Referenced by libcomp::TcpServer::AcceptHandler(), and libcomp::TcpServer::RemoveConnection().
libcomp::DataStore libcomp::BaseServer::mDataStore protected
Data store for the server.
Definition at line 296 of file BaseServer.h.
Referenced by GetDataStore(), and Initialize().
libcomp::Worker libcomp::BaseServer::mMainWorker protected
Worker that blocks and runs in the main thread.
Definition at line 287 of file BaseServer.h.
Referenced by Initialize(), Run(), and Shutdown().
libcomp::Worker libcomp::BaseServer::mQueueWorker protected
Worker used for async processing.
Definition at line 290 of file BaseServer.h.
Referenced by QueueWork(), Run(), and Shutdown().
asio::io_service libcomp::TcpServer::mService protected inherited
ASIO service used to handle network operations.
Definition at line 182 of file TcpServer.h.
Referenced by Run(), and libcomp::TcpServer::Start().
libcomp::TimerManager libcomp::BaseServer::mTimerManager protected
Manager for timer events.
Definition at line 299 of file BaseServer.h.
Referenced by GetTimerManager().
std::list<std::shared_ptr<libcomp::Worker> > libcomp::BaseServer::mWorkers protected
List of workers to handle incoming connection packet based work.
Definition at line 293 of file BaseServer.h.
Referenced by AssignMessageQueue(), CreateWorkers(), GetNextConnectionWorker(), Shutdown(), and ~BaseServer().
std::string BaseServer::sConfigPath static protected
Custom config path to use during execution.
Definition at line 302 of file BaseServer.h.
Referenced by GetConfigPath(), and SetConfigPath().
The documentation for this class was generated from the following files:
BaseServer.h
BaseServer.cpp