COMP_hack: libcomp::TcpServer Class Reference
libcomp::TcpServer Class Reference
Listen for new TCP/IP connections.
#include <TcpServer.h>
Public Member Functions
TcpServer (const String &listenAddress, uint16_t port)
Create a TCP server to listen on a specific address and port.
virtual ~TcpServer ()
Cleanup the server and stop listening for new connections.
void RemoveConnection (std::shared_ptr< TcpConnection > &connection)
Remove a connection from the list of client connections.
virtual int Start ()
Start a thread that listens for incoming network connections.
Static Public Member Functions
static DH * CopyDiffieHellman (const DH *pDiffieHellman)
Copy a Diffie-Hellman key pair.
static DH * GenerateDiffieHellman ()
Generate a Diffie-Hellman key pair.
static DH * LoadDiffieHellman (const String &prime)
Create a Diffie-Helman key pair given the hex encoded prime.
static DH * LoadDiffieHellman (const std::vector< char > &data)
Create a Diffie-Helman key pair given the binary encoded prime.
static DH * LoadDiffieHellman (const void *pData, size_t dataSize)
Create a Diffie-Helman key pair given the binary encoded prime.
static std::vector< char > SaveDiffieHellman (const DH *pDiffieHellman)
Save a Diffie-Hellman key pair (the prime) to a binary buffer.
Protected Member Functions
void AcceptHandler (asio::error_code errorCode, asio::ip::tcp::socket &socket)
Called to handle a new connection to the server.
virtual std::shared_ptr< TcpConnection > CreateConnection (asio::ip::tcp::socket &socket)
Create a connection to a newly active socket.
const DH * GetDiffieHellman () const
Get the Diffie-Hellman key pair used by this server.
virtual int Run ()
Main loop for the server.
virtual void ServerReady ()
Called when the server has started.
void SetDiffieHellman (DH *pDiffieHellman)
Set the Diffie-Hellman key pair used by this server.
Protected Attributes
std::list< std::shared_ptr< TcpConnection > > mConnections
List of connections managed by this server.
std::mutex mConnectionsLock
Lock for the connection list.
asio::io_service mService
ASIO service used to handle network operations.
Private Attributes
asio::ip::tcp::acceptor mAcceptor
Asynchronous acceptor for new connections.
DH * mDiffieHellman
Diffie-Hellman key pair used to encrypt connections.
String mListenAddress
Address the server is listening on.
uint16_t mPort
Port the address is listening on.
std::thread mServiceThread
Thread that runs the ASIO service.
Detailed Description
Listen for new TCP/IP connections.
This class will listen for new TCP/IP connections on the given address and port. If the address specified is blank or "any" it will listen for connections on all network devices. The CreateConnection function should be overridden if a subclass of TcpConnection is required or additional setup should be performed.
Definition at line 58 of file TcpServer.h.
Constructor & Destructor Documentation
TcpServer::TcpServer (const String & listenAddress, uint16_t port)
Create a TCP server to listen on a specific address and port.
Parameters
listenAddress Listen on the specified IP address. If blank or "any" this will listen on all network adapters.
port Port to listen for incoming connections.
Definition at line 40 of file TcpServer.cpp.
TcpServer::~TcpServer () virtual
Cleanup the server and stop listening for new connections.
Definition at line 50 of file TcpServer.cpp.
References mDiffieHellman.
Member Function Documentation
void TcpServer::AcceptHandler (asio::error_code errorCode, asio::ip::tcp::socket & socket) protected
Called to handle a new connection to the server.
This will call CreateConnection and then add the connection to the list.
Parameters
errorCode Error code of the last accept operation.
socket Socket that was bound to the new connection.
Definition at line 164 of file TcpServer.cpp.
References CreateConnection(), LOG_CRITICAL, LOG_DEBUG, LOG_ERROR, mAcceptor, mConnections, mConnectionsLock, and mDiffieHellman.
Referenced by Start().
DH * TcpServer::CopyDiffieHellman (const DH * pDiffieHellman) static
Copy a Diffie-Hellman key pair.
Note
This will not copy the private key (just the base and prime).
Parameters
pDiffieHellman Diffie-Hellman key pair to copy.
Returns
Copied key pair or nullptr on failure.
Definition at line 334 of file TcpServer.cpp.
Referenced by CreateConnection(), and TEST().
std::shared_ptr< TcpConnection > TcpServer::CreateConnection (asio::ip::tcp::socket & socket) protected virtual
Create a connection to a newly active socket.
Parameters
socket A new socket connection.
Returns
Pointer to the newly created connection
Definition at line 157 of file TcpServer.cpp.
References CopyDiffieHellman(), and mDiffieHellman.
Referenced by AcceptHandler().
DH * TcpServer::GenerateDiffieHellman () static
Generate a Diffie-Hellman key pair.
Returns
Generated key pair or nullptr on failure.
Definition at line 225 of file TcpServer.cpp.
References DH_BASE_INT, DH_KEY_BIT_SIZE, and DH_SHARED_DATA_SIZE.
Referenced by Start(), and TEST().
const DH * TcpServer::GetDiffieHellman () const protected
Get the Diffie-Hellman key pair used by this server.
Returns
Key pair or nullptr if one is not set.
Definition at line 210 of file TcpServer.cpp.
References mDiffieHellman.
Referenced by libcomp::BaseServer::Initialize().
DH * TcpServer::LoadDiffieHellman (const String & prime) static
Create a Diffie-Helman key pair given the hex encoded prime.
Parameters
prime Hex encoded string representing the prime.
Returns
Generated key pair or nullptr on failure.
Definition at line 247 of file TcpServer.cpp.
References libcomp::String::C(), DH_BASE_STRING, DH_KEY_HEX_SIZE, DH_SHARED_DATA_SIZE, libcomp::String::Length(), LOG_DEBUG, and LOG_ERROR.
Referenced by libcomp::BaseServer::Initialize(), LoadDiffieHellman(), libcomp::EncryptedConnection::ParseClientEncryptionStart(), and TEST().
DH * TcpServer::LoadDiffieHellman (const std::vector< char > & data) static
Create a Diffie-Helman key pair given the binary encoded prime.
Parameters
data Binary data representing the prime.
Returns
Generated key pair or nullptr on failure.
Definition at line 285 of file TcpServer.cpp.
References LoadDiffieHellman().
DH * TcpServer::LoadDiffieHellman (const void * pData, size_t dataSize) static
Create a Diffie-Helman key pair given the binary encoded prime.
Parameters
pData Pointer to buffer containing data representing the prime.
dataSize Size of the data buffer.
Returns
Generated key pair or nullptr on failure.
Definition at line 290 of file TcpServer.cpp.
References DH_BASE_STRING, and DH_SHARED_DATA_SIZE.
void TcpServer::RemoveConnection (std::shared_ptr< TcpConnection > & connection)
Remove a connection from the list of client connections.
Parameters
connection Connection to remove.
Definition at line 127 of file TcpServer.cpp.
References mConnections, and mConnectionsLock.
int TcpServer::Run () protected virtual
Main loop for the server.
Returns
Code indicating the exit status.
Reimplemented in libcomp::BaseServer.
Definition at line 139 of file TcpServer.cpp.
Referenced by Start().
std::vector< char > TcpServer::SaveDiffieHellman (const DH * pDiffieHellman) static
Save a Diffie-Hellman key pair (the prime) to a binary buffer.
Parameters
pDiffieHellman Key pair to save.
Returns
Buffer containing the prime (empty on failure).
Definition at line 317 of file TcpServer.cpp.
References DH_SHARED_DATA_SIZE.
Referenced by TEST().
void TcpServer::ServerReady () protected virtual
Called when the server has started.
Reimplemented in libcomp::BaseServer.
Definition at line 144 of file TcpServer.cpp.
References LOG_INFO.
Referenced by libcomp::BaseServer::ServerReady(), and Start().
void TcpServer::SetDiffieHellman (DH * pDiffieHellman) protected
Set the Diffie-Hellman key pair used by this server.
Parameters
pDiffieHellman Pointer to the key pair to use.
Definition at line 215 of file TcpServer.cpp.
References mDiffieHellman.
Referenced by libcomp::BaseServer::Initialize().
int TcpServer::Start () virtual
Start a thread that listens for incoming network connections.
This call will block until the server is stopped. This will call Run for the main loop. In the BaseServer implementation this will run a main worker thread.
See also
BaseServer
Worker
Returns
Code indicating the exit status.
Definition at line 58 of file TcpServer.cpp.
References AcceptHandler(), GenerateDiffieHellman(), libcomp::TcpConnection::GetDiffieHellmanPrime(), libcomp::String::IsEmpty(), LOG_CRITICAL, LOG_WARNING, mAcceptor, mDiffieHellman, mListenAddress, mPort, mService, mServiceThread, Run(), ServerReady(), libcomp::String::ToLower(), and libcomp::String::ToUtf8().
Member Data Documentation
asio::ip::tcp::acceptor libcomp::TcpServer::mAcceptor private
Asynchronous acceptor for new connections.
Definition at line 186 of file TcpServer.h.
Referenced by AcceptHandler(), and Start().
std::list<std::shared_ptr<TcpConnection> > libcomp::TcpServer::mConnections protected
List of connections managed by this server.
Definition at line 179 of file TcpServer.h.
Referenced by AcceptHandler(), and RemoveConnection().
std::mutex libcomp::TcpServer::mConnectionsLock protected
Lock for the connection list.
Definition at line 176 of file TcpServer.h.
Referenced by AcceptHandler(), and RemoveConnection().
DH* libcomp::TcpServer::mDiffieHellman private
Diffie-Hellman key pair used to encrypt connections.
Definition at line 192 of file TcpServer.h.
Referenced by AcceptHandler(), CreateConnection(), GetDiffieHellman(), SetDiffieHellman(), Start(), and ~TcpServer().
String libcomp::TcpServer::mListenAddress private
Address the server is listening on.
Definition at line 195 of file TcpServer.h.
Referenced by Start().
uint16_t libcomp::TcpServer::mPort private
Port the address is listening on.
Definition at line 198 of file TcpServer.h.
Referenced by Start().
asio::io_service libcomp::TcpServer::mService protected
ASIO service used to handle network operations.
Definition at line 182 of file TcpServer.h.
Referenced by libcomp::BaseServer::Run(), and Start().
std::thread libcomp::TcpServer::mServiceThread private
Thread that runs the ASIO service.
Definition at line 189 of file TcpServer.h.
Referenced by Start().
The documentation for this class was generated from the following files:
TcpServer.h
TcpServer.cpp