COMP_hack: Exception.cpp File Reference
Exception.cpp File Reference
Implementation of the base Exception class.
#include "Exception.h"
#include "Constants.h"
#include "Log.h"
#include <regex_ext>
#include <execinfo.h>
#include <cxxabi.h>
#include <climits>
#include <cstdlib>
#include <exception>
#include <iomanip>
#include <sstream>
#include <signal.h>
Macros
#define EXCEPTION_STRIP_MODULE (0)
If the module name should be stripped from the backtrace.
Functions
static void SignalHandler (int sig)
Variables
static size_t baseLen = strlen(__FILE__) - strlen("libcomp/src/Exception.cpp")
Length of the absolute path to the source directory to strip from backtrace paths.
Detailed Description
Implementation of the base Exception class.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the COMP_hack Library (libcomp).
Copyright (C) 2012-2018 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file Exception.cpp.
Macro Definition Documentation
#define EXCEPTION_STRIP_MODULE (0)
If the module name should be stripped from the backtrace.
Definition at line 52 of file Exception.cpp.
Function Documentation
static void SignalHandler (int sig) static
Definition at line 379 of file Exception.cpp.
References libcomp::Exception::Backtrace(), and LOG_CRITICAL.
Referenced by libcomp::Exception::RegisterSignalHandler().
Variable Documentation
size_t baseLen = strlen(__FILE__) - strlen("libcomp/src/Exception.cpp") static
Length of the absolute path to the source directory to strip from backtrace paths.
Calculate the length of the path to the project so we may remove that portion of the path from the exception.
Definition at line 69 of file Exception.cpp.
Referenced by libcomp::Exception::File().