COMP_hack: libcomp::Decrypt Namespace Reference
libcomp::Decrypt Namespace Reference
Encryption and Decryption functions.
Functions
void Decrypt (const BF_KEY &key, void *pData, uint32_t dataSize)
Decrypt a data buffer with Blowfish.
void Decrypt (const BF_KEY &key, std::vector< char > &data, std::vector< char >::size_type realSize=0)
Decrypt a data buffer with Blowfish.
void Decrypt (std::vector< char > &data, std::vector< char >::size_type realSize=0)
Decrypt a data buffer with the default Blowfish key.
void DecryptCbc (const BF_KEY &key, uint64_t &initializationVector, std::vector< char > &data, std::vector< char >::size_type realSize=0)
Decrypt a data buffer with Blowfish and Cipher Block Chaining (CBC).
void DecryptCbc (std::vector< char > &data, std::vector< char >::size_type realSize=0)
Decrypt a data buffer with the default Blowfish key and Cipher Block Chaining (CBC) initialization vector (IV).
bool DecryptFile (std::vector< char > &buffer)
Decrypt a file buffer.
std::vector< char > DecryptFile (const std::string &path)
Decrypt a file into a buffer.
void DecryptPacket (const BF_KEY &key, Packet &p)
Decrypt a packet.
void Encrypt (const BF_KEY &key, void *pData, uint32_t dataSize)
Encrypt a data buffer with Blowfish.
void Encrypt (const BF_KEY &key, std::vector< char > &data)
Encrypt a data buffer with Blowfish.
void Encrypt (std::vector< char > &data)
Encrypt a data buffer with the default Blowfish key.
void EncryptCbc (const BF_KEY &key, uint64_t &initializationVector, std::vector< char > &data)
Encrypt a data buffer with Blowfish and Cipher Block Chaining (CBC).
void EncryptCbc (std::vector< char > &data)
Encrypt a data buffer with the default Blowfish key and Cipher Block Chaining (CBC) initialization vector (IV).
bool EncryptFile (std::vector< char > &data)
Encrypt a file buffer.
bool EncryptFile (const std::string &path, const std::vector< char > &data)
Encrypt a file from a buffer.
void EncryptPacket (const BF_KEY &key, Packet &p)
Encrypt a packet.
String GenDiffieHellman (const String &g, const String &p, const String &a, int outputSize=-1)
Generate the result of the operation g^a % p.
String GenerateRandom (int sz=-1)
Generates random data to be used during key exchange.
uint32_t GenerateSessionKey ()
Generates a random value.
String HashPassword (const String &password, const String &salt)
Generate a password hash.
std::vector< char > LoadFile (const std::string &path, int requestedSize=-1)
Load a file into a buffer.
String MD5 (const std::vector< char > &data)
Generate a MD5 hash of the given data.
String SHA1 (const std::vector< char > &data)
Generate a SHA-1 hash of the given data.
Detailed Description
Encryption and Decryption functions.
Function Documentation
void libcomp::Decrypt::Decrypt (const BF_KEY & key, void * pData, uint32_t dataSize)
Decrypt a data buffer with Blowfish.
Parameters
key Blowfish key to decrypt with.
pData Data to be decrypted.
dataSize Size of the data to be decrypted (in bytes).
Note
The data size should be a multiple of BLOWFISH_BLOCK_SIZE.
Definition at line 546 of file src/Decrypt.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE.
Referenced by Decrypt(), and DecryptPacket().
void libcomp::Decrypt::Decrypt (const BF_KEY & key, std::vector< char > & data, std::vector< char >::size_type realSize = 0)
Decrypt a data buffer with Blowfish.
Parameters
key Blowfish key to decrypt with.
data Data to be decrypted.
realSize Size to shrink the buffer to after decryption.
Definition at line 563 of file src/Decrypt.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE.
void libcomp::Decrypt::Decrypt (std::vector< char > & data, std::vector< char >::size_type realSize = 0)
Decrypt a data buffer with the default Blowfish key.
Parameters
data Data to be decrypted.
realSize Size to shrink the buffer to after decryption.
See also
Config::ENCRYPTED_FILE_KEY
Definition at line 588 of file src/Decrypt.cpp.
References Decrypt(), and gFileEncryptionKey.
void libcomp::Decrypt::DecryptCbc (const BF_KEY & key, uint64_t & initializationVector, std::vector< char > & data, std::vector< char >::size_type realSize = 0)
Decrypt a data buffer with Blowfish and Cipher Block Chaining (CBC).
Parameters
key Blowfish key to decrypt with.
initializationVector Initial value to feed into the CBC algorithm.
data Data to be decrypted.
realSize Size to shrink the buffer to after decryption.
Definition at line 643 of file src/Decrypt.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE.
Referenced by DecryptCbc(), and DecryptFile().
void libcomp::Decrypt::DecryptCbc (std::vector< char > & data, std::vector< char >::size_type realSize = 0)
Decrypt a data buffer with the default Blowfish key and Cipher Block Chaining (CBC) initialization vector (IV).
Parameters
data Data to be decrypted.
realSize Size to shrink the buffer to after decryption.
See also
Config::ENCRYPTED_FILE_KEY
Config::ENCRYPTED_FILE_IV
Definition at line 684 of file src/Decrypt.cpp.
References DecryptCbc(), libcomp::Config::ENCRYPTED_FILE_IV, and gFileEncryptionKey.
bool libcomp::Decrypt::DecryptFile (std::vector< char > & buffer)
Decrypt a file buffer.
Parameters
buffer Buffer of the file to be decrypted.
Return values
true File was decrypted.
false File was not decrypted.
See also
Decrypt::EncryptFile
Config::ENCRYPTED_FILE_MAGIC
Config::ENCRYPTED_FILE_KEY
Config::ENCRYPTED_FILE_IV
Definition at line 124 of file src/Decrypt.cpp.
References DecryptCbc(), libcomp::Config::ENCRYPTED_FILE_MAGIC, and EncryptedFileHeader_t.
Referenced by libcomp::DataStore::DecryptFile(), DecryptFile(), and TEST().
std::vector< char > libcomp::Decrypt::DecryptFile (const std::string & path)
Decrypt a file into a buffer.
Parameters
path Path to the file to be decrypted.
Returns
Buffer of the decrypted file. Will be empty if an error occurred.
See also
Decrypt::EncryptFile
Config::ENCRYPTED_FILE_MAGIC
Config::ENCRYPTED_FILE_KEY
Config::ENCRYPTED_FILE_IV
Definition at line 159 of file src/Decrypt.cpp.
References DecryptFile(), and LoadFile().
void libcomp::Decrypt::DecryptPacket (const BF_KEY & key, Packet & p)
Decrypt a packet.
Parameters
key The blowfish key to use.
p The packet to decrypt.
Definition at line 727 of file src/Decrypt.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE, libcomp::Packet::Data(), Decrypt(), libcomp::ReadOnlyPacket::ReadU32Big(), libcomp::ReadOnlyPacket::Rewind(), and libcomp::ReadOnlyPacket::Size().
Referenced by libcomp::EncryptedConnection::ParsePacket().
void libcomp::Decrypt::Encrypt (const BF_KEY & key, void * pData, uint32_t dataSize)
Encrypt a data buffer with Blowfish.
Parameters
key Blowfish key to encrypt with.
pData Data to be encrypted.
dataSize Size of the data to be encrypted (in bytes).
Note
The data size should be a multiple of BLOWFISH_BLOCK_SIZE.
Definition at line 498 of file src/Decrypt.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE.
Referenced by Encrypt(), and EncryptPacket().
void libcomp::Decrypt::Encrypt (const BF_KEY & key, std::vector< char > & data)
Encrypt a data buffer with Blowfish.
Parameters
key Blowfish key to encrypt with.
data Data to be encrypted. The size may change on return.
Definition at line 515 of file src/Decrypt.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE.
void libcomp::Decrypt::Encrypt (std::vector< char > & data)
Encrypt a data buffer with the default Blowfish key.
Parameters
data Data to be encrypted. The size may change on return.
See also
Config::ENCRYPTED_FILE_KEY
Definition at line 541 of file src/Decrypt.cpp.
References Encrypt(), and gFileEncryptionKey.
void libcomp::Decrypt::EncryptCbc (const BF_KEY & key, uint64_t & initializationVector, std::vector< char > & data)
Encrypt a data buffer with Blowfish and Cipher Block Chaining (CBC).
Parameters
key Blowfish key to encrypt with.
initializationVector Initial value to feed into the CBC algorithm.
data Data to be encrypted. The size may change on return.
Definition at line 594 of file src/Decrypt.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE.
Referenced by EncryptCbc(), and EncryptFile().
void libcomp::Decrypt::EncryptCbc (std::vector< char > & data)
Encrypt a data buffer with the default Blowfish key and Cipher Block Chaining (CBC) initialization vector (IV).
Parameters
data Data to be encrypted. The size may change on return.
See also
Config::ENCRYPTED_FILE_KEY
Config::ENCRYPTED_FILE_IV
Definition at line 635 of file src/Decrypt.cpp.
References EncryptCbc(), libcomp::Config::ENCRYPTED_FILE_IV, and gFileEncryptionKey.
bool libcomp::Decrypt::EncryptFile (std::vector< char > & data)
Encrypt a file buffer.
Parameters
buffer Buffer of the file to be encrypted.
Return values
true File was encrypted.
false File was not encrypted.
See also
Decrypt::DecryptFile
Config::ENCRYPTED_FILE_MAGIC
Config::ENCRYPTED_FILE_KEY
Config::ENCRYPTED_FILE_IV
Definition at line 168 of file src/Decrypt.cpp.
References EncryptCbc(), libcomp::Config::ENCRYPTED_FILE_MAGIC, and EncryptedFileHeader_t.
Referenced by libcomp::DataStore::EncryptFile(), and TEST().
bool libcomp::Decrypt::EncryptFile (const std::string & path, const std::vector< char > & data)
Encrypt a file from a buffer.
Parameters
Path to the file to be written to.
data Data to be encrypted.
Return values
true File was encrypted.
false File was not encrypted.
See also
Decrypt::DecryptFile
Config::ENCRYPTED_FILE_MAGIC
Config::ENCRYPTED_FILE_KEY
Config::ENCRYPTED_FILE_IV
Definition at line 184 of file src/Decrypt.cpp.
References EncryptCbc(), libcomp::Config::ENCRYPTED_FILE_MAGIC, and EncryptedFileHeader_t.
void libcomp::Decrypt::EncryptPacket (const BF_KEY & key, Packet & p)
Encrypt a packet.
Parameters
key The blowfish key to use.
p The packet to encrypt.
Definition at line 693 of file src/Decrypt.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE, libcomp::Packet::Data(), Encrypt(), libcomp::ReadOnlyPacket::End(), libcomp::ReadOnlyPacket::Rewind(), libcomp::ReadOnlyPacket::Seek(), libcomp::ReadOnlyPacket::Size(), libcomp::Packet::WriteBlank(), and libcomp::Packet::WriteU32Big().
Referenced by libcomp::ChannelConnection::PreparePackets(), and libcomp::EncryptedConnection::PreparePackets().
String libcomp::Decrypt::GenDiffieHellman (const String & g, const String & p, const String & a, int outputSize = -1)
Generate the result of the operation g^a % p.
Parameters
g Base number represented as a base-16 string.
p Prime number represented as a base-16 string.
a Secret number represented as a base-16 string.
outputSize Number of characters to output. Smaller values will be padded with zeros. Any value of 0 or less will disable output padding.
Returns
A base-16 string representing the operation g^a % p or an empty string if an error occured.
Definition at line 392 of file src/Decrypt.cpp.
References libcomp::String::C(), and libcomp::String::RightJustified().
Referenced by TEST().
String libcomp::Decrypt::GenerateRandom (int sz = -1)
Generates random data to be used during key exchange.
The returned data will be a series of hex digits.
Parameters
sz Number of digits of random data to generate. If -1 is used, the default number of digits will be generated (80 digits).
Returns
The random data encoded as a base-16 string or an empty string if an error occured.
Definition at line 255 of file src/Decrypt.cpp.
References EXCEPTION, libcomp::Platform::GetLastErrorString(), and LoadFile().
Referenced by libcomp::BaseServer::LoadDataFromFile(), libcomp::Randomizer::SeedRNG(), and TEST().
uint32_t libcomp::Decrypt::GenerateSessionKey ()
Generates a random value.
This value is used to identify a login session when passing an authenticated user from the lobby server to the channel server.
Returns
Random value to identify a transitioning client or 0 if an error occured.
Definition at line 340 of file src/Decrypt.cpp.
References LoadFile().
Referenced by TEST().
String libcomp::Decrypt::HashPassword (const String & password, const String & salt)
Generate a password hash.
Parameters
password Clear text password to hash.
salt Salt to append to the password before hashing.
Returns
Hash for the given password.
Definition at line 747 of file src/Decrypt.cpp.
References libcomp::String::ToUtf8().
Referenced by libcomp::BaseServer::LoadDataFromFile().
std::vector< char > libcomp::Decrypt::LoadFile (const std::string & path, int requestedSize = -1)
Load a file into a buffer.
Parameters
path Path to the file to be loaded.
requestedSize Number of bytes to read from the file. If this is negative, the entire file will be read.
Returns
The loaded file data or an empty vector if an error occured.
Definition at line 205 of file src/Decrypt.cpp.
Referenced by DecryptFile(), GenerateRandom(), GenerateSessionKey(), libcomp::ScriptEngine::Include(), and TEST().
String libcomp::Decrypt::MD5 (const std::vector< char > & data)
Generate a MD5 hash of the given data.
Parameters
data Data to generate the hash of.
Returns
MD5 hash string of the given data.
Definition at line 794 of file src/Decrypt.cpp.
String libcomp::Decrypt::SHA1 (const std::vector< char > & data)
Generate a SHA-1 hash of the given data.
Parameters
data Data to generate the hash of.
Returns
SHA-1 hash string of the given data.
Definition at line 771 of file src/Decrypt.cpp.
Referenced by libcomp::DataStore::GetHash().