COMP_hack: Decrypt.cpp File Reference
tests/Decrypt.cpp File Reference
Encryption unit tests.
#include <PushIgnore.h>
#include <gtest/gtest.h>
#include <PopIgnore.h>
#include <Config.h>
#include <Decrypt.h>
#include <Exception.h>
#include <regex>
Macros
#define TEMP_FILE "/tmp/test.bin"
Functions
int main (int argc, char *argv[])
TEST (GenerateRandom, DefaultsTo80Digits)
TEST (GenerateRandom, OddOutputGeneratesError)
TEST (GenerateRandom, OutputIsHex)
TEST (GenerateRandom, OutputChanges)
TEST (GenerateRandom, SpecificLengthEqualsOutput)
TEST (GenerateRandom, NegativeOrZeroReturnsDefault)
TEST (GenerateSessionKey, ValueIsNotNegative)
TEST (GenerateSessionKey, ValueChangesBetweenCalls)
TEST (Decrypt, LoadFile)
TEST (GenDiffieHellman, EmptyArgsReturnError)
TEST (GenDiffieHellman, BadArgsReturnError)
TEST (GenDiffieHellman, ReturnsCorrectAnswer)
TEST (GenDiffieHellman, PaddingWorks)
TEST (EncryptDecrypt, File)
Detailed Description
Encryption unit tests.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the COMP_hack Library (libcomp).
Copyright (C) 2014-2016 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file tests/Decrypt.cpp.
Macro Definition Documentation
#define TEMP_FILE "/tmp/test.bin"
Referenced by TEST().
Function Documentation
int main (int argc, char * argv[])
Definition at line 245 of file tests/Decrypt.cpp.
TEST (GenerateRandom , DefaultsTo80Digits)
Definition at line 39 of file tests/Decrypt.cpp.
References libcomp::Decrypt::GenerateRandom().
TEST (GenerateRandom , OddOutputGeneratesError)
Definition at line 48 of file tests/Decrypt.cpp.
References libcomp::Decrypt::GenerateRandom().
TEST (GenerateRandom , OutputIsHex)
Definition at line 54 of file tests/Decrypt.cpp.
References libcomp::Decrypt::GenerateRandom().
TEST (GenerateRandom , OutputChanges)
Definition at line 61 of file tests/Decrypt.cpp.
References libcomp::Decrypt::GenerateRandom().
TEST (GenerateRandom , SpecificLengthEqualsOutput)
Definition at line 67 of file tests/Decrypt.cpp.
References libcomp::Decrypt::GenerateRandom().
TEST (GenerateRandom , NegativeOrZeroReturnsDefault)
Definition at line 73 of file tests/Decrypt.cpp.
References libcomp::Decrypt::GenerateRandom().
TEST (GenerateSessionKey , ValueIsNotNegative)
Definition at line 82 of file tests/Decrypt.cpp.
References libcomp::Decrypt::GenerateSessionKey().
TEST (GenerateSessionKey , ValueChangesBetweenCalls)
Definition at line 91 of file tests/Decrypt.cpp.
References libcomp::Decrypt::GenerateSessionKey().
TEST (Decrypt , LoadFile)
Definition at line 104 of file tests/Decrypt.cpp.
References libcomp::Decrypt::LoadFile().
TEST (GenDiffieHellman , EmptyArgsReturnError)
Definition at line 134 of file tests/Decrypt.cpp.
References libcomp::Decrypt::GenDiffieHellman().
TEST (GenDiffieHellman , BadArgsReturnError)
Definition at line 141 of file tests/Decrypt.cpp.
References libcomp::Decrypt::GenDiffieHellman().
TEST (GenDiffieHellman , ReturnsCorrectAnswer)
Definition at line 153 of file tests/Decrypt.cpp.
References libcomp::Decrypt::GenDiffieHellman().
TEST (GenDiffieHellman , PaddingWorks)
Definition at line 164 of file tests/Decrypt.cpp.
References libcomp::Decrypt::GenDiffieHellman().
TEST (EncryptDecrypt , File)
Definition at line 179 of file tests/Decrypt.cpp.
References libcomp::Decrypt::DecryptFile(), libcomp::Config::ENCRYPTED_FILE_MAGIC, libcomp::Decrypt::EncryptFile(), libcomp::Decrypt::LoadFile(), and TEMP_FILE.