COMP_hack: Auth.cpp File Reference
Auth.cpp File Reference
Packet parser to handle authorizing a session with the lobby.
#include "Packets.h"
#include <Decrypt.h>
#include <ErrorCodes.h>
#include <Log.h>
#include <Packet.h>
#include <PacketCodes.h>
#include <ReadOnlyPacket.h>
#include <TcpConnection.h>
#include <Account.h>
#include <AccountLogin.h>
#include <CharacterLogin.h>
#include "AccountManager.h"
#include "LobbyServer.h"
#include "ManagerConnection.h"
Functions
static bool CompleteLogin (const std::shared_ptr< LobbyServer > &server, const std::shared_ptr< libcomp::TcpConnection > &connection, const libcomp::String &sid, const libcomp::String &username)
static bool LoginAuthError (const std::shared_ptr< libcomp::TcpConnection > &connection, ErrorCodes_t errorCode)
static bool NoWebAuthParse (const std::shared_ptr< LobbyServer > &server, const std::shared_ptr< libcomp::TcpConnection > &connection, libcomp::ReadOnlyPacket &p, const libcomp::String &username)
static bool WebAuthParse (const std::shared_ptr< LobbyServer > &server, const std::shared_ptr< libcomp::TcpConnection > &connection, libcomp::ReadOnlyPacket &p, const libcomp::String &username)
Detailed Description
Packet parser to handle authorizing a session with the lobby.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the Lobby Server (lobby).
Copyright (C) 2012-2018 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file Auth.cpp.
Function Documentation
CompleteLogin()
static bool CompleteLogin (const std::shared_ptr< LobbyServer > & server, const std::shared_ptr< libcomp::TcpConnection > & connection, const libcomp::String & sid, const libcomp::String & username) static
Definition at line 62 of file Auth.cpp.
References libcomp::Convert::ENCODING_UTF8, libcomp::String::IsEmpty(), LOG_DEBUG, LoginAuthError(), lobby::state(), to_underlying(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteString16Little().
Referenced by NoWebAuthParse(), and WebAuthParse().
LoginAuthError()
static bool LoginAuthError (const std::shared_ptr< libcomp::TcpConnection > & connection, ErrorCodes_t errorCode) static
Definition at line 50 of file Auth.cpp.
References to_underlying(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by CompleteLogin(), and NoWebAuthParse().
NoWebAuthParse()
static bool NoWebAuthParse (const std::shared_ptr< LobbyServer > & server, const std::shared_ptr< libcomp::TcpConnection > & connection, libcomp::ReadOnlyPacket & p, const libcomp::String & username) static
Definition at line 112 of file Auth.cpp.
References libcomp::String::Arg(), CompleteLogin(), libcomp::Convert::ENCODING_UTF8, libcomp::Decrypt::HashPassword(), LOG_DEBUG, LOG_ERROR, LoginAuthError(), libcomp::ReadOnlyPacket::ReadString16Little(), lobby::state(), and libcomp::String::ToLower().
WebAuthParse()
static bool WebAuthParse (const std::shared_ptr< LobbyServer > & server, const std::shared_ptr< libcomp::TcpConnection > & connection, libcomp::ReadOnlyPacket & p, const libcomp::String & username) static
Definition at line 149 of file Auth.cpp.
References CompleteLogin(), libcomp::Convert::ENCODING_UTF8, LOG_DEBUG, libcomp::ReadOnlyPacket::ReadString16Little(), and libcomp::String::ToLower().