COMP_hack: lobby::ApiHandler Class Reference
lobby::ApiHandler Class Reference
#include <ApiHandler.h>
Public Member Functions
ApiHandler (const std::shared_ptr< objects::LobbyConfig > &config, const std::shared_ptr< lobby::LobbyServer > &server)
virtual ~ApiHandler ()
virtual bool handlePost (CivetServer *pServer, struct mg_connection *pConnection)
void SetAccountManager (AccountManager *pManager)
Protected Member Functions
bool Account_ChangePassword (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Account_ClientLogin (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Account_GetCP (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Account_GetDetails (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Account_Register (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_CreatePromo (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_DeleteAccount (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_DeletePromo (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_GetAccount (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_GetAccounts (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_GetPromos (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_UpdateAccount (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Auth_Token (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Authenticate (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
std::shared_ptr< libcomp::Database > GetDatabase () const
bool WebGame_GetCoins (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool WebGame_Start (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool WebGame_Update (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
int64_t WebGameScript_GetCoins (const std::shared_ptr< ApiSession > &session)
void WebGameScript_SetResponse (JsonBox::Object *response, const libcomp::String &key, const libcomp::String &value)
bool WebGameScript_UpdateCoins (const std::shared_ptr< ApiSession > &session, int64_t coins, bool adjust)
Private Member Functions
bool GetWebGameSession (JsonBox::Object &response, const std::shared_ptr< ApiSession > &session, std::shared_ptr< objects::WebGameSession > &gameSession, std::shared_ptr< World > &world)
Private Attributes
AccountManager * mAccountManager
std::shared_ptr< objects::LobbyConfig > mConfig
std::unordered_map< libcomp::String, std::shared_ptr< libcomp::ServerScript > > mGameDefinitions
std::unordered_map< libcomp::String, std::function< bool(ApiHandler &, const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)> > mParsers
List of API parsers.
std::shared_ptr< lobby::LobbyServer > mServer
std::unordered_map< libcomp::String, std::shared_ptr< ApiSession > > mSessions
Detailed Description
Definition at line 87 of file ApiHandler.h.
Constructor & Destructor Documentation
ApiHandler()
ApiHandler::ApiHandler (const std::shared_ptr< objects::LobbyConfig > & config, const std::shared_ptr< lobby::LobbyServer > & server)
Definition at line 69 of file ApiHandler.cpp.
References Account_ChangePassword(), Account_ClientLogin(), Account_GetCP(), Account_GetDetails(), Account_Register(), Admin_CreatePromo(), Admin_DeleteAccount(), Admin_DeletePromo(), Admin_GetAccount(), Admin_GetAccounts(), Admin_GetPromos(), Admin_UpdateAccount(), Auth_Token(), LOG_DEBUG, LOG_ERROR, mGameDefinitions, mParsers, WebGame_GetCoins(), WebGame_Start(), and WebGame_Update().
Referenced by WebGame_Start().
~ApiHandler()
ApiHandler::~ApiHandler () virtual
Definition at line 122 of file ApiHandler.cpp.
Member Function Documentation
Account_ChangePassword()
bool ApiHandler::Account_ChangePassword (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 237 of file ApiHandler.cpp.
References libcomp::Decrypt::GenerateRandom(), GetDatabase(), libcomp::Decrypt::HashPassword(), and libcomp::String::Matches().
Referenced by ApiHandler().
Account_ClientLogin()
bool ApiHandler::Account_ClientLogin (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 304 of file ApiHandler.cpp.
References ErrorCodeString(), GetDatabase(), mAccountManager, to_underlying(), libcomp::String::ToDecimal(), libcomp::String::ToUtf8(), and lobby::AccountManager::WebAuthLoginApi().
Referenced by ApiHandler().
Account_GetCP()
bool ApiHandler::Account_GetCP (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 180 of file ApiHandler.cpp.
References GetDatabase().
Referenced by ApiHandler().
Account_GetDetails()
bool ApiHandler::Account_GetDetails (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 199 of file ApiHandler.cpp.
References GetDatabase().
Referenced by ApiHandler().
Account_Register()
bool ApiHandler::Account_Register (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 378 of file ApiHandler.cpp.
References libcomp::Decrypt::GenerateRandom(), GetDatabase(), libcomp::Decrypt::HashPassword(), libcomp::String::IsEmpty(), libcomp::String::Matches(), mConfig, and libcomp::String::ToLower().
Referenced by ApiHandler().
Admin_CreatePromo()
bool ApiHandler::Admin_CreatePromo (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Todo:
Check the shop product ID is valid.
Definition at line 827 of file ApiHandler.cpp.
References GetDatabase(), and libcomp::String::IsEmpty().
Referenced by ApiHandler().
Admin_DeleteAccount()
bool ApiHandler::Admin_DeleteAccount (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 588 of file ApiHandler.cpp.
References GetDatabase(), and libcomp::String::ToLower().
Referenced by ApiHandler().
Admin_DeletePromo()
bool ApiHandler::Admin_DeletePromo (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 979 of file ApiHandler.cpp.
References libcomp::String::Arg(), GetDatabase(), libcomp::String::IsEmpty(), and libcomp::String::ToUtf8().
Referenced by ApiHandler().
Admin_GetAccount()
bool ApiHandler::Admin_GetAccount (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 536 of file ApiHandler.cpp.
References GetDatabase(), and libcomp::String::ToLower().
Referenced by ApiHandler().
Admin_GetAccounts()
bool ApiHandler::Admin_GetAccounts (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 485 of file ApiHandler.cpp.
References GetDatabase().
Referenced by ApiHandler().
Admin_GetPromos()
bool ApiHandler::Admin_GetPromos (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 775 of file ApiHandler.cpp.
References GetDatabase().
Referenced by ApiHandler().
Admin_UpdateAccount()
bool ApiHandler::Admin_UpdateAccount (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 626 of file ApiHandler.cpp.
References libcomp::Decrypt::GenerateRandom(), GetDatabase(), libcomp::Decrypt::HashPassword(), libcomp::String::Matches(), and libcomp::String::ToLower().
Referenced by ApiHandler().
Auth_Token()
bool ApiHandler::Auth_Token (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 126 of file ApiHandler.cpp.
References libcomp::Decrypt::GenerateRandom(), GetDatabase(), LOG_ERROR, libcomp::String::ToLower(), and libcomp::String::ToUtf8().
Referenced by ApiHandler().
Authenticate()
bool ApiHandler::Authenticate (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 1335 of file ApiHandler.cpp.
References libcomp::Decrypt::GenerateRandom(), libcomp::Decrypt::HashPassword(), and libcomp::String::ToUtf8().
Referenced by handlePost().
GetDatabase()
std::shared_ptr< libcomp::Database > ApiHandler::GetDatabase () const protected
Definition at line 1378 of file ApiHandler.cpp.
References libcomp::BaseServer::GetDatabase(), and mConfig.
Referenced by Account_ChangePassword(), Account_ClientLogin(), Account_GetCP(), Account_GetDetails(), Account_Register(), Admin_CreatePromo(), Admin_DeleteAccount(), Admin_DeletePromo(), Admin_GetAccount(), Admin_GetAccounts(), Admin_GetPromos(), Admin_UpdateAccount(), and Auth_Token().
GetWebGameSession()
bool ApiHandler::GetWebGameSession (JsonBox::Object & response, const std::shared_ptr< ApiSession > & session, std::shared_ptr< objects::WebGameSession > & gameSession, std::shared_ptr< World > & world) private
Definition at line 1592 of file ApiHandler.cpp.
References mServer, and lobby::WebGameApiSession::webGameSession.
Referenced by WebGame_GetCoins(), WebGame_Start(), and WebGame_Update().
handlePost()
bool ApiHandler::handlePost (CivetServer * pServer, struct mg_connection * pConnection) virtual
Definition at line 1400 of file ApiHandler.cpp.
References Authenticate(), libcomp::String::IsEmpty(), libcomp::String::Left(), LOG_ERROR, MAX_PAYLOAD, libcomp::String::Mid(), mParsers, mServer, and mSessions.
SetAccountManager()
void ApiHandler::SetAccountManager (AccountManager * pManager)
Definition at line 1587 of file ApiHandler.cpp.
References mAccountManager.
WebGame_GetCoins()
bool ApiHandler::WebGame_GetCoins (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 1023 of file ApiHandler.cpp.
References libcomp::String::Arg(), libcomp::String::C(), GetWebGameSession(), and WebGameScript_GetCoins().
Referenced by ApiHandler().
WebGame_Start()
bool ApiHandler::WebGame_Start (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 1049 of file ApiHandler.cpp.
References ApiHandler(), libcomp::String::Arg(), GetWebGameSession(), mGameDefinitions, WebGameScript_GetCoins(), WebGameScript_SetResponse(), and WebGameScript_UpdateCoins().
Referenced by ApiHandler().
WebGame_Update()
bool ApiHandler::WebGame_Update (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 1153 of file ApiHandler.cpp.
References libcomp::String::Arg(), and GetWebGameSession().
Referenced by ApiHandler().
WebGameScript_GetCoins()
int64_t ApiHandler::WebGameScript_GetCoins (const std::shared_ptr< ApiSession > & session) protected
Definition at line 1232 of file ApiHandler.cpp.
References mServer, and lobby::WebGameApiSession::webGameSession.
Referenced by WebGame_GetCoins(), and WebGame_Start().
WebGameScript_SetResponse()
void ApiHandler::WebGameScript_SetResponse (JsonBox::Object * response, const libcomp::String & key, const libcomp::String & value) protected
Definition at line 1262 of file ApiHandler.cpp.
References libcomp::String::C().
Referenced by WebGame_Start().
WebGameScript_UpdateCoins()
bool ApiHandler::WebGameScript_UpdateCoins (const std::shared_ptr< ApiSession > & session, int64_t coins, bool adjust) protected
Definition at line 1271 of file ApiHandler.cpp.
References mServer, and lobby::WebGameApiSession::webGameSession.
Referenced by WebGame_Start().
Member Data Documentation
mAccountManager
AccountManager* lobby::ApiHandler::mAccountManager private
Definition at line 184 of file ApiHandler.h.
Referenced by Account_ClientLogin(), and SetAccountManager().
mConfig
std::shared_ptr<objects::LobbyConfig> lobby::ApiHandler::mConfig private
Definition at line 178 of file ApiHandler.h.
Referenced by Account_Register(), and GetDatabase().
mGameDefinitions
std::unordered_map<libcomp::String, std::shared_ptr<libcomp::ServerScript> > lobby::ApiHandler::mGameDefinitions private
Definition at line 182 of file ApiHandler.h.
Referenced by ApiHandler(), and WebGame_Start().
mParsers
std::unordered_map<libcomp::String, std::function<bool(ApiHandler&, const JsonBox::Object& request, JsonBox::Object& response, const std::shared_ptr<ApiSession>& session)> > lobby::ApiHandler::mParsers private
List of API parsers.
Definition at line 176 of file ApiHandler.h.
Referenced by ApiHandler(), and handlePost().
mServer
std::shared_ptr<lobby::LobbyServer> lobby::ApiHandler::mServer private
Definition at line 179 of file ApiHandler.h.
Referenced by GetWebGameSession(), handlePost(), WebGameScript_GetCoins(), and WebGameScript_UpdateCoins().
mSessions
std::unordered_map<libcomp::String, std::shared_ptr<ApiSession> > lobby::ApiHandler::mSessions private
Definition at line 171 of file ApiHandler.h.
Referenced by handlePost().
The documentation for this class was generated from the following files:
ApiHandler.h
ApiHandler.cpp