COMP_hack: lobby::ImportHandler Class Reference
lobby::ImportHandler Class Reference
#include <ImportHandler.h>
Public Member Functions
ImportHandler (const std::shared_ptr< objects::LobbyConfig > &config, const std::shared_ptr< lobby::LobbyServer > &server)
virtual ~ImportHandler ()
virtual bool handlePost (CivetServer *pServer, struct mg_connection *pConnection)
Private Member Functions
libcomp::String ExtractFile (const libcomp::String &contentType, const libcomp::String &contentData)
Private Attributes
std::shared_ptr< objects::LobbyConfig > mConfig
std::shared_ptr< lobby::LobbyServer > mServer
Detailed Description
Definition at line 47 of file ImportHandler.h.
Constructor & Destructor Documentation
ImportHandler()
ImportHandler::ImportHandler (const std::shared_ptr< objects::LobbyConfig > & config, const std::shared_ptr< lobby::LobbyServer > & server)
Definition at line 42 of file ImportHandler.cpp.
~ImportHandler()
ImportHandler::~ImportHandler () virtual
Definition at line 49 of file ImportHandler.cpp.
Member Function Documentation
ExtractFile()
libcomp::String ImportHandler::ExtractFile (const libcomp::String & contentType, const libcomp::String & contentData) private
Definition at line 176 of file ImportHandler.cpp.
References libcomp::String::Arg(), libcomp::String::IsEmpty(), libcomp::String::LeftOf(), libcomp::String::Mid(), libcomp::String::Split(), and libcomp::String::Trimmed().
Referenced by handlePost().
handlePost()
bool ImportHandler::handlePost (CivetServer * pServer, struct mg_connection * pConnection) virtual
Definition at line 53 of file ImportHandler.cpp.
References ExtractFile(), libcomp::String::IsEmpty(), MAX_PAYLOAD, mConfig, mServer, and libcomp::String::ToUtf8().
Member Data Documentation
mConfig
std::shared_ptr<objects::LobbyConfig> lobby::ImportHandler::mConfig private
Definition at line 62 of file ImportHandler.h.
Referenced by handlePost().
mServer
std::shared_ptr<lobby::LobbyServer> lobby::ImportHandler::mServer private
Definition at line 63 of file ImportHandler.h.
Referenced by handlePost().
The documentation for this class was generated from the following files:
ImportHandler.h
ImportHandler.cpp