COMP_hack: lobby::LoginHandler Class Reference
lobby::LoginHandler Class Reference
#include <LoginWebHandler.h>
Public Member Functions
LoginHandler (const std::shared_ptr< libcomp::Database > &database)
virtual ~LoginHandler ()
virtual bool handleGet (CivetServer *pServer, struct mg_connection *pConnection)
virtual bool handlePost (CivetServer *pServer, struct mg_connection *pConnection)
void SetAccountManager (AccountManager *pManager)
void SetConfig (const std::shared_ptr< objects::LobbyConfig > &config)
Private Member Functions
bool HandlePage (CivetServer *pServer, struct mg_connection *pConnection, const std::shared_ptr< objects::LoginScriptRequest > &req)
std::vector< char > LoadVfsFile (const libcomp::String &path)
std::shared_ptr< objects::LoginScriptRequest > ParsePost (CivetServer *pServer, struct mg_connection *pConnection)
Private Attributes
AccountManager * mAccountManager
std::shared_ptr< objects::LobbyConfig > mConfig
std::shared_ptr< libcomp::Database > mDatabase
ttvfs::Root mVfs
Static Private Attributes
static thread_local LoginHandlerThread mThreadHandler
Detailed Description
Definition at line 57 of file LoginWebHandler.h.
Constructor & Destructor Documentation
LoginHandler()
LoginHandler::LoginHandler (const std::shared_ptr< libcomp::Database > & database)
Definition at line 49 of file LoginWebHandler.cpp.
References LOG_CRITICAL, and mVfs.
~LoginHandler()
LoginHandler::~LoginHandler () virtual
Definition at line 63 of file LoginWebHandler.cpp.
Member Function Documentation
handleGet()
bool LoginHandler::handleGet (CivetServer * pServer, struct mg_connection * pConnection) virtual
Definition at line 79 of file LoginWebHandler.cpp.
References HandlePage().
HandlePage()
bool LoginHandler::HandlePage (CivetServer * pServer, struct mg_connection * pConnection, const std::shared_ptr< objects::LoginScriptRequest > & req) private
Load the Squirrel handler script once per thread.
Definition at line 154 of file LoginWebHandler.cpp.
References libcomp::String::C(), libcomp::String::Contains(), lobby::LoginHandlerThread::DidInit(), ErrorCodeString(), lobby::LoginHandlerThread::Init(), libcomp::String::IsEmpty(), libcomp::String::Left(), LoadVfsFile(), LOG_DEBUG, LOG_ERROR, mAccountManager, mConfig, libcomp::String::Mid(), mThreadHandler, lobby::LoginHandlerThread::ProcessLoginReply(), lobby::LoginHandlerThread::ProcessLoginRequest(), libcomp::String::Replace(), libcomp::String::Right(), libcomp::String::Size(), to_underlying(), and lobby::AccountManager::WebAuthLogin().
Referenced by handleGet(), and handlePost().
handlePost()
bool LoginHandler::handlePost (CivetServer * pServer, struct mg_connection * pConnection) virtual
Definition at line 87 of file LoginWebHandler.cpp.
References HandlePage(), and ParsePost().
LoadVfsFile()
std::vector< char > LoginHandler::LoadVfsFile (const libcomp::String & path) private
Definition at line 378 of file LoginWebHandler.cpp.
References libcomp::String::C(), LOG_ERROR, and mVfs.
Referenced by HandlePage().
ParsePost()
std::shared_ptr< objects::LoginScriptRequest > LoginHandler::ParsePost (CivetServer * pServer, struct mg_connection * pConnection) private
Definition at line 100 of file LoginWebHandler.cpp.
References mConfig, and libcomp::String::Split().
Referenced by handlePost().
SetAccountManager()
void LoginHandler::SetAccountManager (AccountManager * pManager)
Definition at line 414 of file LoginWebHandler.cpp.
References mAccountManager.
Referenced by main().
SetConfig()
void LoginHandler::SetConfig (const std::shared_ptr< objects::LobbyConfig > & config)
Definition at line 67 of file LoginWebHandler.cpp.
References lobby::config(), mConfig, and mVfs.
Member Data Documentation
mAccountManager
AccountManager* lobby::LoginHandler::mAccountManager private
Definition at line 87 of file LoginWebHandler.h.
Referenced by HandlePage(), and SetAccountManager().
mConfig
std::shared_ptr<objects::LobbyConfig> lobby::LoginHandler::mConfig private
Definition at line 85 of file LoginWebHandler.h.
Referenced by HandlePage(), ParsePost(), and SetConfig().
mDatabase
std::shared_ptr<libcomp::Database> lobby::LoginHandler::mDatabase private
Definition at line 84 of file LoginWebHandler.h.
mThreadHandler
thread_local LoginHandlerThread LoginHandler::mThreadHandler static private
Definition at line 89 of file LoginWebHandler.h.
Referenced by HandlePage().
mVfs
ttvfs::Root lobby::LoginHandler::mVfs private
Definition at line 82 of file LoginWebHandler.h.
Referenced by LoadVfsFile(), LoginHandler(), and SetConfig().
The documentation for this class was generated from the following files:
LoginWebHandler.h
LoginWebHandler.cpp