COMP_hack: lobby::LoginHandlerThread Class Reference
lobby::LoginHandlerThread Class Reference
#include <LoginHandlerThread.h>
Public Member Functions
LoginHandlerThread ()
~LoginHandlerThread ()
bool DidInit () const
bool Init (const libcomp::String &script)
bool ProcessLoginReply (const std::shared_ptr< objects::LoginScriptReply > &reply)
bool ProcessLoginRequest (const std::shared_ptr< objects::LoginScriptRequest > &req)
Private Attributes
bool mDidInit
libcomp::ScriptEngine mEngine
Detailed Description
Definition at line 49 of file LoginHandlerThread.h.
Constructor & Destructor Documentation
LoginHandlerThread()
LoginHandlerThread::LoginHandlerThread ()
Definition at line 144 of file LoginHandlerThread.cpp.
References mEngine, and libcomp::ScriptEngine::Using().
~LoginHandlerThread()
LoginHandlerThread::~LoginHandlerThread ()
Definition at line 150 of file LoginHandlerThread.cpp.
Member Function Documentation
DidInit()
bool LoginHandlerThread::DidInit () const
Definition at line 154 of file LoginHandlerThread.cpp.
References mDidInit.
Referenced by lobby::LoginHandler::HandlePage().
Init()
bool LoginHandlerThread::Init (const libcomp::String & script)
Definition at line 159 of file LoginHandlerThread.cpp.
References libcomp::ScriptEngine::Eval(), mDidInit, and mEngine.
Referenced by lobby::LoginHandler::HandlePage().
ProcessLoginReply()
bool LoginHandlerThread::ProcessLoginReply (const std::shared_ptr< objects::LoginScriptReply > & reply)
Definition at line 190 of file LoginHandlerThread.cpp.
References libcomp::ScriptEngine::GetVM(), LOG_ERROR, and mEngine.
Referenced by lobby::LoginHandler::HandlePage().
ProcessLoginRequest()
bool LoginHandlerThread::ProcessLoginRequest (const std::shared_ptr< objects::LoginScriptRequest > & req)
Definition at line 171 of file LoginHandlerThread.cpp.
References libcomp::ScriptEngine::GetVM(), LOG_ERROR, mEngine, and to_underlying().
Referenced by lobby::LoginHandler::HandlePage().
Member Data Documentation
mDidInit
bool lobby::LoginHandlerThread::mDidInit private
Definition at line 64 of file LoginHandlerThread.h.
Referenced by DidInit(), and Init().
mEngine
libcomp::ScriptEngine lobby::LoginHandlerThread::mEngine private
Definition at line 66 of file LoginHandlerThread.h.
Referenced by Init(), LoginHandlerThread(), ProcessLoginReply(), and ProcessLoginRequest().
The documentation for this class was generated from the following files:
LoginHandlerThread.h
LoginHandlerThread.cpp