COMP_hack: AccountLogin.cpp File Reference
AccountLogin.cpp File Reference
Parser to handle retrieving a channel for the client to log into.
#include "Packets.h"
#include <Log.h>
#include <ManagerPacket.h>
#include <Packet.h>
#include <PacketCodes.h>
#include <ReadOnlyPacket.h>
#include <cmath>
#include <Account.h>
#include <AccountLogin.h>
#include <Character.h>
#include <CharacterLogin.h>
#include <Clan.h>
#include <ClanMember.h>
#include <EntityStats.h>
#include "AccountManager.h"
#include "CharacterManager.h"
#include "WorldConfig.h"
#include "WorldServer.h"
Functions
void ChannelLogin (std::shared_ptr< WorldServer > server, const std::shared_ptr< libcomp::InternalConnection > connection, uint32_t sesssionKey, const libcomp::String username)
void LobbyLogin (std::shared_ptr< WorldServer > server, const std::shared_ptr< libcomp::InternalConnection > connection, std::shared_ptr< objects::AccountLogin > login)
Detailed Description
Parser to handle retrieving a channel for the client to log into.
Author
HACKfrost
This file is part of the World Server (world).
Copyright (C) 2012-2018 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file AccountLogin.cpp.
Function Documentation
void ChannelLogin (std::shared_ptr< WorldServer > server, const std::shared_ptr< libcomp::InternalConnection > connection, uint32_t sesssionKey, const libcomp::String username)
Definition at line 202 of file AccountLogin.cpp.
References libcomp::Convert::ENCODING_UTF8, libcomp::ManagerPacket::GetServer(), libcomp::String::Length(), LobbyLogin(), LOG_ERROR, libcomp::ReadOnlyPacket::ReadString16Little(), libcomp::ReadOnlyPacket::ReadU32(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteString16Little().
void LobbyLogin (std::shared_ptr< WorldServer > server, const std::shared_ptr< libcomp::InternalConnection > connection, std::shared_ptr< objects::AccountLogin > login)
Definition at line 56 of file AccountLogin.cpp.
References libcomp::PersistentObject::LoadObjectByUUID(), LOG_DEBUG, LOG_ERROR, libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS8().
Referenced by ChannelLogin().