COMP_hack: world::WorldServer Class Reference
world::WorldServer Class Reference
#include <WorldServer.h>
Public Types
typedef std::unordered_map< std::string, std::list< std::shared_ptr< libcomp::PersistentObject > > > PersistentObjectMap
Public Member Functions
WorldServer (const char *szProgram, std::shared_ptr< objects::ServerConfig > config, std::shared_ptr< libcomp::ServerCommandLineParser > commandLine)
Create a new world server.
virtual ~WorldServer ()
Clean up the server.
virtual void Cleanup ()
virtual void FinishInitialize ()
Do any initialize that should happen after the server is listening and fully started.
AccountManager * GetAccountManager ()
Get the account manager for the server.
std::shared_ptr< objects::RegisteredChannel > GetChannel (const std::shared_ptr< libcomp::InternalConnection > &connection) const
Get the RegisteredChannel of a channel currently connected to by its connection pointer.
std::shared_ptr< libcomp::InternalConnection > GetChannelConnectionByID (int8_t channelID) const
Get channel connection associated to the specified ID.
std::map< std::shared_ptr< libcomp::InternalConnection >, std::shared_ptr< objects::RegisteredChannel > > GetChannels () const
Get all channels by connection.
CharacterManager * GetCharacterManager () const
Get the character manager for the server.
std::shared_ptr< objects::ServerConfig > GetConfig () const
std::shared_ptr< Database > GetDatabase (const EnumMap< objects::ServerConfig::DatabaseType_t, std::shared_ptr< objects::DatabaseConfig >> &configMap, bool performSetup, DataStore *pDataStore=nullptr, const std::string &migrationDirectory=std::string())
DataStore * GetDataStore ()
const std::shared_ptr< libcomp::InternalConnection > GetLobbyConnection () const
Get a pointer to the lobby connection.
std::shared_ptr< libcomp::Database > GetLobbyDatabase () const
Get the lobby database.
uint8_t GetNextChannelID () const
Get the next channel ID to use for connecting channels.
const std::shared_ptr< objects::RegisteredWorld > GetRegisteredWorld () const
Get the RegisteredWorld.
virtual std::list< libcomp::Message::MessageType > GetSupportedTypes () const
gsl::not_null< TimerManager *> GetTimerManager ()
std::shared_ptr< libcomp::Database > GetWorldDatabase () const
Get the world database.
WorldSyncManager * GetWorldSyncManager () const
Get a pointer to the data sync manager.
virtual bool Initialize ()
Initialize the database connection and do anything else that can fail to execute that needs to be handled outside of a constructor.
virtual bool ProcessMessage (const libcomp::Message::Message *pMessage)
bool QueueWork (Function &&f, Args &&... args) const
void RegisterChannel (const std::shared_ptr< objects::RegisteredChannel > &channel, const std::shared_ptr< libcomp::InternalConnection > &connection)
Set the RegisteredChannel of a channel currently being connected to.
bool RegisterServer ()
Register the world with the lobby database.
bool RemoveChannel (const std::shared_ptr< libcomp::InternalConnection > &connection)
Remove the RegisteredChannel for a connection that is no longer being used.
void RemoveConnection (std::shared_ptr< TcpConnection > &connection)
virtual void ServerReady ()
void SetLobbyDatabase (const std::shared_ptr< libcomp::Database > &database)
Set the lobby database.
virtual void Shutdown ()
virtual int Start (bool delayReady=false)
Static Public Member Functions
static DH * CopyDiffieHellman (const DH *pDiffieHellman)
static DH * GenerateDiffieHellman ()
static std::string GetConfigPath ()
static std::shared_ptr< Database > GetDatabase (objects::ServerConfig::DatabaseType_t dbType, const EnumMap< objects::ServerConfig::DatabaseType_t, std::shared_ptr< objects::DatabaseConfig >> &configMap)
static std::string GetDefaultConfigPath ()
static uint32_t GetRelayPacket (libcomp::Packet &p, const std::list< int32_t > &targetCIDs={}, int32_t sourceCID=0)
Build the data-less relay packet from and targetting the supplied world CIDs.
static void GetRelayPacket (libcomp::Packet &p, int32_t targetCID, int32_t sourceCID=0)
Build the data-less relay packet from and targetting the supplied world CIDs.
static DH * LoadDiffieHellman (const std::vector< char > &data)
static DH * LoadDiffieHellman (const String &prime)
static DH * LoadDiffieHellman (const void *pData, size_t dataSize)
static bool ReadConfig (std::shared_ptr< objects::ServerConfig > config, tinyxml2::XMLDocument &doc)
static bool ReadConfig (std::shared_ptr< objects::ServerConfig > config, libcomp::String filePath)
static std::vector< char > SaveDiffieHellman (const DH *pDiffieHellman)
static void SetConfigPath (const std::string &path)
Protected Member Functions
void AcceptHandler (asio::error_code errorCode, asio::ip::tcp::socket &socket)
bool AssignMessageQueue (const std::shared_ptr< libcomp::EncryptedConnection > &connection)
virtual std::shared_ptr< libcomp::TcpConnection > CreateConnection (asio::ip::tcp::socket &socket)
Create a connection to a newly active socket.
void CreateWorkers ()
const DH * GetDiffieHellman () const
virtual std::shared_ptr< libcomp::Worker > GetNextConnectionWorker ()
bool InsertDataFromFile (const libcomp::String &filePath, const std::shared_ptr< Database > &db, const std::set< std::string > &specificTypes={})
bool LoadDataFromFile (const libcomp::String &filePath, PersistentObjectMap &records, bool registerRecords, const std::set< std::string > &specificTypes={})
virtual int Run ()
void SetDiffieHellman (DH *pDiffieHellman)
Protected Attributes
AccountManager * mAccountManager
Account manager for the server.
CharacterManager * mCharacterManager
Character manager for the server.
std::shared_ptr< ServerCommandLineParser > mCommandLine
std::shared_ptr< objects::ServerConfig > mConfig
std::list< std::shared_ptr< TcpConnection > > mConnections
std::mutex mConnectionsLock
std::shared_ptr< libcomp::Database > mDatabase
A shared pointer to the world database used by the server.
libcomp::DataStore mDataStore
std::shared_ptr< libcomp::Database > mLobbyDatabase
A shared pointer to the world database used by the server.
std::mutex mLock
Server lock for shared resources.
libcomp::Worker mMainWorker
std::shared_ptr< ManagerConnection > mManagerConnection
Pointer to the manager in charge of connection messages.
libcomp::Worker mQueueWorker
std::map< std::shared_ptr< libcomp::InternalConnection >, std::shared_ptr< objects::RegisteredChannel > > mRegisteredChannels
Pointer to the RegisteredChannels by their connections.
std::shared_ptr< objects::RegisteredWorld > mRegisteredWorld
Pointer to the RegisteredWorld.
asio::io_service mService
WorldSyncManager * mSyncManager
Data sync manager for the server.
libcomp::TimerManager mTimerManager
std::list< std::shared_ptr< libcomp::Worker > > mWorkers
Static Protected Attributes
static std::string sConfigPath
Detailed Description
Definition at line 50 of file WorldServer.h.
Constructor & Destructor Documentation
WorldServer()
WorldServer::WorldServer (const char * szProgram, std::shared_ptr< objects::ServerConfig > config, std::shared_ptr< libcomp::ServerCommandLineParser > commandLine)
Create a new world server.
Parameters
szProgram First command line argument for the application.
config Pointer to a casted WorldConfig that will contain properties every server has in addition to world specific ones.
Definition at line 50 of file WorldServer.cpp.
~WorldServer()
WorldServer::~WorldServer () virtual
Clean up the server.
Definition at line 202 of file WorldServer.cpp.
References mAccountManager, mCharacterManager, and mSyncManager.
Member Function Documentation
CreateConnection()
std::shared_ptr< libcomp::TcpConnection > WorldServer::CreateConnection (asio::ip::tcp::socket & socket) protected virtual
Create a connection to a newly active socket.
Parameters
socket A new socket connection.
Returns
Pointer to the newly created connection
Todo:
: ensure that channels can start connecting
Todo:
: send a "connection refused" error message to the client
Reimplemented from libcomp::BaseServer.
Definition at line 437 of file WorldServer.cpp.
References libcomp::BaseServer::AssignMessageQueue(), libcomp::BaseServer::CopyDiffieHellman(), libcomp::BaseServer::GetDiffieHellman(), libcomp::Worker::GetMessageQueue(), libcomp::BaseServer::mMainWorker, and mManagerConnection.
FinishInitialize()
void WorldServer::FinishInitialize () virtual
Do any initialize that should happen after the server is listening and fully started.
Reimplemented from libcomp::BaseServer.
Definition at line 92 of file WorldServer.cpp.
References libcomp::Worker::AddManager(), LOG_CRITICAL, libcomp::BaseServer::mConfig, libcomp::BaseServer::mMainWorker, mManagerConnection, libcomp::LobbyConnection::MODE_WORLD_UP, libcomp::BaseServer::mWorkers, libcomp::TcpConnection::STATUS_CONNECTED, and to_underlying().
GetAccountManager()
AccountManager * WorldServer::GetAccountManager ()
Get the account manager for the server.
Returns
Account manager for the server.
Definition at line 395 of file WorldServer.cpp.
References mAccountManager.
GetChannel()
std::shared_ptr< objects::RegisteredChannel > WorldServer::GetChannel (const std::shared_ptr< libcomp::InternalConnection > & connection) const
Get the RegisteredChannel of a channel currently connected to by its connection pointer.
Parameters
connection Pointer to the channel's connection.
Returns
Pointer to the RegisteredChannel
Definition at line 214 of file WorldServer.cpp.
References mRegisteredChannels.
Referenced by world::ManagerConnection::RemoveConnection().
GetChannelConnectionByID()
std::shared_ptr< libcomp::InternalConnection > WorldServer::GetChannelConnectionByID (int8_t channelID) const
Get channel connection associated to the specified ID.
Parameters
channelID ID of the channel to retrieve
Returns
Pointer to the channel connnection
Definition at line 226 of file WorldServer.cpp.
References mRegisteredChannels.
GetChannels()
std::map< std::shared_ptr< libcomp::InternalConnection >, std::shared_ptr< objects::RegisteredChannel > > WorldServer::GetChannels () const
Get all channels by connection.
Returns
Map of channels by connection
Definition at line 241 of file WorldServer.cpp.
References mRegisteredChannels.
GetCharacterManager()
CharacterManager * WorldServer::GetCharacterManager () const
Get the character manager for the server.
Returns
Character manager for the server.
Definition at line 400 of file WorldServer.cpp.
References mCharacterManager.
GetLobbyConnection()
const std::shared_ptr< libcomp::InternalConnection > WorldServer::GetLobbyConnection () const
Get a pointer to the lobby connection.
Returns
Pointer to the lobby connection
Definition at line 267 of file WorldServer.cpp.
References mManagerConnection.
GetLobbyDatabase()
std::shared_ptr< libcomp::Database > WorldServer::GetLobbyDatabase () const
Get the lobby database.
Returns
Pointer to the lobby's database
Definition at line 320 of file WorldServer.cpp.
References mLobbyDatabase.
GetNextChannelID()
uint8_t WorldServer::GetNextChannelID () const
Get the next channel ID to use for connecting channels.
Returns
Next channel ID, starting at 0
Definition at line 246 of file WorldServer.cpp.
References mRegisteredChannels.
GetRegisteredWorld()
const std::shared_ptr< objects::RegisteredWorld > WorldServer::GetRegisteredWorld () const
Get the RegisteredWorld.
Returns
Pointer to the RegisteredWorld
Definition at line 209 of file WorldServer.cpp.
References mRegisteredWorld.
GetRelayPacket() [1/2]
uint32_t WorldServer::GetRelayPacket (libcomp::Packet & p, const std::list< int32_t > & targetCIDs = {}, int32_t sourceCID = 0) static
Build the data-less relay packet from and targetting the supplied world CIDs.
Parameters
p Reference param containing the packet to write to
targetCIDs Optional list of target CIDs. If this is not supplied it must be inserted elsewhere.
sourceCID World CID of the source character, 0 means it came from the world
Returns
Position of the target CIDs section of the packet. This is useful for when the target CIDs are added later.
Definition at line 410 of file WorldServer.cpp.
References libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU8().
Referenced by world::CharacterManager::ClanDisband(), ClanInvite(), world::CharacterManager::ClanJoin(), world::CharacterManager::ClanKick(), world::CharacterManager::ClanLeave(), GetRelayPacket(), PartyCancel(), world::CharacterManager::PartyDisband(), PartyDropRule(), PartyInvite(), world::CharacterManager::PartyJoin(), world::CharacterManager::PartyLeaderUpdate(), world::CharacterManager::PartyLeave(), world::CharacterManager::PartyRecruit(), PartyRecruitJoin(), world::CharacterManager::SendClanDetails(), world::CharacterManager::SendClanMemberInfo(), world::CharacterManager::SendPartyMember(), TeamCancel(), world::CharacterManager::TeamDisband(), TeamForm(), TeamInvite(), world::CharacterManager::TeamJoin(), world::CharacterManager::TeamKick(), world::CharacterManager::TeamLeaderUpdate(), and world::CharacterManager::TeamLeave().
GetRelayPacket() [2/2]
void WorldServer::GetRelayPacket (libcomp::Packet & p, int32_t targetCID, int32_t sourceCID = 0) static
Build the data-less relay packet from and targetting the supplied world CIDs.
Parameters
p Reference param containing the packet to write to
targetCID World CID of the target to send the packet to
sourceCID World CID of the source character, 0 means it came from the world
Definition at line 430 of file WorldServer.cpp.
References GetRelayPacket().
GetWorldDatabase()
std::shared_ptr< libcomp::Database > WorldServer::GetWorldDatabase () const
Get the world database.
Returns
Pointer to the world's database
Definition at line 315 of file WorldServer.cpp.
References mDatabase.
GetWorldSyncManager()
WorldSyncManager * WorldServer::GetWorldSyncManager () const
Get a pointer to the data sync manager.
Returns
Pointer to the WorldSyncManager
Definition at line 405 of file WorldServer.cpp.
References mSyncManager.
Initialize()
bool WorldServer::Initialize () virtual
Initialize the database connection and do anything else that can fail to execute that needs to be handled outside of a constructor.
This calls the BaseServer version as well to perform shared init steps.
Parameters
self Pointer to this server to be used as a reference in packet handling code.
Returns
true on success, false on failure
Reimplemented from libcomp::BaseServer.
Definition at line 57 of file WorldServer.cpp.
References libcomp::BaseServer::GetDatabase(), libcomp::BaseServer::GetDataStore(), mAccountManager, mCharacterManager, libcomp::BaseServer::mConfig, mDatabase, and mSyncManager.
RegisterChannel()
void WorldServer::RegisterChannel (const std::shared_ptr< objects::RegisteredChannel > & channel, const std::shared_ptr< libcomp::InternalConnection > & connection)
Set the RegisteredChannel of a channel currently being connected to.
Parameters
channel Pointer to the RegisteredChannel.
connection Pointer to the channel's connection.
Definition at line 272 of file WorldServer.cpp.
References mLock, mRegisteredChannels, mSyncManager, libcomp::DataSyncManager::RegisterConnection(), and world::WorldSyncManager::SyncExistingChannelRecords().
RegisterServer()
bool WorldServer::RegisterServer ()
Register the world with the lobby database.
Returns
true on success, false on failure
Definition at line 330 of file WorldServer.cpp.
References libcomp::String::Arg(), libcomp::PersistentObject::LoadAll(), LOG_CRITICAL, LOG_DEBUG, libcomp::BaseServer::mConfig, mDatabase, mLobbyDatabase, and mRegisteredWorld.
RemoveChannel()
bool WorldServer::RemoveChannel (const std::shared_ptr< libcomp::InternalConnection > & connection)
Remove the RegisteredChannel for a connection that is no longer being used.
Parameters
connection Pointer to the channel's connection.
Returns
true if the RegisteredChannel existed, false if it did not
Definition at line 301 of file WorldServer.cpp.
References mLock, and mRegisteredChannels.
SetLobbyDatabase()
void WorldServer::SetLobbyDatabase (const std::shared_ptr< libcomp::Database > & database)
Set the lobby database.
Parameters
database Pointer to the lobby's database
Definition at line 325 of file WorldServer.cpp.
References mLobbyDatabase.
Member Data Documentation
mAccountManager
AccountManager* world::WorldServer::mAccountManager protected
Account manager for the server.
Definition at line 235 of file WorldServer.h.
Referenced by GetAccountManager(), Initialize(), and ~WorldServer().
mCharacterManager
CharacterManager* world::WorldServer::mCharacterManager protected
Character manager for the server.
Definition at line 238 of file WorldServer.h.
Referenced by GetCharacterManager(), Initialize(), and ~WorldServer().
mDatabase
std::shared_ptr<libcomp::Database> world::WorldServer::mDatabase protected
A shared pointer to the world database used by the server.
Definition at line 219 of file WorldServer.h.
Referenced by GetWorldDatabase(), Initialize(), and RegisterServer().
mLobbyDatabase
std::shared_ptr<libcomp::Database> world::WorldServer::mLobbyDatabase protected
A shared pointer to the world database used by the server.
Definition at line 222 of file WorldServer.h.
Referenced by GetLobbyDatabase(), RegisterServer(), and SetLobbyDatabase().
mLock
std::mutex world::WorldServer::mLock protected
Server lock for shared resources.
Definition at line 244 of file WorldServer.h.
Referenced by RegisterChannel(), and RemoveChannel().
mManagerConnection
std::shared_ptr<ManagerConnection> world::WorldServer::mManagerConnection protected
Pointer to the manager in charge of connection messages.
Definition at line 232 of file WorldServer.h.
Referenced by CreateConnection(), FinishInitialize(), and GetLobbyConnection().
mRegisteredChannels
std::map<std::shared_ptr<libcomp::InternalConnection>, std::shared_ptr<objects::RegisteredChannel> > world::WorldServer::mRegisteredChannels protected
Pointer to the RegisteredChannels by their connections.
Definition at line 229 of file WorldServer.h.
Referenced by GetChannel(), GetChannelConnectionByID(), GetChannels(), GetNextChannelID(), RegisterChannel(), and RemoveChannel().
mRegisteredWorld
std::shared_ptr<objects::RegisteredWorld> world::WorldServer::mRegisteredWorld protected
Pointer to the RegisteredWorld.
Definition at line 225 of file WorldServer.h.
Referenced by GetRegisteredWorld(), and RegisterServer().
mSyncManager
WorldSyncManager* world::WorldServer::mSyncManager protected
Data sync manager for the server.
Definition at line 241 of file WorldServer.h.
Referenced by GetWorldSyncManager(), Initialize(), RegisterChannel(), and ~WorldServer().
The documentation for this class was generated from the following files:
WorldServer.h
WorldServer.cpp