COMP_hack: world::AccountManager Class Reference
world::AccountManager Class Reference
Manages logged in user accounts.
#include <AccountManager.h>
Public Member Functions
AccountManager (const std::weak_ptr< WorldServer > &server)
Create a new account manager.
bool ChannelLogin (std::shared_ptr< objects::AccountLogin > login)
Update the supplied login, set the login state to CHANNEL and the character status to ONLINE.
void CleanupAccountWorldData ()
Perform all clean up operations related to each AccountWorldData entry with CleanupRequired currently flagged.
bool DeleteCharacter (const std::shared_ptr< objects::Character > &character)
Delete a character requested from the lobby or otherwise marked for deletion by cleaning up all related character objects.
bool ExpireSession (const libcomp::String &username, uint32_t key)
Expire the user session and log out the account.
std::shared_ptr< objects::AccountLogin > GetUserLogin (const libcomp::String &username)
Get the current user login state independent of world.
bool IsLoggedIn (const libcomp::String &username, int8_t &channel)
Check if a user is logged in.
bool LobbyLogin (std::shared_ptr< objects::AccountLogin > login)
Register the supplied login with the world if it has not been already.
std::shared_ptr< objects::AccountLogin > LogoutUser (const libcomp::String &username, int8_t channel=-1)
Mark the user logged out of the given channel.
std::list< std::shared_ptr< objects::AccountLogin > > LogoutUsersOnChannel (int8_t channel)
Log out all users on a given channel.
bool PopChannelSwitch (const libcomp::String &username, int8_t &channel)
"Pop" any existing channel switch signifier from the manager for the specified account and return the channel ID value.
bool SwitchChannel (std::shared_ptr< objects::AccountLogin > login, int8_t channelID)
Transition the login from CHANNEL to CHANNEL_TO_CHANNEL and sechedule a timeout.
Private Member Functions
void Cleanup (const std::shared_ptr< objects::AccountLogin > &login)
Utility function to free up references to an AccountLogin loaded by the world.
template<class T >
void Cleanup (const std::shared_ptr< T > &obj)
Utility function to free up references to a PersistentObject loaded by the world.
void PushChannelSwitch (const libcomp::String &username, int8_t channel)
"Push" a channel switch signifier to the manager for the specified account.
void UpdateSessionKey (std::shared_ptr< objects::AccountLogin > login)
Update the session key of the supplied login.
Private Attributes
std::unordered_map< libcomp::String, std::shared_ptr< objects::AccountLogin > > mAccountMap
Map of account login information by username.
std::unordered_map< libcomp::String, int8_t > mChannelSwitches
Map of account usernames associated to accounts set to switch channel upon next disconnect from a channel.
std::mutex mLock
Server lock for shared resources.
std::weak_ptr< WorldServer > mServer
Pointer back to theworld server this belongs to.
Detailed Description
Manages logged in user accounts.
Definition at line 53 of file AccountManager.h.
Constructor & Destructor Documentation
AccountManager::AccountManager (const std::weak_ptr< WorldServer > & server)
Create a new account manager.
Parameters
server Pointer back to the world server this belongs to
Definition at line 62 of file AccountManager.cpp.
Member Function Documentation
bool AccountManager::ChannelLogin (std::shared_ptr< objects::AccountLogin > login)
Update the supplied login, set the login state to CHANNEL and the character status to ONLINE.
Also perform any "on login" actions.
Parameters
login Login information associated to the account.
Returns
true if the account was successfully updated; false if an error occurred.
Definition at line 110 of file AccountManager.cpp.
References LOG_ERROR, mLock, and mServer.
void AccountManager::Cleanup (const std::shared_ptr< objects::AccountLogin > & login) private
Utility function to free up references to an AccountLogin loaded by the world.
Parameters
login Pointer to the AcccountLogin to clean up
Definition at line 690 of file AccountManager.cpp.
Referenced by DeleteCharacter(), LogoutUser(), and LogoutUsersOnChannel().
template<class T > void world::AccountManager::Cleanup (const std::shared_ptr< T > & obj) inline private
Utility function to free up references to a PersistentObject loaded by the world.
Parameters
login Pointer to the PersistentObject to clean up
Definition at line 197 of file AccountManager.h.
References libcomp::ObjectReference< class >::Unload().
void AccountManager::CleanupAccountWorldData ()
Perform all clean up operations related to each AccountWorldData entry with CleanupRequired currently flagged.
Definition at line 393 of file AccountManager.cpp.
References DeleteCharacter(), libcomp::PersistentObject::LoadObjectByUUID(), LOG_DEBUG, LOG_ERROR, MAX_CHARACTER, and mServer.
bool AccountManager::DeleteCharacter (const std::shared_ptr< objects::Character > & character)
Delete a character requested from the lobby or otherwise marked for deletion by cleaning up all related character objects.
If the character is somehow still logged in, a disconnect request will be sent and the character will be marked for deletion for the next time this process runs.
Parameters
character Pointer to the character to delete
Returns
true if the delete was successful, false if the delete failed
Definition at line 464 of file AccountManager.cpp.
References Cleanup(), libcomp::DatabaseChangeSet::Create(), LOG_DEBUG, LOG_ERROR, LOG_WARNING, and mServer.
Referenced by CleanupAccountWorldData().
bool AccountManager::ExpireSession (const libcomp::String & username, uint32_t key)
Expire the user session and log out the account.
If the session key is not matched or the account has completed its channel login (CHANNEL state) this is ignored.
Parameters
username Username for account to check.
key Session key that has expired.
Returns
true if the session was expired, false if it was not
Definition at line 292 of file AccountManager.cpp.
References LOG_DEBUG, LogoutUser(), mAccountMap, mLock, mServer, and libcomp::String::ToLower().
std::shared_ptr< objects::AccountLogin > AccountManager::GetUserLogin (const libcomp::String & username)
Get the current user login state independent of world.
Parameters
username Username for the account to login.
Returns
Pointer to the login state; null if it does not exist.
Definition at line 232 of file AccountManager.cpp.
References mAccountMap, mLock, and libcomp::String::ToLower().
bool AccountManager::IsLoggedIn (const libcomp::String & username, int8_t & channel)
Check if a user is logged in.
Parameters
username Username for the account to check.
channel Channel the user is logged into or -1 if they are in the lobby server.
Returns
true if the user is logged in; false otherwise.
Definition at line 67 of file AccountManager.cpp.
References mAccountMap, mLock, and libcomp::String::ToLower().
bool AccountManager::LobbyLogin (std::shared_ptr< objects::AccountLogin > login)
Register the supplied login with the world if it has not been already.
Parameters
login Login information associated to the account.
Returns
true if the user was logged in; false if the user is already logged in.
Definition at line 87 of file AccountManager.cpp.
References mAccountMap, mLock, RNG, and libcomp::String::ToLower().
std::shared_ptr< objects::AccountLogin > AccountManager::LogoutUser (const libcomp::String & username, int8_t channel = -1)
Mark the user logged out of the given channel.
Parameters
username Username for the account to log out.
channel Channel the user is logged into or -1 if they are in the lobby server.
Returns
Pointer to the AccountLogin representing the logged out user, nullptr if they were not registered.
Definition at line 242 of file AccountManager.cpp.
References Cleanup(), LOG_DEBUG, mAccountMap, mLock, mServer, libcomp::String::ToLower(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteString16Little().
Referenced by ExpireSession().
std::list< std::shared_ptr< objects::AccountLogin > > AccountManager::LogoutUsersOnChannel (int8_t channel)
Log out all users on a given channel.
This should only be called when a channel disconnects.
Parameters
channel Channel to log out all users from.
Returns
List of AccountLogins representing the logged out users.
Definition at line 336 of file AccountManager.cpp.
References Cleanup(), mAccountMap, and mLock.
bool AccountManager::PopChannelSwitch (const libcomp::String & username, int8_t & channel)
"Pop" any existing channel switch signifier from the manager for the specified account and return the channel ID value.
Parameters
username Username of the account set to switch channels
channel Output parameter to store the channel being switched to. If no channel switch is stored, this will not be set.
Returns
true if a channel switch is stored, false if it is not
Definition at line 377 of file AccountManager.cpp.
References mChannelSwitches, mLock, and libcomp::String::ToLower().
void AccountManager::PushChannelSwitch (const libcomp::String & username, int8_t channel) private
"Push" a channel switch signifier to the manager for the specified account.
The next logout request will pop this value and await a reconnect to the specified channel rather than log the account out.
Parameters
username Username of the account that will switch channels
channel Channel being switched to
Definition at line 371 of file AccountManager.cpp.
References mChannelSwitches, and libcomp::String::ToLower().
Referenced by SwitchChannel().
bool AccountManager::SwitchChannel (std::shared_ptr< objects::AccountLogin > login, int8_t channelID)
Transition the login from CHANNEL to CHANNEL_TO_CHANNEL and sechedule a timeout.
Parameters
login Login information associated to the account.
channelID New channel ID, the connection will be moved to
Returns
true if the update succeeded, false if it did not
Definition at line 187 of file AccountManager.cpp.
References LOG_ERROR, mLock, mServer, PushChannelSwitch(), and UpdateSessionKey().
void AccountManager::UpdateSessionKey (std::shared_ptr< objects::AccountLogin > login) private
Update the session key of the supplied login.
The lobby must be notified of this update or the login information will become out of sync.
Parameters
login Pointer to the account login to update
Definition at line 366 of file AccountManager.cpp.
References RNG.
Referenced by SwitchChannel().
Member Data Documentation
std::unordered_map<libcomp::String, std::shared_ptr<objects::AccountLogin> > world::AccountManager::mAccountMap private
Map of account login information by username.
Definition at line 210 of file AccountManager.h.
Referenced by ExpireSession(), GetUserLogin(), IsLoggedIn(), LobbyLogin(), LogoutUser(), and LogoutUsersOnChannel().
std::unordered_map<libcomp::String, int8_t> world::AccountManager::mChannelSwitches private
Map of account usernames associated to accounts set to switch channel upon next disconnect from a channel.
Definition at line 214 of file AccountManager.h.
Referenced by PopChannelSwitch(), and PushChannelSwitch().
std::mutex world::AccountManager::mLock private
Server lock for shared resources.
Definition at line 217 of file AccountManager.h.
Referenced by ChannelLogin(), ExpireSession(), GetUserLogin(), IsLoggedIn(), LobbyLogin(), LogoutUser(), LogoutUsersOnChannel(), PopChannelSwitch(), and SwitchChannel().
std::weak_ptr<WorldServer> world::AccountManager::mServer private
Pointer back to theworld server this belongs to.
Definition at line 206 of file AccountManager.h.
Referenced by ChannelLogin(), CleanupAccountWorldData(), DeleteCharacter(), ExpireSession(), LogoutUser(), and SwitchChannel().
The documentation for this class was generated from the following files:
AccountManager.h
AccountManager.cpp