COMP_hack: FriendsUpdate.cpp File Reference
FriendsUpdate.cpp File Reference
Parser to handle all friend list focused actions between the world and the channels.
#include "Packets.h"
#include <Log.h>
#include <ManagerPacket.h>
#include <Packet.h>
#include <PacketCodes.h>
#include <Account.h>
#include <AccountLogin.h>
#include <Character.h>
#include <CharacterLogin.h>
#include <FriendSettings.h>
#include "CharacterManager.h"
#include "WorldServer.h"
Functions
void FriendList (std::shared_ptr< WorldServer > server, std::shared_ptr< libcomp::TcpConnection > connection, std::shared_ptr< objects::CharacterLogin > cLogin)
void FriendRemoved (std::shared_ptr< WorldServer > server, std::shared_ptr< libcomp::TcpConnection > sourceConnection, std::shared_ptr< objects::CharacterLogin > cLogin, int32_t targetCID)
void FriendRequest (std::shared_ptr< WorldServer > server, std::shared_ptr< libcomp::TcpConnection > sourceConnection, std::shared_ptr< objects::CharacterLogin > cLogin, const libcomp::String sourceName, const libcomp::String targetName)
void FriendRequestAccepted (std::shared_ptr< WorldServer > server, std::shared_ptr< libcomp::TcpConnection > sourceConnection, std::shared_ptr< objects::CharacterLogin > cLogin, const libcomp::String sourceName, const libcomp::String targetName)
void FriendRequestCancel (const std::shared_ptr< libcomp::TcpConnection > &connection, const libcomp::String otherName, std::shared_ptr< objects::CharacterLogin > cLogin)
void FriendRequestCancelled (std::shared_ptr< WorldServer > server, std::shared_ptr< libcomp::TcpConnection > sourceConnection, std::shared_ptr< objects::CharacterLogin > cLogin, const libcomp::String sourceName, const libcomp::String targetName)
Detailed Description
Parser to handle all friend list focused actions between the world and the channels.
Author
HACKfrost
This file is part of the World Server (world).
Copyright (C) 2012-2018 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file FriendsUpdate.cpp.
Function Documentation
FriendList()
void FriendList (std::shared_ptr< WorldServer > server, std::shared_ptr< libcomp::TcpConnection > connection, std::shared_ptr< objects::CharacterLogin > cLogin)
Definition at line 63 of file FriendsUpdate.cpp.
References RELATED_FRIENDS, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU8().
FriendRemoved()
void FriendRemoved (std::shared_ptr< WorldServer > server, std::shared_ptr< libcomp::TcpConnection > sourceConnection, std::shared_ptr< objects::CharacterLogin > cLogin, int32_t targetCID)
Definition at line 257 of file FriendsUpdate.cpp.
References libcomp::Packet::Clear(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
FriendRequest()
void FriendRequest (std::shared_ptr< WorldServer > server, std::shared_ptr< libcomp::TcpConnection > sourceConnection, std::shared_ptr< objects::CharacterLogin > cLogin, const libcomp::String sourceName, const libcomp::String targetName)
Definition at line 90 of file FriendsUpdate.cpp.
References FriendRequestCancel(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU8().
FriendRequestAccepted()
void FriendRequestAccepted (std::shared_ptr< WorldServer > server, std::shared_ptr< libcomp::TcpConnection > sourceConnection, std::shared_ptr< objects::CharacterLogin > cLogin, const libcomp::String sourceName, const libcomp::String targetName)
Definition at line 138 of file FriendsUpdate.cpp.
References libcomp::Packet::Clear(), FriendRequestCancel(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU8().
FriendRequestCancel()
void FriendRequestCancel (const std::shared_ptr< libcomp::TcpConnection > & connection, const libcomp::String otherName, std::shared_ptr< objects::CharacterLogin > cLogin)
Definition at line 49 of file FriendsUpdate.cpp.
References libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU8().
Referenced by FriendRequest(), FriendRequestAccepted(), and FriendRequestCancelled().
FriendRequestCancelled()
void FriendRequestCancelled (std::shared_ptr< WorldServer > server, std::shared_ptr< libcomp::TcpConnection > sourceConnection, std::shared_ptr< objects::CharacterLogin > cLogin, const libcomp::String sourceName, const libcomp::String targetName)
Definition at line 228 of file FriendsUpdate.cpp.
References FriendRequestCancel().