COMP_hack: world Namespace Reference
world Namespace Reference
Namespaces
Parsers
Classes
class AccountManager
Manages logged in user accounts.
class CharacterManager
Manages world level character actions.
class ManagerConnection
Class to handle messages pertaining to connecting to the lobby or channels.
class WorldServer
class WorldSyncManager
World specific implementation of the DataSyncManager in charge of performing server side update operations.
Functions
template<>
void WorldSyncManager::Expire< objects::SearchEntry > (int32_t entryID, uint32_t expirationTime)
template<>
void WorldSyncManager::SyncComplete< objects::EventCounter > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
void WorldSyncManager::SyncComplete< objects::Match > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
void WorldSyncManager::SyncComplete< objects::MatchEntry > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
void WorldSyncManager::SyncComplete< objects::PentalphaEntry > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
void WorldSyncManager::SyncComplete< objects::PentalphaMatch > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
void WorldSyncManager::SyncComplete< objects::PvPMatch > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
void WorldSyncManager::SyncComplete< objects::UBResult > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
void WorldSyncManager::SyncComplete< objects::UBTournament > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
int8_t WorldSyncManager::Update< objects::Account > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t WorldSyncManager::Update< objects::Character > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t WorldSyncManager::Update< objects::CharacterLogin > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t WorldSyncManager::Update< objects::CharacterProgress > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t WorldSyncManager::Update< objects::InstanceAccess > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t WorldSyncManager::Update< objects::MatchEntry > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t WorldSyncManager::Update< objects::PentalphaMatch > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t WorldSyncManager::Update< objects::PvPMatch > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t WorldSyncManager::Update< objects::SearchEntry > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t WorldSyncManager::Update< objects::UBTournament > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
Function Documentation
WorldSyncManager::Expire< objects::SearchEntry >()
template<> void world::WorldSyncManager::Expire< objects::SearchEntry > (int32_t entryID, uint32_t expirationTime)
Definition at line 1000 of file WorldSyncManager.cpp.
WorldSyncManager::SyncComplete< objects::EventCounter >()
template<> void world::WorldSyncManager::SyncComplete< objects::EventCounter > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 606 of file WorldSyncManager.cpp.
References libcomp::DatabaseChangeSet::Create(), and libcomp::PersistentObject::New().
WorldSyncManager::SyncComplete< objects::Match >()
template<> void world::WorldSyncManager::SyncComplete< objects::Match > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 472 of file WorldSyncManager.cpp.
WorldSyncManager::SyncComplete< objects::MatchEntry >()
template<> void world::WorldSyncManager::SyncComplete< objects::MatchEntry > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 549 of file WorldSyncManager.cpp.
WorldSyncManager::SyncComplete< objects::PentalphaEntry >()
template<> void world::WorldSyncManager::SyncComplete< objects::PentalphaEntry > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 752 of file WorldSyncManager.cpp.
WorldSyncManager::SyncComplete< objects::PentalphaMatch >()
template<> void world::WorldSyncManager::SyncComplete< objects::PentalphaMatch > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 816 of file WorldSyncManager.cpp.
WorldSyncManager::SyncComplete< objects::PvPMatch >()
template<> void world::WorldSyncManager::SyncComplete< objects::PvPMatch > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 979 of file WorldSyncManager.cpp.
WorldSyncManager::SyncComplete< objects::UBResult >()
template<> void world::WorldSyncManager::SyncComplete< objects::UBResult > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 836 of file WorldSyncManager.cpp.
WorldSyncManager::SyncComplete< objects::UBTournament >()
template<> void world::WorldSyncManager::SyncComplete< objects::UBTournament > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 898 of file WorldSyncManager.cpp.
WorldSyncManager::Update< objects::Account >()
template<> int8_t world::WorldSyncManager::Update< objects::Account > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 277 of file WorldSyncManager.cpp.
WorldSyncManager::Update< objects::Character >()
template<> int8_t world::WorldSyncManager::Update< objects::Character > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 319 of file WorldSyncManager.cpp.
References LOG_ERROR.
WorldSyncManager::Update< objects::CharacterLogin >()
template<> int8_t world::WorldSyncManager::Update< objects::CharacterLogin > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 351 of file WorldSyncManager.cpp.
WorldSyncManager::Update< objects::CharacterProgress >()
template<> int8_t world::WorldSyncManager::Update< objects::CharacterProgress > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 365 of file WorldSyncManager.cpp.
References libcomp::PersistentObject::GetObjectByUUID().
WorldSyncManager::Update< objects::InstanceAccess >()
template<> int8_t world::WorldSyncManager::Update< objects::InstanceAccess > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 403 of file WorldSyncManager.cpp.
WorldSyncManager::Update< objects::MatchEntry >()
template<> int8_t world::WorldSyncManager::Update< objects::MatchEntry > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 513 of file WorldSyncManager.cpp.
WorldSyncManager::Update< objects::PentalphaMatch >()
template<> int8_t world::WorldSyncManager::Update< objects::PentalphaMatch > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 802 of file WorldSyncManager.cpp.
WorldSyncManager::Update< objects::PvPMatch >()
template<> int8_t world::WorldSyncManager::Update< objects::PvPMatch > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 939 of file WorldSyncManager.cpp.
WorldSyncManager::Update< objects::SearchEntry >()
template<> int8_t world::WorldSyncManager::Update< objects::SearchEntry > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 1024 of file WorldSyncManager.cpp.
References world::WorldSyncManager::Expire(), and LOG_WARNING.
WorldSyncManager::Update< objects::UBTournament >()
template<> int8_t world::WorldSyncManager::Update< objects::UBTournament > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 884 of file WorldSyncManager.cpp.