COMP_hack Logger: ChannelConnection Class Reference
ChannelConnection Class Reference
Proxy connection between the logger and the channel server.
#include <ChannelConnection.h>
Public Member Functions
ChannelConnection (LoggerServer *server, qintptr socketDescriptor, uint32_t clientID, QObject *parent=0)
Create a new channel connection.
virtual ~ChannelConnection ()
Delete the connection.
Protected Slots
void clientLost ()
This method is called when the client closes the connection.
void clientReady ()
This method is called when new data has arrived from the client.
void sendClientHello ()
This method is called when the connection to the channel server is opened.
void serverLost ()
This method is called when the channel server closes the connection.
void serverReady ()
This method is called when new data has arrived from the channel server.
Protected Member Functions
void decryptPacket (const BF_KEY *key, libcomp::Packet &p)
Decrypt a packet.
void encryptPacket (const BF_KEY *key, libcomp::Packet &p)
Encrypt a packet.
void exchangeKeys ()
Exchange encryption keys with the channel server.
void logMessage (const QString &msg)
Log a message to the console and GUI.
void logPacket (libcomp::Packet &p, uint8_t source)
Log a packet to the capture file and send it to the live capgrep.
bool packetHasServerSwitch (libcomp::Packet &p)
Determine if the packet has a server switch command.
void rewriteServerSwitchPacket (libcomp::Packet &p)
Re-write the server switch command contained in the packet.
virtual void run ()
This method is called when the connection thread starts executing.
QString timestamp () const
Generate a timestamp to be used in the log.
Private Types
enum ConnectionState { NotConnected = 0, Connected, ExchangeStarted, Encrypted }
State of the channel connection.
Private Attributes
QFile mCaptureLog
File to write the capture log to.
QString mClientAddress
IP address of the client connection.
CryptData mClientCryptData
Crypto data for the connection to the client.
uint32_t mClientID
Unique channel ID of this client connection.
uint8_t * mClientLoginPacket
Buffer to store the login packet before it is sent to the server.
uint32_t mClientLoginPacketSize
Size of the login packet that is waiting to be sent to the server.
QTcpSocket * mClientSocket
Connection to the client.
ConnectionState mClientState
Connection state for the connection to the client.
libcomp::Packet mKeyExchangePacket
Generated packet to be sent to the client upon connection.
QList< QByteArray > mPacketBuffer
List of packets to be sent to the target server when the connection is encrypted.
LoggerServer * mServer
Logger server this connection belongs to.
CryptData mServerCryptData
Crypto data for the connection to the target server.
QTcpSocket * mServerSocket
Connection to the target server.
ConnectionState mServerState
Connection state for the connection to the target server.
qintptr mSocketDescriptor
Socket descriptior of the client connection.
libcomp::String mUsername
Username used to log into the channel server.
Detailed Description
Proxy connection between the logger and the channel server.
Definition at line 47 of file ChannelConnection.h.
Member Enumeration Documentation
ConnectionState
enum ChannelConnection::ConnectionState private
State of the channel connection.
Enumerator
NotConnected
Socket is not connected.
Connected
Socket is connected awaiting data.
ExchangeStarted
Encryption key exchange has started.
Encrypted
Connection is encrypted and running normally.
Definition at line 163 of file ChannelConnection.h.
Constructor & Destructor Documentation
ChannelConnection()
ChannelConnection::ChannelConnection (LoggerServer * server, qintptr socketDescriptor, uint32_t clientID, QObject * parent = 0)
Create a new channel connection.
server LoggerServer this connection was made from.
socketDescriptor Netowrk socket for the connection.
clientID ID to identify this client in the log.
parent Parent object that this object belongs to. Should remain 0.
Definition at line 80 of file ChannelConnection.cpp.
Member Function Documentation
clientLost
void ChannelConnection::clientLost () protected slot
This method is called when the client closes the connection.
The connection to the channel server will be closed and the connection object will be deleted.
Definition at line 181 of file ChannelConnection.cpp.
References logMessage(), mCaptureLog, mClientID, mClientLoginPacket, mClientSocket, mClientState, mServerSocket, and NotConnected.
Referenced by run(), and serverLost().
clientReady
void ChannelConnection::clientReady () protected slot
This method is called when new data has arrived from the client.
The data will be parsed and then sent to the channel server.
Definition at line 292 of file ChannelConnection.cpp.
References Connected, libcomp::Packet::Data(), decryptPacket(), libcomp::Packet::Direct(), libcomp::Convert::ENCODING_UTF8, Encrypted, encryptPacket(), ExchangeStarted, libcomp::Decrypt::GenDiffieHellman(), libcomp::Packet::Left(), logPacket(), mClientCryptData, mClientLoginPacket, mClientLoginPacketSize, mClientSocket, mClientState, mKeyExchangePacket, mPacketBuffer, mServer, mServerCryptData, mServerSocket, mServerState, mUsername, NotConnected, libcomp::Packet::PeekU16Little(), libcomp::Packet::ReadArray(), libcomp::Packet::ReadString16Little(), libcomp::Packet::ReadString32Big(), libcomp::Packet::ReadU32Big(), libcomp::Packet::ReadU32Little(), LoggerServer::retrieveChannelKey(), libcomp::Packet::Rewind(), libcomp::Packet::Seek(), sendClientHello(), serverLost(), serverReady(), and libcomp::Packet::Size().
Referenced by run().
decryptPacket()
void ChannelConnection::decryptPacket (const BF_KEY * key, libcomp::Packet & p) protected
Decrypt a packet.
key Blowfish key to decrypt with.
p Packet to be decrypted.
Definition at line 265 of file ChannelConnection.cpp.
References libcomp::Packet::ReadArray(), libcomp::Packet::Rewind(), libcomp::Packet::Seek(), libcomp::Packet::Size(), and libcomp::Packet::WriteArray().
Referenced by clientReady(), and serverReady().
encryptPacket()
void ChannelConnection::encryptPacket (const BF_KEY * key, libcomp::Packet & p) protected
Encrypt a packet.
key Blowfish key to encrypt with.
p Packet to be encrypted.
Definition at line 237 of file ChannelConnection.cpp.
References libcomp::Packet::ReadArray(), libcomp::Packet::Rewind(), libcomp::Packet::Seek(), libcomp::Packet::Size(), and libcomp::Packet::WriteArray().
Referenced by clientReady(), exchangeKeys(), and serverReady().
logMessage()
void ChannelConnection::logMessage (const QString & msg) protected
Log a message to the console and GUI.
msg Message to log.
Definition at line 1023 of file ChannelConnection.cpp.
References LoggerServer::addLogMessage(), mServer, and timestamp().
Referenced by clientLost(), rewriteServerSwitchPacket(), and run().
logPacket()
void ChannelConnection::logPacket (libcomp::Packet & p, uint8_t source) protected
Log a packet to the capture file and send it to the live capgrep.
p Packet to log.
source Source of the packet. 0 if the packet came from the client, 1 if the packet came from the server.
Definition at line 1037 of file ChannelConnection.cpp.
References libcomp::Packet::ReadU32Big(), libcomp::Packet::Rewind(), and libcomp::Packet::Size().
Referenced by clientReady(), and serverReady().
packetHasServerSwitch()
bool ChannelConnection::packetHasServerSwitch (libcomp::Packet & p) protected
Determine if the packet has a server switch command.
p Packet to examine.
Returns
true if the packet contains a server switch command, false otherwise.
Definition at line 614 of file ChannelConnection.cpp.
References libcomp::Packet::Data(), libcomp::Packet::Decompress(), libcomp::Packet::Left(), libcomp::Packet::ReadS32Little(), libcomp::Packet::ReadU16Little(), libcomp::Packet::ReadU32Big(), libcomp::Packet::Rewind(), libcomp::Packet::Seek(), libcomp::Packet::Size(), libcomp::Packet::Skip(), and libcomp::Packet::Tell().
Referenced by serverReady().
rewriteServerSwitchPacket()
void ChannelConnection::rewriteServerSwitchPacket (libcomp::Packet & p) protected
Re-write the server switch command contained in the packet.
p Packet to rewrite.
Definition at line 714 of file ChannelConnection.cpp.
References libcomp::String::C(), libcomp::Packet::Clear(), libcomp::Packet::Compress(), libcomp::Packet::Data(), libcomp::Packet::Decompress(), libcomp::Convert::ENCODING_UTF8, libcomp::Packet::End(), libcomp::Packet::Left(), libcomp::String::Length(), logMessage(), mClientSocket, mServer, libcomp::Packet::ReadS32Little(), libcomp::Packet::ReadU16Little(), libcomp::Packet::ReadU32Big(), LoggerServer::registerChannelKey(), libcomp::Packet::Rewind(), libcomp::Packet::Seek(), libcomp::Packet::Size(), libcomp::Packet::Skip(), libcomp::Packet::Tell(), libcomp::Packet::WriteArray(), libcomp::Packet::WriteBlank(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteU16Big(), libcomp::Packet::WriteU16Little(), libcomp::Packet::WriteU32Big(), and libcomp::Packet::WriteU32Little().
Referenced by serverReady().
sendClientHello
void ChannelConnection::sendClientHello () protected slot
This method is called when the connection to the channel server is opened.
The client hello packet will be sent to the channel server.
Definition at line 514 of file ChannelConnection.cpp.
References mServerSocket.
Referenced by clientReady().
serverLost
void ChannelConnection::serverLost () protected slot
This method is called when the channel server closes the connection.
The connection to the client will be closed and the connection object will be deleted.
Definition at line 521 of file ChannelConnection.cpp.
References clientLost().
Referenced by clientReady(), and exchangeKeys().
serverReady
void ChannelConnection::serverReady () protected slot
This method is called when new data has arrived from the channel server.
The data will be parsed and then sent to the client.
Definition at line 527 of file ChannelConnection.cpp.
References libcomp::Packet::Data(), decryptPacket(), libcomp::Packet::Direct(), Encrypted, encryptPacket(), exchangeKeys(), logPacket(), mClientCryptData, mClientSocket, mServerCryptData, mServerSocket, mServerState, packetHasServerSwitch(), libcomp::Packet::ReadU32Big(), libcomp::Packet::Rewind(), rewriteServerSwitchPacket(), libcomp::Packet::Size(), and libcomp::Packet::WriteArray().
Referenced by clientReady().
timestamp()
QString ChannelConnection::timestamp () const protected
Generate a timestamp to be used in the log.
Returns
The timestamp string.
Definition at line 175 of file ChannelConnection.cpp.
Referenced by logMessage().
Member Data Documentation
mPacketBuffer
QList<QByteArray> ChannelConnection::mPacketBuffer private
List of packets to be sent to the target server when the connection is encrypted.
Definition at line 224 of file ChannelConnection.h.
Referenced by clientReady(), and exchangeKeys().
The documentation for this class was generated from the following files:
ChannelConnection.h
ChannelConnection.cpp