COMP_hack Logger: MainWindow Class Reference
MainWindow Class Reference
Main window for the COMP_hack Logger.
#include <MainWindow.h>
Public Slots
void addLogMessage (const QString &msg)
Display a new log message.
void addPacket (const QByteArray &p)
If the logger is connected to a capgrep instance in live mode, add the packet to the capgrep instance.
void init ()
Initialize the server and start listening on the required ports.
void showAbout ()
Display the about dialog.
void showCaptures ()
Open the captures folder using the default file browser.
void showSettings ()
Display the settings window.
void shutdown ()
Give one last chance to back out before shutting down the logger.
void startGame ()
This slot must be called by a QAction in the start game sub-menu.
Public Member Functions
MainWindow (const QString &capturePath, QWidget *parent=0)
Construct the main window class.
Static Public Member Functions
static QList< quint32 > findMatches (const void *haystack, quint32 haystack_size, const void *needle, quint32 needle_size)
Find all occurrences of a sequence of bytes in a larger byte buffer.
static bool versionCheck (const QString &path, float *floatVer, uint32_t *ver, bool *isUS)
Determine the version of the client executable.
Protected Slots
void updateClientList (const QVariantMap &clientList)
Reload the client list in the start game sub-menu.
Protected Member Functions
virtual void closeEvent (QCloseEvent *event)
When the main windows is closed, this method will be called.
void patchWebAccess (const QString &path)
Patch the webaccess.sdat file to direct the client login page to the logger.
QString serverLine () const
Get a string representing the IP address of the logger.
Protected Attributes
QString mCapturePath
Path to the directory capture files will be stored in.
QTcpSocket * mLiveSocket
Socket for the live mode capgrep connection to send packets to.
LoggerServer * mServer
Server object that controls all connections to the logger.
Ui::MainWindow ui
Generated class for the UI file.
Detailed Description
Main window for the COMP_hack Logger.
This window provides the interface to change settings on the logger as well as display feedback on the server operation. Any informational or error messages will be displayed in this window. Closing this window will terminate the application.
Definition at line 43 of file MainWindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (const QString & capturePath, QWidget * parent = 0)
Construct the main window class.
capturePath Path to folder that capture files will be saved into.
parent Parent widget that this window belongs to. Should remain 0.
Definition at line 47 of file MainWindow.cpp.
References init(), showAbout(), showCaptures(), showSettings(), shutdown(), and ui.
Member Function Documentation
addLogMessage
void MainWindow::addLogMessage (const QString & msg) slot
Display a new log message.
msg Message to display.
Definition at line 91 of file MainWindow.cpp.
References ui.
Referenced by init().
addPacket
void MainWindow::addPacket (const QByteArray & p) slot
If the logger is connected to a capgrep instance in live mode, add the packet to the capgrep instance.
This should only be used for channel packets.
p Packet to send to capgrep.
Definition at line 106 of file MainWindow.cpp.
References mLiveSocket.
Referenced by init().
closeEvent()
void MainWindow::closeEvent (QCloseEvent * event) protected virtual
When the main windows is closed, this method will be called.
This method will ensure the application exits.
event Close event object.
Definition at line 140 of file MainWindow.cpp.
References shutdown().
findMatches()
QList< quint32 > MainWindow::findMatches (const void * haystack, quint32 haystack_size, const void * needle, quint32 needle_size) static
Find all occurrences of a sequence of bytes in a larger byte buffer.
Why did I bother writing my own method for this? No clue ^_^.
haystack Buffer to search in.
haystack_size Size of the buffer to search in.
needle Data to search for.
needle_size Size of the data to search for.
Returns
List of byte offsets in the buffer of matching sequences.
Definition at line 282 of file MainWindow.cpp.
Referenced by versionCheck().
init
void MainWindow::init () slot
Initialize the server and start listening on the required ports.
This slot is called when the main event loop starts.
Definition at line 68 of file MainWindow.cpp.
References addLogMessage(), addPacket(), mCapturePath, mLiveSocket, mServer, LoggerServer::setCapturePath(), LoggerServer::startServer(), and updateClientList().
Referenced by MainWindow().
patchWebAccess()
void MainWindow::patchWebAccess (const QString & path) protected
Patch the webaccess.sdat file to direct the client login page to the logger.
This method should only be called if you wish to use the WebAuth feature of the logger. This feature is NOT needed or recommended.
path Path to the webaccess.sdat file.
Definition at line 256 of file MainWindow.cpp.
References libcomp::Decrypt::DecryptFile(), libcomp::Decrypt::EncryptFile(), and serverLine().
Referenced by startGame().
serverLine()
QString MainWindow::serverLine () const protected
Get a string representing the IP address of the logger.
This defaults to 127.0.0.1 and may need to be changed in some cases.
Returns
IP address of the logger.
Definition at line 164 of file MainWindow.cpp.
Referenced by patchWebAccess(), and startGame().
showCaptures
void MainWindow::showCaptures () slot
Open the captures folder using the default file browser.
On Windows, this will open the folder in Windows Explorer. On Linux, this will open the folder in Nautilus.
Definition at line 127 of file MainWindow.cpp.
References mCapturePath.
Referenced by MainWindow().
startGame
void MainWindow::startGame () slot
This slot must be called by a QAction in the start game sub-menu.
The requested client executable will be scanned for a version number. The version setting for that client (US or JP) will be updated. The ImagineClient.dat file will be modified to direct the client to the logger. This file must be backed up or restored using the COMP_hack updater. The client executable will then be started. If running Windows and the client is JP, the application will attempt to use AppLocale to change the locale to Japanese. If running Linux, the application will start the client with WINE and set the locale to Japanese if required.
Definition at line 170 of file MainWindow.cpp.
References LoggerServer::isWebAuthJPEnabled(), mServer, patchWebAccess(), serverLine(), LoggerServer::setChannelLogEnabled(), LoggerServer::setVersionJP(), LoggerServer::setVersionUS(), and versionCheck().
Referenced by updateClientList().
updateClientList
void MainWindow::updateClientList (const QVariantMap & clientList) protected slot
Reload the client list in the start game sub-menu.
clientList Mapping of client names to their paths. Both the keys and values should be of the QString type.
Definition at line 439 of file MainWindow.cpp.
References startGame(), and ui.
Referenced by init(), and showSettings().
versionCheck()
bool MainWindow::versionCheck (const QString & path, float * floatVer, uint32_t * ver, bool * isUS) static
Determine the version of the client executable.
For example, if the client version is 1.684U then floatVer is 1.684, ver is 1684, and isUS is true. If the client version is 1.441 then floatVer is 1.441, ver is 1441 and isUS is false.
path Path to the client executable to check.
floatVer Pointer to a variable to store the version number in.
ver Pointer to a variable to store the version number in.
isUS Pointer to a variable to store whether the client is US or JP.
Returns
true if the version number was determined, false if an error occured.
Definition at line 304 of file MainWindow.cpp.
References libcomp::PEFile::absoluteToOffset(), libcomp::PEFile::addressToOffset(), findMatches(), and libcomp::PEFile::offsetToAddress().
Referenced by Settings::addClient(), and startGame().
The documentation for this class was generated from the following files:
MainWindow.h
MainWindow.cpp