COMP_hack Capture Grep: Find Class Reference
Find Class Reference
Dialog used to find a packet.
#include <Find.h>
Public Slots
void findTerm ()
Find the current search term.
void findTerm (const QByteArray &term)
Find the binary sequence.
Public Member Functions
Find (PacketListFilter *model, QWidget *parent=0)
Construct the find dialog.
Protected Slots
void cancelSearch ()
The 'Cancel' button was clicked, close the window.
void doubleClicked (const QModelIndex &index)
An item in the search results has been double-clicked.
void termTypeChanged ()
The search type has changed.
Protected Attributes
SearchFilter * mFilter
Model to display the search results.
Ui::Find ui
Generated UI for the window.
Detailed Description
Dialog used to find a packet.
A packet can be found with three different methods: command code, text, binary. Command codes are input as hex values (like in the filter dialog). Text can be converted to one of multiple encodings selectable from a drop-down list. Once the text is converted, the binary sequence is then searched for. Binary searches convert a hex sequence into a byte encoded sequence to match in the packet data. The results of a search are displayed in a list and the search term for the list is indicated. Double-clicking an item in the list displays the matching packet/command in the main window. Note that the search results have the sample command code filter as the list in the main window.
Definition at line 47 of file Find.h.
Constructor & Destructor Documentation
Find()
Find::Find (PacketListFilter * model, QWidget * parent = 0)
Construct the find dialog.
model The item model to search. Parent widget (or null if this widget is a window).
Definition at line 42 of file Find.cpp.
References cancelSearch(), doubleClicked(), findTerm(), mFilter, termTypeChanged(), and ui.
Member Function Documentation
doubleClicked
void Find::doubleClicked (const QModelIndex & index) protected slot
An item in the search results has been double-clicked.
This method will display the matching data in the main window.
Definition at line 271 of file Find.cpp.
References mFilter.
Referenced by Find().
termTypeChanged
void Find::termTypeChanged () protected slot
The search type has changed.
The search type can be one of: command code, text, binary.
Definition at line 106 of file Find.cpp.
References ui.
Referenced by Find().
The documentation for this class was generated from the following files:
Find.h
Find.cpp