COMP_hack Capture Grep: Filter Class Reference
Filter Class Reference
Packet filter dialog.
#include <Filter.h>
Public Member Functions
Filter (QWidget *parent=0)
Construct the filter dialog.
Static Public Member Functions
static QString cmdStr (uint16_t cmd)
Convert the given command code to a string representation.
Protected Slots
void addBlack ()
Prompt the user for a command code to add to the black list.
void addWhite ()
Prompt the user for a command code to add to the white list.
void blackSelectionChanged ()
The black list selection has changed.
void cancel ()
Discard any changes and close the dialog.
void removeBlack ()
Remove the selected command from the black list.
void removeWhite ()
Remove the selected command from the white list.
void save ()
Save the settings and close the dialog.
void whiteSelectionChanged ()
The white list selection has changed.
Protected Attributes
QList< uint16_t > mBlackList
List of command codes in the black list.
QList< uint16_t > mWhiteList
List of command codes in the white list.
Ui::Filter ui
Generated UI for the dialog.
Detailed Description
Packet filter dialog.
The filter dialog presents two lists of packets that will be filtered. If the white list is not empty, only packets in the white list will be displayed. If a packet is in the black list, it will not be displayed.
Definition at line 42 of file Filter.h.
Constructor & Destructor Documentation
Filter()
Filter::Filter (QWidget * parent = 0)
Construct the filter dialog.
Parent window (or null if this dialog isn't modal).
Definition at line 33 of file Filter.cpp.
References addBlack(), addWhite(), blackSelectionChanged(), cancel(), cmdStr(), mBlackList, mWhiteList, removeBlack(), removeWhite(), save(), ui, and whiteSelectionChanged().
Member Function Documentation
blackSelectionChanged
void Filter::blackSelectionChanged () protected slot
The black list selection has changed.
This is used to check if the remove button should be enabled.
Definition at line 231 of file Filter.cpp.
References ui.
Referenced by Filter().
cmdStr()
QString Filter::cmdStr (uint16_t cmd) static
Convert the given command code to a string representation.
cmd Command code to convert to a string.
Returns
String representation of the command code.
Definition at line 78 of file Filter.cpp.
Referenced by Filter().
whiteSelectionChanged
void Filter::whiteSelectionChanged () protected slot
The white list selection has changed.
This is used to check if the remove button should be enabled.
Definition at line 225 of file Filter.cpp.
References ui.
Referenced by Filter().
The documentation for this class was generated from the following files:
Filter.h
Filter.cpp