COMP_hack: AccountDumpRequest.cpp File Reference
AccountDumpRequest.cpp File Reference
Request from the client to dump the account information.
#include "Packets.h"
#include <Account.h>
#include <AccountLogin.h>
#include <Decrypt.h>
#include <Log.h>
#include <ManagerPacket.h>
#include <Packet.h>
#include <PacketCodes.h>
#include "AccountManager.h"
#include "ChannelServer.h"
Macros
#define PART_SIZE (1024)
Functions
void DumpAccount (AccountManager *accountManager, const std::shared_ptr< ChannelClientConnection > client)
Detailed Description
Request from the client to dump the account information.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the Channel Server (channel).
Copyright (C) 2012-2018 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file AccountDumpRequest.cpp.
Macro Definition Documentation
PART_SIZE
#define PART_SIZE (1024)
Definition at line 44 of file AccountDumpRequest.cpp.
Referenced by DumpAccount().
Function Documentation
DumpAccount()
void DumpAccount (AccountManager * accountManager, const std::shared_ptr< ChannelClientConnection > client)
Definition at line 46 of file AccountDumpRequest.cpp.
References channel::AccountManager::DumpAccount(), PART_SIZE, libcomp::Decrypt::SHA1(), channel::state(), libcomp::String::ToUtf8(), libcomp::Packet::WriteArray(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().