COMP_hack: Barter.cpp File Reference
Barter.cpp File Reference
Request from the client to barter for items or other materials.
#include "Packets.h"
#include <DefinitionManager.h>
#include <Log.h>
#include <ManagerPacket.h>
#include <Packet.h>
#include <PacketCodes.h>
#include <ServerConstants.h>
#include <CharacterProgress.h>
#include <Item.h>
#include <ItemBox.h>
#include <MiItemData.h>
#include <MiNPCBarterData.h>
#include <MiNPCBarterItemData.h>
#include <MiPossessionData.h>
#include "ChannelServer.h"
#include "CharacterManager.h"
#include "EventManager.h"
Functions
void HandleBarter (const std::shared_ptr< ChannelServer > server, const std::shared_ptr< ChannelClientConnection > client, uint16_t barterID)
Detailed Description
Request from the client to barter for items or other materials.
Author
HACKfrost
This file is part of the Channel Server (channel).
Copyright (C) 2012-2018 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file Barter.cpp.
Function Documentation
HandleBarter()
void HandleBarter (const std::shared_ptr< ChannelServer > server, const std::shared_ptr< ChannelClientConnection > client, uint16_t barterID)
Definition at line 53 of file Barter.cpp.
References libcomp::String::Arg(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetCurrentMenuShopID(), channel::ClientState::GetDemonState(), channel::CharacterManager::HasValuable(), LOG_ERROR, channel::NONE, channel::state(), SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU16Little().