COMP_hack: channel::ChannelServer Class Reference
channel::ChannelServer Class Reference
Channel server that handles client packets in game.
#include <ChannelServer.h>
Public Types
typedef std::unordered_map< std::string, std::list< std::shared_ptr< libcomp::PersistentObject > > > PersistentObjectMap
Public Member Functions
ChannelServer (const char *szProgram, std::shared_ptr< objects::ServerConfig > config, std::shared_ptr< libcomp::ServerCommandLineParser > commandLine)
Create a new channel server.
virtual ~ChannelServer ()
Clean up the server.
virtual void Cleanup ()
This is called before Run() ends giving a derived class the chance to do additional cleanup.
virtual void FinishInitialize ()
AccountManager * GetAccountManager () const
Get a pointer to the account manager.
ActionManager * GetActionManager () const
Get a pointer to the action manager.
AIManager * GetAIManager () const
Get a pointer to the AI manager.
const std::list< std::shared_ptr< objects::RegisteredChannel > > GetAllRegisteredChannels ()
Get all channels registerd on the channel's world (including itself).
uint8_t GetChannelID ()
Get the current channel ID from the RegisteredChannel.
ChannelSyncManager * GetChannelSyncManager () const
Get a pointer to the data sync manager.
CharacterManager * GetCharacterManager () const
Get a pointer to the character manager.
ChatManager * GetChatManager () const
Get a pointer to the chat manager.
std::shared_ptr< objects::ServerConfig > GetConfig () const
std::shared_ptr< Database > GetDatabase (const EnumMap< objects::ServerConfig::DatabaseType_t, std::shared_ptr< objects::DatabaseConfig >> &configMap, bool performSetup, DataStore *pDataStore=nullptr, const std::string &migrationDirectory=std::string())
DataStore * GetDataStore ()
PersistentObjectMap GetDefaultCharacterObjectMap () const
Get the default character creation object map.
libcomp::DefinitionManager * GetDefinitionManager () const
Get a pointer to the definition manager.
EventManager * GetEventManager () const
Get a pointer to the event manager.
FusionManager * GetFusionManager () const
Get a pointer to the fusion manager.
std::shared_ptr< libcomp::Database > GetLobbyDatabase () const
Get the lobby database.
std::shared_ptr< ManagerConnection > GetManagerConnection () const
Get the connection manager for the server.
MatchManager * GetMatchManager () const
Get a pointer to the match manager.
int32_t GetNextEntityID ()
Increments and returns the next available entity ID.
int64_t GetNextObjectID ()
Increments and returns the next available object ID.
int32_t GetPAttributeDeadline ()
Get the system time deadline for all punitive attributes which matches midnight of the next Monday.
const std::shared_ptr< objects::RegisteredChannel > GetRegisteredChannel ()
Get the RegisteredChannel.
std::shared_ptr< objects::RegisteredWorld > GetRegisteredWorld ()
Get the RegisteredWorld.
libcomp::ServerDataManager * GetServerDataManager () const
Get a pointer to the server data manager.
int32_t GetServerTimeOffset ()
Get the configured server time offset in seconds.
SkillManager * GetSkillManager () const
Get a pointer to the skill manager.
virtual std::list< libcomp::Message::MessageType > GetSupportedTypes () const
gsl::not_null< TimerManager *> GetTimerManager ()
TokuseiManager * GetTokuseiManager () const
Get a pointer to the tokusei manager.
const WorldClock GetWorldClockTime ()
Get the world clock time of the server.
std::shared_ptr< libcomp::Database > GetWorldDatabase () const
Get the world database.
std::shared_ptr< objects::WorldSharedConfig > GetWorldSharedConfig () const
Get the world server supplied shared config settings.
ZoneManager * GetZoneManager () const
Get a pointer to the zone manager.
void HandleClockEvents ()
Clock event handler that is called once every second to update the the world time.
void HandleDemonQuestReset ()
Update and notify all currently connected players of demon quests becoming available for the next day.
virtual bool Initialize ()
Initialize the database connection and do anything else that can fail to execute that needs to be handled outside of a constructor.
void LoadAllRegisteredChannels ()
Load all of the channel's connected world's RegisteredChannel entries in the database.
virtual bool ProcessMessage (const libcomp::Message::Message *pMessage)
bool QueueWork (Function &&f, Args &&... args) const
bool RegisterClockEvent (WorldClockTime time, uint8_t type, bool remove)
Register a timed event to occur when the world clock is updated to pass that time.
bool RegisterServer (uint8_t channelID)
Register the channel with the lobby database.
void RegisterWorld (const std::shared_ptr< objects::RegisteredWorld > &registeredWorld)
Set the RegisteredWorld.
void RemoveConnection (std::shared_ptr< TcpConnection > &connection)
void ScheduleRecurringActions ()
Schedule recurring actions that continue to run until the server shuts down.
template<typename Function , typename... Args>
bool ScheduleWork (ServerTime timestamp, Function &&f, Args &&... args)
Schedule code work to be queued by the next server tick that occurs following the specified time.
bool SendSystemMessage (const std::shared_ptr< channel::ChannelClientConnection > &client, libcomp::String message, int8_t type, bool broadcast)
Sends an announcement to each client connected to world.
virtual void ServerReady ()
void SetLobbyDatabase (const std::shared_ptr< libcomp::Database > &database)
Set the lobby database.
void SetTimeOffset (uint32_t offset)
Set a custom time offset for the world clock (in seconds)
void SetWorldDatabase (const std::shared_ptr< libcomp::Database > &database)
Set the world database.
virtual void Shutdown ()
Call the Shutdown function on each worker.
virtual int Start (bool delayReady=false)
void StartGameTick ()
Generates server game ticks.
void Tick ()
Simulate a server tick, handling events like updating the server time and zone states as well as ansynchronously saving data.
Static Public Member Functions
static DH * CopyDiffieHellman (const DH *pDiffieHellman)
static DH * GenerateDiffieHellman ()
static std::string GetConfigPath ()
static std::shared_ptr< Database > GetDatabase (objects::ServerConfig::DatabaseType_t dbType, const EnumMap< objects::ServerConfig::DatabaseType_t, std::shared_ptr< objects::DatabaseConfig >> &configMap)
static std::string GetDefaultConfigPath ()
static int32_t GetExpirationInSeconds (uint32_t fixedTime, uint32_t relativeTo=0)
Get the amount of time left in an expiration relative to the server, in seconds.
static ServerTime GetServerTime ()
Get the current time relative to the server.
static DH * LoadDiffieHellman (const std::vector< char > &data)
static DH * LoadDiffieHellman (const String &prime)
static DH * LoadDiffieHellman (const void *pData, size_t dataSize)
static bool ReadConfig (std::shared_ptr< objects::ServerConfig > config, tinyxml2::XMLDocument &doc)
static bool ReadConfig (std::shared_ptr< objects::ServerConfig > config, libcomp::String filePath)
static std::vector< char > SaveDiffieHellman (const DH *pDiffieHellman)
static void SetConfigPath (const std::string &path)
Protected Member Functions
void AcceptHandler (asio::error_code errorCode, asio::ip::tcp::socket &socket)
bool AssignMessageQueue (const std::shared_ptr< libcomp::EncryptedConnection > &connection)
virtual std::shared_ptr< libcomp::TcpConnection > CreateConnection (asio::ip::tcp::socket &socket)
Create a connection to a newly active socket.
void CreateWorkers ()
const DH * GetDiffieHellman () const
virtual std::shared_ptr< libcomp::Worker > GetNextConnectionWorker ()
uint32_t GetTimeUntilMidnight ()
Get the number of seconds until midnight of the next day.
bool InsertDataFromFile (const libcomp::String &filePath, const std::shared_ptr< Database > &db, const std::set< std::string > &specificTypes={})
bool LoadDataFromFile (const libcomp::String &filePath, PersistentObjectMap &records, bool registerRecords, const std::set< std::string > &specificTypes={})
void RecalcNextWorldEventTime ()
Recalculate the next time the world clock will fire an event on.
virtual int Run ()
void SetDiffieHellman (DH *pDiffieHellman)
Static Protected Member Functions
static ServerTime GetServerTimeHighResolution ()
Get the current time relative to the server using the C++ standard high_resolution_clock.
static ServerTime GetServerTimeSteady ()
Get the current time relative to the server using the C++ standard steady_clock.
Protected Attributes
AccountManager * mAccountManager
Pointer to the account manager.
ActionManager * mActionManager
Pointer to the action manager.
AIManager * mAIManager
Pointer to the AI manager.
std::list< std::shared_ptr< objects::RegisteredChannel > > mAllRegisteredChannels
List of pointers to all RegisteredChannels for the world.
CharacterManager * mCharacterManager
Poiner to the character manager.
ChatManager * mChatManager
Pointer to the Chat Manager.
std::shared_ptr< ServerCommandLineParser > mCommandLine
std::shared_ptr< objects::ServerConfig > mConfig
std::list< std::shared_ptr< TcpConnection > > mConnections
std::mutex mConnectionsLock
libcomp::DataStore mDataStore
PersistentObjectMap mDefaultCharacterObjectMap
Map of default character creation state objects.
libcomp::DefinitionManager * mDefinitionManager
Pointer to the Definition Manager.
EventManager * mEventManager
Pointer to the Event Manager.
FusionManager * mFusionManager
Pointer to the Fusion Manager.
WorldClockTime mLastEventTrigger
World clock time of the last time zone events processed.
std::shared_ptr< libcomp::Database > mLobbyDatabase
A shared pointer to the main database used by the server.
std::mutex mLock
Server lock for shared resources.
libcomp::Worker mMainWorker
std::shared_ptr< ManagerConnection > mManagerConnection
Pointer to the manager in charge of connection messages.
MatchManager * mMatchManager
Pointer to the Match Manager.
int32_t mMaxEntityID
Highest entity ID currently assigned.
int64_t mMaxObjectID
Highest unique object ID currently assigned.
uint32_t mNextEventTime
System time representation of the next world clock event time that the clock needs to react to.
libcomp::Worker mQueueWorker
bool mRecalcTimeDependents
true if the sources of each time registered should should be updated based on the last clock update
std::shared_ptr< objects::RegisteredChannel > mRegisteredChannel
Pointer to the RegisteredChannel for this server.
std::shared_ptr< objects::RegisteredWorld > mRegisteredWorld
Pointer to the RegisteredWorld.
std::map< ServerTime, std::list< libcomp::Message::Execute * > > mScheduledWork
Timestamp ordered map of prepared Execute messages and timestamps associated to when they should be queued following a server tick.
libcomp::ServerDataManager * mServerDataManager
Pointer to the Server Data Manager.
asio::io_service mService
SkillManager * mSkillManager
Pointer to the Skill Manager.
ChannelSyncManager * mSyncManager
Data sync manager for the server.
std::mutex mTickLock
Server lock for setting the tick pending indicator.
volatile bool mTickRunning
If the tick thread should continue running.
uint8_t mTicksPending
Inidicates how many tick messages are sitting in the queue.
std::thread mTickThread
Thread that queues up tick messages after a delay.
std::mutex mTimeLock
Server lock for server time calculation.
libcomp::TimerManager mTimerManager
TokuseiManager * mTokuseiManager
Tokusei manager for the server.
std::list< std::shared_ptr< libcomp::Worker > > mWorkers
WorldClock mWorldClock
Server world clock.
std::map< WorldClockTime, std::set< uint8_t > > mWorldClockEvents
Map of world clock times to the type of event that will occur at that time.
std::shared_ptr< libcomp::Database > mWorldDatabase
A shared pointer to the world database used by the server.
ZoneManager * mZoneManager
Pointer to the Zone Manager.
Static Protected Attributes
static std::string sConfigPath
static GET_SERVER_TIME sGetServerTime
Function pointer to the most accurate time detection code available for the current machine.
Detailed Description
Channel server that handles client packets in game.
Definition at line 77 of file ChannelServer.h.
Constructor & Destructor Documentation
ChannelServer()
ChannelServer::ChannelServer (const char * szProgram, std::shared_ptr< objects::ServerConfig > config, std::shared_ptr< libcomp::ServerCommandLineParser > commandLine)
Create a new channel server.
Parameters
szProgram First command line argument for the application.
config Pointer to a casted ChannelConfig that will contain properties every server has in addition to channel specific ones.
Definition at line 97 of file ChannelServer.cpp.
~ChannelServer()
ChannelServer::~ChannelServer () virtual
Clean up the server.
Definition at line 769 of file ChannelServer.cpp.
References mAccountManager, mActionManager, mAIManager, mCharacterManager, mChatManager, mDefinitionManager, mEventManager, mFusionManager, mMatchManager, mServerDataManager, mSkillManager, mSyncManager, mTickRunning, mTickThread, mTokuseiManager, and mZoneManager.
Member Function Documentation
Cleanup()
void ChannelServer::Cleanup () virtual
This is called before Run() ends giving a derived class the chance to do additional cleanup.
Reimplemented from libcomp::BaseServer.
Definition at line 759 of file ChannelServer.cpp.
References mDefaultCharacterObjectMap, and mTickThread.
CreateConnection()
std::shared_ptr< libcomp::TcpConnection > ChannelServer::CreateConnection (asio::ip::tcp::socket & socket) protected virtual
Create a connection to a newly active socket.
Parameters
socket A new socket connection.
Returns
Pointer to the newly created connection
Reimplemented from libcomp::BaseServer.
Definition at line 1449 of file ChannelServer.cpp.
References libcomp::BaseServer::AssignMessageQueue(), libcomp::BaseServer::CopyDiffieHellman(), libcomp::BaseServer::GetDiffieHellman(), GetServerTime(), and libcomp::BaseServer::mConfig.
GetAccountManager()
AccountManager * ChannelServer::GetAccountManager () const
Get a pointer to the account manager.
Returns
Pointer to the AccountManager
Definition at line 1013 of file ChannelServer.cpp.
References mAccountManager.
Referenced by channel::ManagerConnection::RemoveClientConnection().
GetActionManager()
ActionManager * ChannelServer::GetActionManager () const
Get a pointer to the action manager.
Returns
Pointer to the ActionManager
Definition at line 1018 of file ChannelServer.cpp.
References mActionManager.
GetAIManager()
AIManager * ChannelServer::GetAIManager () const
Get a pointer to the AI manager.
Returns
Pointer to the AIManager
Definition at line 1023 of file ChannelServer.cpp.
References mAIManager.
GetAllRegisteredChannels()
const std::list< std::shared_ptr< objects::RegisteredChannel > > ChannelServer::GetAllRegisteredChannels ()
Get all channels registerd on the channel's world (including itself).
Returns
List of pointers to all of the world's registered channels
Definition at line 909 of file ChannelServer.cpp.
References mAllRegisteredChannels.
GetChannelID()
uint8_t ChannelServer::GetChannelID ()
Get the current channel ID from the RegisteredChannel.
Returns
Current channel ID
Definition at line 902 of file ChannelServer.cpp.
References mRegisteredChannel.
GetChannelSyncManager()
ChannelSyncManager * ChannelServer::GetChannelSyncManager () const
Get a pointer to the data sync manager.
Returns
Pointer to the ChannelSyncManager
Definition at line 1073 of file ChannelServer.cpp.
References mSyncManager.
GetCharacterManager()
CharacterManager * ChannelServer::GetCharacterManager () const
Get a pointer to the character manager.
Returns
Pointer to the CharacterManager
Definition at line 1028 of file ChannelServer.cpp.
References mCharacterManager.
GetChatManager()
ChatManager * ChannelServer::GetChatManager () const
Get a pointer to the chat manager.
Returns
Pointer to the ChatManager
Definition at line 1033 of file ChannelServer.cpp.
References mChatManager.
GetDefaultCharacterObjectMap()
ChannelServer::PersistentObjectMap ChannelServer::GetDefaultCharacterObjectMap () const
Get the default character creation object map.
Returns
Default character creation object map
Definition at line 1314 of file ChannelServer.cpp.
References mDefaultCharacterObjectMap.
GetDefinitionManager()
libcomp::DefinitionManager * ChannelServer::GetDefinitionManager () const
Get a pointer to the definition manager.
Returns
Pointer to the DefinitionManager
Definition at line 1063 of file ChannelServer.cpp.
References mDefinitionManager.
GetEventManager()
EventManager * ChannelServer::GetEventManager () const
Get a pointer to the event manager.
Returns
Pointer to the EventManager
Definition at line 1038 of file ChannelServer.cpp.
References mEventManager.
GetExpirationInSeconds()
int32_t ChannelServer::GetExpirationInSeconds (uint32_t fixedTime, uint32_t relativeTo = 0) static
Get the amount of time left in an expiration relative to the server, in seconds.
Returns
Time until expiration relative to the server, in seconds
Definition at line 799 of file ChannelServer.cpp.
Referenced by channel::MatchManager::CreatePvPInstance(), channel::CharacterManager::GetDemonPacketData(), HandleCultureItem(), channel::CharacterManager::SendDemonBoxData(), channel::CharacterManager::SendDemonData(), channel::CharacterManager::SendInvokeStatus(), channel::CharacterManager::SendPartnerData(), channel::MatchManager::UpdateMatchEntries(), and channel::MatchManager::UpdatePvPMatches().
GetFusionManager()
FusionManager * ChannelServer::GetFusionManager () const
Get a pointer to the fusion manager.
Returns
Pointer to the FusionManager
Definition at line 1043 of file ChannelServer.cpp.
References mFusionManager.
GetLobbyDatabase()
std::shared_ptr< libcomp::Database > ChannelServer::GetLobbyDatabase () const
Get the lobby database.
Returns
Pointer to the lobby's database
Definition at line 950 of file ChannelServer.cpp.
References mLobbyDatabase.
GetManagerConnection()
std::shared_ptr< ManagerConnection > ChannelServer::GetManagerConnection () const
Get the connection manager for the server.
Returns
Pointer to the connection manager.
Definition at line 1008 of file ChannelServer.cpp.
References mManagerConnection.
Referenced by channel::ManagerConnection::ScheduleClientTimeoutHandler().
GetMatchManager()
MatchManager * ChannelServer::GetMatchManager () const
Get a pointer to the match manager.
Returns
Pointer to the MatchManager
Definition at line 1048 of file ChannelServer.cpp.
References mMatchManager.
GetNextEntityID()
int32_t ChannelServer::GetNextEntityID ()
Increments and returns the next available entity ID.
Returns
Next game entity ID for the channel
Definition at line 1090 of file ChannelServer.cpp.
References mLock, and mMaxEntityID.
GetNextObjectID()
int64_t ChannelServer::GetNextObjectID ()
Increments and returns the next available object ID.
Returns
Next object ID for the channel
Definition at line 1096 of file ChannelServer.cpp.
References mLock, and mMaxObjectID.
GetPAttributeDeadline()
int32_t ChannelServer::GetPAttributeDeadline ()
Get the system time deadline for all punitive attributes which matches midnight of the next Monday.
Punitive atributes are used for time restricted actions such as participation in the "invoke" events.
Returns
System time respresenting the punitive attribute deadline
Definition at line 1283 of file ChannelServer.cpp.
References GetWorldClockTime().
GetRegisteredChannel()
const std::shared_ptr< objects::RegisteredChannel > ChannelServer::GetRegisteredChannel ()
Get the RegisteredChannel.
Returns
Pointer to the RegisteredChannel
Definition at line 897 of file ChannelServer.cpp.
References mRegisteredChannel.
GetRegisteredWorld()
std::shared_ptr< objects::RegisteredWorld > ChannelServer::GetRegisteredWorld ()
Get the RegisteredWorld.
Returns
Pointer to the RegisteredWorld
Definition at line 914 of file ChannelServer.cpp.
References mRegisteredWorld.
GetServerDataManager()
libcomp::ServerDataManager * ChannelServer::GetServerDataManager () const
Get a pointer to the server data manager.
Returns
Pointer to the ServerDataManager
Definition at line 1068 of file ChannelServer.cpp.
References mServerDataManager.
GetServerTime()
ServerTime ChannelServer::GetServerTime () static
Get the current time relative to the server.
Returns
Current time relative to the server
Definition at line 794 of file ChannelServer.cpp.
References sGetServerTime.
Referenced by channel::SkillManager::ActivateSkill(), channel::ZoneManager::AddEnemiesToZone(), channel::CharacterManager::AddRemoveOpponent(), channel::SkillManager::BeginSkillExecution(), channel::SkillManager::CompleteSkillExecution(), CreateConnection(), channel::Zone::CreateEncounter(), channel::ActionManager::CreateLoot(), channel::MatchManager::CreatePvPInstance(), channel::ActionManager::Delay(), channel::Zone::EnableSpawnGroups(), channel::MatchManager::EnterDiaspora(), channel::MatchManager::EnterUltimateBattle(), channel::ZoneManager::EnterZone(), channel::SkillManager::ExecuteNormalSkill(), channel::SkillManager::ExecuteSkill(), channel::ZoneManager::ExpireRentals(), channel::SkillManager::FinalizeSkillExecution(), channel::ZoneManager::FixCurrentPosition(), channel::Zone::GetActiveEntitiesInRadius(), channel::ActiveEntityState::GetMovementSpeed(), channel::ChatManager::GMCommand_Enemy(), channel::ZoneManager::HandleDeathTimeOut(), channel::SkillManager::HandleKills(), channel::AccountManager::HandleLogoutRequest(), channel::SkillManager::HandleNegotiations(), channel::ZoneManager::HandleSpecialInstancePopulate(), channel::PlasmaState::HasStateChangePoints(), channel::PlasmaState::HidePoint(), channel::ZoneManager::LeaveZone(), channel::SkillManager::Mount(), channel::Zone::OccupyPvPBase(), channel::PlasmaState::PopHidePoints(), channel::PlasmaState::PopRespawnPoints(), channel::SkillManager::PrepareFusionSkill(), channel::SkillManager::ProcessSkillResult(), channel::SkillManager::ProcessSkillResultFinal(), channel::Zone::RemoveEntity(), channel::SkillManager::Rest(), channel::CharacterManager::ReviveCharacter(), channel::ManagerConnection::ScheduleClientTimeoutHandler(), channel::ZoneManager::ScheduleInstanceAccessTimeOut(), channel::ZoneManager::ScheduleTimerExpiration(), SendClientReadyData(), channel::ZoneManager::SendInstanceTimer(), channel::MatchManager::SendPhase(), channel::ZoneManager::SendPopulateZoneData(), channel::ActiveEntityState::SetHPMP(), channel::PlasmaState::SetPickResult(), channel::SkillManager::SetSkillCompleteState(), channel::AIState::SetStatus(), channel::SkillManager::SpecialSkill(), channel::PerformanceTimer::Start(), channel::AICommand::Start(), channel::ZoneManager::StartInstanceTimer(), channel::MatchManager::StartStopMatch(), channel::MatchManager::StartUltimateBattleTimer(), channel::PerformanceTimer::Stop(), channel::ZoneManager::StopInstanceTimer(), channel::SkillManager::TargetInRange(), Tick(), channel::MatchManager::ToggleDiasporaBase(), channel::MatchManager::UltimateBattleQueue(), channel::MatchManager::UltimateBattleTick(), channel::ZoneManager::UpdateActiveZoneStates(), channel::ZoneManager::UpdateDeathTimeOut(), channel::MatchManager::UpdatePvPMatches(), channel::ZoneManager::UpdateSpawnGroups(), channel::AIManager::UseDiasporaQuake(), and channel::ZoneManager::Warp().
GetServerTimeHighResolution()
ServerTime ChannelServer::GetServerTimeHighResolution () static protected
Get the current time relative to the server using the C++ standard high_resolution_clock.
Returns
Current time relative to the server
Definition at line 1490 of file ChannelServer.cpp.
GetServerTimeOffset()
int32_t ChannelServer::GetServerTimeOffset ()
Get the configured server time offset in seconds.
Returns
Server time offset in seconds
Definition at line 1277 of file ChannelServer.cpp.
References GetWorldSharedConfig().
Referenced by GetWorldClockTime().
GetServerTimeSteady()
ServerTime ChannelServer::GetServerTimeSteady () static protected
Get the current time relative to the server using the C++ standard steady_clock.
Returns
Current time relative to the server
Definition at line 1483 of file ChannelServer.cpp.
GetSkillManager()
SkillManager * ChannelServer::GetSkillManager () const
Get a pointer to the skill manager.
Returns
Pointer to the SkillManager
Definition at line 1053 of file ChannelServer.cpp.
References mSkillManager.
GetTimeUntilMidnight()
uint32_t ChannelServer::GetTimeUntilMidnight () protected
Get the number of seconds until midnight of the next day.
Useful for scheduling timed events.
Returns
Number of seconds until midnight of the next day
Definition at line 1301 of file ChannelServer.cpp.
References GetWorldClockTime().
Referenced by HandleDemonQuestReset(), and ScheduleRecurringActions().
GetTokuseiManager()
TokuseiManager * ChannelServer::GetTokuseiManager () const
Get a pointer to the tokusei manager.
Returns
Pointer to the TokuseiManager
Definition at line 1078 of file ChannelServer.cpp.
References mTokuseiManager.
GetWorldClockTime()
const WorldClock ChannelServer::GetWorldClockTime ()
Get the world clock time of the server.
This is thread safe and checks to make sure it does not calculate more than is needed.
Returns
Current world clock time
Definition at line 814 of file ChannelServer.cpp.
References channel::WorldClock::CycleOffset, channel::WorldClock::Day, channel::WorldClock::GameOffset, GetServerTimeOffset(), channel::WorldClockTime::Hour, channel::WorldClockTime::Min, mNextEventTime, channel::WorldClock::Month, channel::WorldClockTime::MoonPhase, mRecalcTimeDependents, mTimeLock, mWorldClock, RecalcNextWorldEventTime(), channel::WorldClockTime::SystemHour, channel::WorldClockTime::SystemMin, channel::WorldClock::SystemSec, channel::WorldClock::SystemTime, and channel::WorldClock::WeekDay.
Referenced by GetPAttributeDeadline(), GetTimeUntilMidnight(), HandleClockEvents(), and ScheduleRecurringActions().
GetWorldDatabase()
std::shared_ptr< libcomp::Database > ChannelServer::GetWorldDatabase () const
Get the world database.
Returns
Pointer to the world's database
Definition at line 940 of file ChannelServer.cpp.
References mWorldDatabase.
GetWorldSharedConfig()
std::shared_ptr< objects::WorldSharedConfig > ChannelServer::GetWorldSharedConfig () const
Get the world server supplied shared config settings.
Returns
Pointer to the world shared config
Definition at line 1084 of file ChannelServer.cpp.
References libcomp::BaseServer::GetConfig().
Referenced by GetServerTimeOffset().
GetZoneManager()
ZoneManager * ChannelServer::GetZoneManager () const
Get a pointer to the zone manager.
Returns
Pointer to the ZoneManager
Definition at line 1058 of file ChannelServer.cpp.
References mZoneManager.
HandleClockEvents()
void ChannelServer::HandleClockEvents ()
Clock event handler that is called once every second to update the the world time.
If the registered "next time" is hit, the time sources will be notified to recalculate updates.
Definition at line 1396 of file ChannelServer.cpp.
References GetWorldClockTime(), channel::ZoneManager::HandleTimedActions(), LOG_DEBUG, mLastEventTrigger, mRecalcTimeDependents, mTimeLock, mTokuseiManager, mZoneManager, and channel::TokuseiManager::RecalcTimedTokusei().
Referenced by ScheduleRecurringActions().
HandleDemonQuestReset()
void ChannelServer::HandleDemonQuestReset ()
Update and notify all currently connected players of demon quests becoming available for the next day.
By default this is scheduled to execute at midnight UTC.
Definition at line 1422 of file ChannelServer.cpp.
References channel::ClientState::GetAccountUID(), GetTimeUntilMidnight(), HandleDemonQuestReset(), LOG_DEBUG, LOG_ERROR, mEventManager, mManagerConnection, libcomp::BaseServer::mTimerManager, channel::EventManager::ResetDemonQuests(), libcomp::TimerManager::ScheduleEventIn(), and channel::state().
Referenced by HandleDemonQuestReset(), and ScheduleRecurringActions().
Initialize()
bool ChannelServer::Initialize () virtual
Initialize the database connection and do anything else that can fail to execute that needs to be handled outside of a constructor.
This calls the BaseServer version as well to perform shared init steps.
Parameters
self Pointer to this server to be used as a reference in packet handling code.
Returns
true on success, false on failure
Reimplemented from libcomp::BaseServer.
Definition at line 109 of file ChannelServer.cpp.
References libcomp::Worker::AddManager(), libcomp::BaseServer::GetConfigPath(), libcomp::BaseServer::GetDataStore(), libcomp::Worker::GetMessageQueue(), channel::TokuseiManager::Initialize(), libcomp::DefinitionManager::LoadAllData(), libcomp::ServerDataManager::LoadData(), libcomp::BaseServer::LoadDataFromFile(), LOG_CRITICAL, LOG_INFO, mAccountManager, mActionManager, mAIManager, mCharacterManager, mChatManager, libcomp::BaseServer::mConfig, mDefaultCharacterObjectMap, mDefinitionManager, mEventManager, mFusionManager, libcomp::BaseServer::mMainWorker, mManagerConnection, mMatchManager, libcomp::BaseServer::mQueueWorker, mServerDataManager, libcomp::BaseServer::mService, mSkillManager, mSyncManager, mTokuseiManager, libcomp::BaseServer::mWorkers, mZoneManager, libcomp::InternalConnection::SetName(), libcomp::TcpConnection::STATUS_CONNECTED, and to_underlying().
LoadAllRegisteredChannels()
void ChannelServer::LoadAllRegisteredChannels ()
Load all of the channel's connected world's RegisteredChannel entries in the database.
This allows other channels to be seen by the current channel for listing existing channels to the client.
Definition at line 925 of file ChannelServer.cpp.
References libcomp::PersistentObject::LoadAll(), mAllRegisteredChannels, mRegisteredChannel, and mWorldDatabase.
RecalcNextWorldEventTime()
void ChannelServer::RecalcNextWorldEventTime () protected
Recalculate the next time the world clock will fire an event on.
This will be stored as a system timestamp for easy comparison.
Definition at line 1497 of file ChannelServer.cpp.
References channel::WorldClockTime::Hour, channel::WorldClockTime::IsSet(), channel::WorldClockTime::Min, mNextEventTime, channel::WorldClockTime::MoonPhase, mWorldClock, mWorldClockEvents, channel::WorldClockTime::SystemHour, channel::WorldClockTime::SystemMin, channel::WorldClock::SystemSec, and channel::WorldClock::SystemTime.
Referenced by GetWorldClockTime(), and RegisterClockEvent().
RegisterClockEvent()
bool ChannelServer::RegisterClockEvent (WorldClockTime time, uint8_t type, bool remove)
Register a timed event to occur when the world clock is updated to pass that time.
Parameters
time Time to register
type Type identifier to register the time with. This allows multiple sources to register the same time and have the server clean up as needed upon removal.
remove true if the time should be removed, false if it should should be registered
Returns
true if the time was registered properly, false if a failure ocurred
Definition at line 1349 of file ChannelServer.cpp.
References channel::WorldClockTime::Hour, channel::WorldClockTime::IsSet(), channel::WorldClockTime::Min, mTimeLock, mWorldClockEvents, RecalcNextWorldEventTime(), channel::WorldClockTime::SystemHour, and channel::WorldClockTime::SystemMin.
RegisterServer()
bool ChannelServer::RegisterServer (uint8_t channelID)
Register the channel with the lobby database.
Parameters
channelID Channel ID from the world to register with
Returns
true on success, false on failure
Definition at line 960 of file ChannelServer.cpp.
References libcomp::String::Arg(), mAllRegisteredChannels, libcomp::BaseServer::mConfig, mRegisteredChannel, and mWorldDatabase.
RegisterWorld()
void ChannelServer::RegisterWorld (const std::shared_ptr< objects::RegisteredWorld > & registeredWorld)
Set the RegisteredWorld.
Parameters
registeredWorld Pointer to the RegisteredWorld
Definition at line 919 of file ChannelServer.cpp.
References mRegisteredWorld.
ScheduleRecurringActions()
void ChannelServer::ScheduleRecurringActions ()
Schedule recurring actions that continue to run until the server shuts down.
This does not need to run until the channel has successfully registered with the world.
Definition at line 1319 of file ChannelServer.cpp.
References libcomp::BaseServer::GetConfig(), GetTimeUntilMidnight(), GetWorldClockTime(), HandleClockEvents(), HandleDemonQuestReset(), mManagerConnection, libcomp::BaseServer::mTimerManager, mTokuseiManager, channel::TokuseiManager::RecalcTimedTokusei(), libcomp::TimerManager::ScheduleEventIn(), libcomp::TimerManager::SchedulePeriodicEvent(), and StartGameTick().
ScheduleWork()
template<typename Function , typename... Args> bool channel::ChannelServer::ScheduleWork (ServerTime timestamp, Function && f, Args &&... args) inline
Schedule code work to be queued by the next server tick that occurs following the specified time.
Parameters
timestamp ServerTime timestamp that needs to pass for the specified work to be processed
f Function (lambda) to execute
args Arguments to pass to the function when it is executed
Returns
true on success, false on failure
Definition at line 419 of file ChannelServer.h.
References mLock, and mScheduledWork.
SendSystemMessage()
bool ChannelServer::SendSystemMessage (const std::shared_ptr< channel::ChannelClientConnection > & client, libcomp::String message, int8_t type, bool broadcast)
Sends an announcement to each client connected to world.
Parameters
client Client that sent announcement packet to channel
message Content of message that will be announced
type Type of message to send 0) Red ticker message 1) White ticker message 2) Blue ticker message 3) Purple ticker message 4) COMP shop description
broadcast If true, the packet will be broadcasted to everyone in the current zone
Returns
true if the message was successfully sent, false otherwise.
Definition at line 1255 of file ChannelServer.cpp.
References mManagerConnection, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteString16Little().
SetLobbyDatabase()
void ChannelServer::SetLobbyDatabase (const std::shared_ptr< libcomp::Database > & database)
Set the lobby database.
Parameters
database Pointer to the lobby's database
Definition at line 955 of file ChannelServer.cpp.
References mLobbyDatabase.
SetTimeOffset()
void ChannelServer::SetTimeOffset (uint32_t offset)
Set a custom time offset for the world clock (in seconds)
Parameters
offset Custom time offset (in seconds)
Definition at line 886 of file ChannelServer.cpp.
References channel::WorldClock::GameOffset, mLastEventTrigger, mNextEventTime, mTimeLock, mWorldClock, and channel::WorldClock::SystemTime.
SetWorldDatabase()
void ChannelServer::SetWorldDatabase (const std::shared_ptr< libcomp::Database > & database)
Set the world database.
Parameters
database Pointer to the world's database
Definition at line 945 of file ChannelServer.cpp.
References mWorldDatabase.
Shutdown()
void ChannelServer::Shutdown () virtual
Call the Shutdown function on each worker.
This should be called only before preparing to stop the application.
Reimplemented from libcomp::BaseServer.
Definition at line 752 of file ChannelServer.cpp.
References mTickRunning.
StartGameTick()
void ChannelServer::StartGameTick ()
Generates server game ticks.
Definition at line 1201 of file ChannelServer.cpp.
References libcomp::Worker::GetMessageQueue(), LOG_DEBUG, libcomp::BaseServer::mQueueWorker, mTickLock, mTickRunning, mTicksPending, and mTickThread.
Referenced by ScheduleRecurringActions().
Tick()
void ChannelServer::Tick ()
Simulate a server tick, handling events like updating the server time and zone states as well as ansynchronously saving data.
Definition at line 1102 of file ChannelServer.cpp.
References libcomp::Worker::GetMessageQueue(), libcomp::PersistentObject::GetObjectByUUID(), GetServerTime(), LOG_ERROR, mLobbyDatabase, mLock, mManagerConnection, libcomp::BaseServer::mQueueWorker, mScheduledWork, mTickLock, mTicksPending, mWorldDatabase, mZoneManager, channel::PerformanceTimer::Start(), channel::PerformanceTimer::Stop(), and channel::ZoneManager::UpdateActiveZoneStates().
Referenced by channel::ManagerSystem::ProcessMessage().
Member Data Documentation
mAccountManager
AccountManager* channel::ChannelServer::mAccountManager protected
Pointer to the account manager.
Definition at line 505 of file ChannelServer.h.
Referenced by GetAccountManager(), Initialize(), and ~ChannelServer().
mActionManager
ActionManager* channel::ChannelServer::mActionManager protected
Pointer to the action manager.
Definition at line 508 of file ChannelServer.h.
Referenced by GetActionManager(), Initialize(), and ~ChannelServer().
mAIManager
AIManager* channel::ChannelServer::mAIManager protected
Pointer to the AI manager.
Definition at line 511 of file ChannelServer.h.
Referenced by GetAIManager(), Initialize(), and ~ChannelServer().
mAllRegisteredChannels
std::list<std::shared_ptr<objects::RegisteredChannel> > channel::ChannelServer::mAllRegisteredChannels protected
List of pointers to all RegisteredChannels for the world.
Definition at line 499 of file ChannelServer.h.
Referenced by GetAllRegisteredChannels(), LoadAllRegisteredChannels(), and RegisterServer().
mCharacterManager
CharacterManager* channel::ChannelServer::mCharacterManager protected
Poiner to the character manager.
Definition at line 514 of file ChannelServer.h.
Referenced by GetCharacterManager(), Initialize(), and ~ChannelServer().
mChatManager
ChatManager* channel::ChannelServer::mChatManager protected
Pointer to the Chat Manager.
Definition at line 517 of file ChannelServer.h.
Referenced by GetChatManager(), Initialize(), and ~ChannelServer().
mDefaultCharacterObjectMap
PersistentObjectMap channel::ChannelServer::mDefaultCharacterObjectMap protected
Map of default character creation state objects.
Definition at line 502 of file ChannelServer.h.
Referenced by Cleanup(), GetDefaultCharacterObjectMap(), and Initialize().
mDefinitionManager
libcomp::DefinitionManager* channel::ChannelServer::mDefinitionManager protected
Pointer to the Definition Manager.
Definition at line 535 of file ChannelServer.h.
Referenced by GetDefinitionManager(), Initialize(), and ~ChannelServer().
mEventManager
EventManager* channel::ChannelServer::mEventManager protected
Pointer to the Event Manager.
Definition at line 520 of file ChannelServer.h.
Referenced by GetEventManager(), HandleDemonQuestReset(), Initialize(), and ~ChannelServer().
mFusionManager
FusionManager* channel::ChannelServer::mFusionManager protected
Pointer to the Fusion Manager.
Definition at line 523 of file ChannelServer.h.
Referenced by GetFusionManager(), Initialize(), and ~ChannelServer().
mLastEventTrigger
WorldClockTime channel::ChannelServer::mLastEventTrigger protected
World clock time of the last time zone events processed.
Definition at line 550 of file ChannelServer.h.
Referenced by HandleClockEvents(), and SetTimeOffset().
mLobbyDatabase
std::shared_ptr<libcomp::Database> channel::ChannelServer::mLobbyDatabase protected
A shared pointer to the main database used by the server.
Definition at line 493 of file ChannelServer.h.
Referenced by GetLobbyDatabase(), SetLobbyDatabase(), and Tick().
mLock
std::mutex channel::ChannelServer::mLock protected
Server lock for shared resources.
Definition at line 574 of file ChannelServer.h.
Referenced by GetNextEntityID(), GetNextObjectID(), ScheduleWork(), and Tick().
mManagerConnection
std::shared_ptr<ManagerConnection> channel::ChannelServer::mManagerConnection protected
Pointer to the manager in charge of connection messages.
Definition at line 484 of file ChannelServer.h.
Referenced by GetManagerConnection(), HandleDemonQuestReset(), Initialize(), ScheduleRecurringActions(), SendSystemMessage(), and Tick().
mMatchManager
MatchManager* channel::ChannelServer::mMatchManager protected
Pointer to the Match Manager.
Definition at line 526 of file ChannelServer.h.
Referenced by GetMatchManager(), Initialize(), and ~ChannelServer().
mMaxEntityID
int32_t channel::ChannelServer::mMaxEntityID protected
Highest entity ID currently assigned.
Definition at line 561 of file ChannelServer.h.
Referenced by GetNextEntityID().
mMaxObjectID
int64_t channel::ChannelServer::mMaxObjectID protected
Highest unique object ID currently assigned.
Definition at line 564 of file ChannelServer.h.
Referenced by GetNextObjectID().
mNextEventTime
uint32_t channel::ChannelServer::mNextEventTime protected
System time representation of the next world clock event time that the clock needs to react to.
Definition at line 554 of file ChannelServer.h.
Referenced by GetWorldClockTime(), RecalcNextWorldEventTime(), and SetTimeOffset().
mRecalcTimeDependents
bool channel::ChannelServer::mRecalcTimeDependents protected
true if the sources of each time registered should should be updated based on the last clock update
Definition at line 558 of file ChannelServer.h.
Referenced by GetWorldClockTime(), and HandleClockEvents().
mRegisteredChannel
std::shared_ptr<objects::RegisteredChannel> channel::ChannelServer::mRegisteredChannel protected
Pointer to the RegisteredChannel for this server.
Definition at line 496 of file ChannelServer.h.
Referenced by GetChannelID(), GetRegisteredChannel(), LoadAllRegisteredChannels(), and RegisterServer().
mRegisteredWorld
std::shared_ptr<objects::RegisteredWorld> channel::ChannelServer::mRegisteredWorld protected
Pointer to the RegisteredWorld.
Definition at line 487 of file ChannelServer.h.
Referenced by GetRegisteredWorld(), and RegisterWorld().
mScheduledWork
std::map<ServerTime, std::list<libcomp::Message::Execute*> > channel::ChannelServer::mScheduledWork protected
Timestamp ordered map of prepared Execute messages and timestamps associated to when they should be queued following a server tick.
Definition at line 473 of file ChannelServer.h.
Referenced by ScheduleWork(), and Tick().
mServerDataManager
libcomp::ServerDataManager* channel::ChannelServer::mServerDataManager protected
Pointer to the Server Data Manager.
Definition at line 538 of file ChannelServer.h.
Referenced by GetServerDataManager(), Initialize(), and ~ChannelServer().
mSkillManager
SkillManager* channel::ChannelServer::mSkillManager protected
Pointer to the Skill Manager.
Definition at line 529 of file ChannelServer.h.
Referenced by GetSkillManager(), Initialize(), and ~ChannelServer().
mSyncManager
ChannelSyncManager* channel::ChannelServer::mSyncManager protected
Data sync manager for the server.
Definition at line 541 of file ChannelServer.h.
Referenced by GetChannelSyncManager(), Initialize(), and ~ChannelServer().
mTickLock
std::mutex channel::ChannelServer::mTickLock protected
Server lock for setting the tick pending indicator.
Definition at line 580 of file ChannelServer.h.
Referenced by StartGameTick(), and Tick().
mTickRunning
volatile bool channel::ChannelServer::mTickRunning protected
If the tick thread should continue running.
Definition at line 583 of file ChannelServer.h.
Referenced by Shutdown(), StartGameTick(), and ~ChannelServer().
mTicksPending
uint8_t channel::ChannelServer::mTicksPending protected
Inidicates how many tick messages are sitting in the queue.
Incremented by StartTick and decremented by Tick.
Definition at line 568 of file ChannelServer.h.
Referenced by StartGameTick(), and Tick().
mTickThread
std::thread channel::ChannelServer::mTickThread protected
Thread that queues up tick messages after a delay.
Definition at line 571 of file ChannelServer.h.
Referenced by Cleanup(), StartGameTick(), and ~ChannelServer().
mTimeLock
std::mutex channel::ChannelServer::mTimeLock protected
Server lock for server time calculation.
Definition at line 577 of file ChannelServer.h.
Referenced by GetWorldClockTime(), HandleClockEvents(), RegisterClockEvent(), and SetTimeOffset().
mTokuseiManager
TokuseiManager* channel::ChannelServer::mTokuseiManager protected
Tokusei manager for the server.
Definition at line 544 of file ChannelServer.h.
Referenced by GetTokuseiManager(), HandleClockEvents(), Initialize(), ScheduleRecurringActions(), and ~ChannelServer().
mWorldClock
WorldClock channel::ChannelServer::mWorldClock protected
Server world clock.
Definition at line 547 of file ChannelServer.h.
Referenced by GetWorldClockTime(), RecalcNextWorldEventTime(), and SetTimeOffset().
mWorldClockEvents
std::map<WorldClockTime, std::set<uint8_t> > channel::ChannelServer::mWorldClockEvents protected
Map of world clock times to the type of event that will occur at that time.
Types include: 1) Spawn activation/deactivation 2) Tokusei active timespans 3) Zone event trigger 4) Global zone event trigger
Definition at line 481 of file ChannelServer.h.
Referenced by RecalcNextWorldEventTime(), and RegisterClockEvent().
mWorldDatabase
std::shared_ptr<libcomp::Database> channel::ChannelServer::mWorldDatabase protected
A shared pointer to the world database used by the server.
Definition at line 490 of file ChannelServer.h.
Referenced by GetWorldDatabase(), LoadAllRegisteredChannels(), RegisterServer(), SetWorldDatabase(), and Tick().
mZoneManager
ZoneManager* channel::ChannelServer::mZoneManager protected
Pointer to the Zone Manager.
Definition at line 532 of file ChannelServer.h.
Referenced by GetZoneManager(), HandleClockEvents(), Initialize(), Tick(), and ~ChannelServer().
sGetServerTime
GET_SERVER_TIME ChannelServer::sGetServerTime static protected
Initial value:
=
    std::chrono::high_resolution_clock::is_steady
        ? &ChannelServer::GetServerTimeHighResolution
        : &ChannelServer::GetServerTimeSteady
Function pointer to the most accurate time detection code available for the current machine.
Definition at line 462 of file ChannelServer.h.
Referenced by GetServerTime().
The documentation for this class was generated from the following files:
ChannelServer.h
ChannelServer.cpp