COMP_hack: channel::Zone Class Reference
channel::Zone Class Reference
Represents a server zone containing client connections, objects, enemies, etc.
#include <Zone.h>
Public Member Functions
Zone ()
Create a new zone.
Zone (uint32_t id, const std::shared_ptr< objects::ServerZone > &definition)
Create a new zone.
Zone (const Zone &other)
Explicitly defined copy constructor necessary due to removal of implicit constructor from non-copyable mutex member.
~Zone ()
Clean up the zone.
void AddBazaar (const std::shared_ptr< BazaarState > &bazaar)
Add a bazaar to the zone.
void AddConnection (const std::shared_ptr< ChannelClientConnection > &client)
Add a client connection to the zone and register its world CID.
void AddEnemy (const std::shared_ptr< EnemyState > &enemy)
Add an enemy to the zone.
void AddLootBox (const std::shared_ptr< LootBoxState > &box, uint32_t bossGroupID=0)
Add a loot body to the zone.
void AddNPC (const std::shared_ptr< NPCState > &npc)
Add an NPC to the zone.
void AddObject (const std::shared_ptr< ServerObjectState > &object)
Add an object to the zone.
void AddPlasma (const std::shared_ptr< PlasmaState > &plasma)
Add a plasma grouping to the zone.
bool ClaimBossBox (int32_t id, int32_t looterID)
Mark a boss box as belonging to the specified entity if the box is not already claimed and the entity has not already claimed the box.
void Cleanup ()
Perform pre-deletion cleanup actions.
void CreateEncounter (const std::list< std::shared_ptr< EnemyState >> &enemies, std::shared_ptr< objects::ActionSpawn > spawnSource=nullptr)
Create an encounter from a group of enemies and register them with the zone.
bool EnableDisableSpawnGroups (const std::set< uint32_t > &spawnGroupIDs, bool enable)
Enable or disable the supplied spawn groups and also disable (or enable) any spawn location groups that now have all groups disabled (or one enabled)
bool EncounterDefeated (uint32_t encounterID, std::shared_ptr< objects::ActionSpawn > &defeatActionSource)
Determine if an enemy encounter has been defeated and clean up the encounter information for the zone.
const std::list< std::shared_ptr< ActiveEntityState > > GetActiveEntities ()
Get all active entities in the zone.
const std::list< std::shared_ptr< ActiveEntityState > > GetActiveEntitiesInRadius (float x, float y, double radius)
Get all active entities in the zone within a supplied radius.
const std::shared_ptr< ActiveEntityState > GetActiveEntity (int32_t entityID)
Get an active entity in the zone by ID.
std::shared_ptr< objects::EntityStateObject > GetActor (int32_t actorID)
Get an entity instance with a specified actor ID.
std::shared_ptr< BazaarState > GetBazaar (int32_t id)
Get a bazaar instance by it's ID.
const std::list< std::shared_ptr< BazaarState > > GetBazaars () const
Get all bazaar instances in the zone.
std::list< std::shared_ptr< ChannelClientConnection > > GetConnectionList ()
Get all client connections in the zone as a list.
std::unordered_map< int32_t, std::shared_ptr< ChannelClientConnection > > GetConnections ()
Get all client connections in the zone mapped by world CID.
const std::shared_ptr< objects::ServerZone > GetDefinition ()
Get the definition of the zone.
uint32_t GetDefinitionID ()
Get the defintion ID of the zone.
std::set< int32_t > GetDespawnEntities ()
Get the IDs of all entities in the zone marked for despawn.
std::set< uint32_t > GetDisabledSpawnGroups ()
Get all spawn groups in this zone that have been marked as disabled either due to time restrictions or manually.
const std::shared_ptr< DynamicMap > GetDynamicMap () const
Get the dynamic map information bound to the zone.
const std::list< std::shared_ptr< EnemyState > > GetEnemies () const
Get all enemy instances in the zone.
std::shared_ptr< EnemyState > GetEnemy (int32_t id)
Get an enemy instance by it's ID.
std::shared_ptr< objects::EntityStateObject > GetEntity (int32_t id)
Get an entity instance by it's ID.
bool GetFlagState (int32_t key, int32_t &value, int32_t worldCID)
Get the state of a zone flag.
std::unordered_map< int32_t, std::unordered_map< int32_t, int32_t > > GetFlagStates ()
Return the flag states for the zone.
int32_t GetFlagStateValue (int32_t key, int32_t nullDefault, int32_t worldCID)
Get the state of a zone flag, returning the null default if it does not exist.
const std::shared_ptr< ZoneGeometry > GetGeometry () const
Get the geometry information bound to the zone.
uint32_t GetID ()
Get the unique server ID of the zone.
std::shared_ptr< ZoneInstance > GetInstance () const
Get the instance the zone belongs to if on exists.
std::shared_ptr< LootBoxState > GetLootBox (int32_t id)
Get a loot box instance by it's ID.
const std::list< std::shared_ptr< LootBoxState > > GetLootBoxes () const
Get all loot box instances in the zone.
std::shared_ptr< NPCState > GetNPC (int32_t id)
Get an NPC instance by it's ID.
const std::list< std::shared_ptr< NPCState > > GetNPCs () const
Get all NPC instances in the zone.
std::shared_ptr< PlasmaState > GetPlasma (uint32_t id)
Get a plasma instance by it's definition ID.
const std::unordered_map< uint32_t, std::shared_ptr< PlasmaState > > GetPlasma () const
Get all plasma instances in the zone.
std::set< uint32_t > GetRespawnLocations (uint64_t now)
Get the set of spawn location groups that need to be respawned.
std::shared_ptr< ServerObjectState > GetServerObject (int32_t id)
Get an object instance by it's ID.
const std::list< std::shared_ptr< ServerObjectState > > GetServerObjects () const
Get all object instances in the zone.
std::list< std::shared_ptr< ActiveEntityState > > GetUpdatedStatusEffectEntities (uint32_t now)
Get the list of entities that have had registered status effect event times that have passed since the specified time.
bool GroupHasSpawned (uint32_t groupID, bool isLocation, bool aliveOnly)
Check if a spawn group/location group has ever been spawned in this zone or is currently spawned.
bool HasRespawns () const
Check if the zone has respawnable entities associated to it.
void MarkDespawn (int32_t entityID)
Mark an entity for despawn in the zone.
void RemoveConnection (const std::shared_ptr< ChannelClientConnection > &client)
Remove a client connection from the zone and unregister its world CID.
void RemoveEntity (int32_t entityID, uint32_t spawnDelay=0)
Remove an entity from the zone.
void SetDynamicMap (const std::shared_ptr< DynamicMap > &map)
Set the dynamic map information bound to the zone.
void SetFlagState (int32_t key, int32_t value, int32_t worldCID)
Set the state of a zone flag.
void SetGeometry (const std::shared_ptr< ZoneGeometry > &geometry)
Set the geometry information bound to the zone.
void SetInstance (const std::shared_ptr< ZoneInstance > &instance)
Set the instance the zone belongs to.
void SetNextStatusEffectTime (uint32_t time, int32_t entityID)
Set the next status effect event time associated to an entity in the zone.
bool SpawnedAtSpot (uint32_t spotID)
Check if an enemy has ever spawned at the specified spot.
std::unordered_map< size_t, std::shared_ptr< objects::Loot > > TakeLoot (std::shared_ptr< objects::LootBox > lBox, std::set< int8_t > slots, size_t freeSlots, std::unordered_map< uint32_t, uint16_t > stacksFree={})
Take loot out of the specified loot box.
bool UpdateTimedSpawns (const WorldClock &clock)
Update all spawn groups and plasma states that have time restrictions based upon the supplie world clock time.
Private Member Functions
bool DisableSpawnGroups (const std::set< uint32_t > &spawnGroupIDs)
Disable a set of spawn groups and update any spawn location groups that now have all groups disabled.
void EnableSpawnGroups (const std::set< uint32_t > &spawnGroupIDs)
Enable a set of spawn groups and update any spawn location groups that previously had all groups disabled.
void RegisterEntityState (const std::shared_ptr< objects::EntityStateObject > &state)
Register an entity as one that currently exists in the zone.
bool TimeRestrictionActive (const WorldClock &clock, const std::shared_ptr< objects::SpawnRestriction > &restriction)
Determine based on the supplied clock time if a spawn restriction is active or not.
void UnregisterEntityState (int32_t entityID)
Remove an entity that no longer exists in the zone by its ID.
Private Attributes
std::unordered_map< int32_t, std::shared_ptr< objects::EntityStateObject > > mActors
Map of entities in the zone with a specified actor ID for used when referencing in actions or events.
std::unordered_map< int32_t, std::shared_ptr< objects::EntityStateObject > > mAllEntities
Map of entities in the zone by their ID.
std::list< std::shared_ptr< BazaarState > > mBazaars
List of pointers to bazaars instantiated for the zone.
std::unordered_map< uint32_t, std::set< int32_t > > mBossBoxGroups
Map of boss box group IDs to the boxes included.
std::unordered_map< uint32_t, std::set< int32_t > > mBossBoxOwners
Map of boss box group IDs to entities that have claimed part of the group.
std::unordered_map< int32_t, std::shared_ptr< ChannelClientConnection > > mConnections
Map of world CIDs to client connections.
std::set< uint32_t > mDisabledSpawnGroups
Set of spawn group IDs that have been disabled.
std::set< uint32_t > mDisabledSpawnLocationGroups
Set of spawn location group IDs where all associated groups are disabled.
std::shared_ptr< DynamicMap > mDynamicMap
Dynamic map information bound to the zone.
std::unordered_map< uint32_t, std::set< std::shared_ptr< EnemyState > > > mEncounters
Map of encounter IDs to enemies that belong to that encounter.
std::unordered_map< uint32_t, std::shared_ptr< objects::ActionSpawn > > mEncounterSpawnSources
Map of encounter IDs to spawn actions that created the encounter.
std::list< std::shared_ptr< EnemyState > > mEnemies
List of pointers to enemies instantiated for the zone.
std::unordered_map< int32_t, std::unordered_map< int32_t, int32_t > > mFlagStates
General use flags and associated values used for event sequences etc keyed on 0 for all characters or world CID if for a specific one.
std::shared_ptr< ZoneGeometry > mGeometry
Geometry information bound to the zone.
bool mHasRespawns
Quick reference flag to determine if the zone has respwa.
uint32_t mID
Unique server ID of the zone.
std::mutex mLock
Server lock for shared resources.
std::list< std::shared_ptr< LootBoxState > > mLootBoxes
List of pointers to lootable boxes for the zone.
uint32_t mNextEncounterID
Next ID to use for encounters registered for the zone.
std::map< uint32_t, std::set< int32_t > > mNextEntityStatusTimes
Map of system times to active entities with status effects that need handling at that time.
std::list< std::shared_ptr< NPCState > > mNPCs
List of pointers to NPCs instantiated for the zone.
std::list< std::shared_ptr< ServerObjectState > > mObjects
List of pointers to objects instantiated for the zone.
std::set< int32_t > mPendingDespawnEntities
Set of entity IDs waiting to despawn.
std::unordered_map< uint32_t, std::shared_ptr< PlasmaState > > mPlasma
Map of plasma states by definition ID.
std::map< uint64_t, std::set< uint32_t > > mRespawnTimes
Map of server times to spawn location group IDs that need to be respawned at that time.
std::shared_ptr< objects::ServerZone > mServerZone
Pointer to the ServerZone definition.
std::unordered_map< uint32_t, std::list< std::shared_ptr< EnemyState > > > mSpawnGroups
Map of spawn group IDs to pointers to enemies created from that group.
std::unordered_map< uint32_t, std::list< std::shared_ptr< EnemyState > > > mSpawnLocationGroups
Map of spawn location group IDs to pointers to enemies created from the groups.
std::set< uint32_t > mSpotsSpawned
Set of all spot IDs that have had an enemy spawned.
std::shared_ptr< ZoneInstance > mZoneInstance
Zone instance pointer for non-global zones.
Detailed Description
Represents a server zone containing client connections, objects, enemies, etc.
Definition at line 68 of file Zone.h.
Constructor & Destructor Documentation
Zone::Zone ()
Create a new zone.
While not useful this constructor is necessary for the script bindings.
Definition at line 78 of file Zone.cpp.
Zone::Zone (uint32_t id, const std::shared_ptr< objects::ServerZone > & definition)
Create a new zone.
Parameters
id Unique server ID of the zone
definition Pointer to the ServerZone definition
Definition at line 82 of file Zone.cpp.
References DisableSpawnGroups(), and mHasRespawns.
Zone::Zone (const Zone & other)
Explicitly defined copy constructor necessary due to removal of implicit constructor from non-copyable mutex member.
This should never actually be used.
Parameters
other The other zone to copy
Definition at line 117 of file Zone.cpp.
Zone::~Zone ()
Clean up the zone.
Definition at line 122 of file Zone.cpp.
Member Function Documentation
void Zone::AddBazaar (const std::shared_ptr< BazaarState > & bazaar)
Add a bazaar to the zone.
Parameters
bazaar Pointer to the bazaar to add
Definition at line 327 of file Zone.cpp.
References mBazaars, and RegisterEntityState().
void Zone::AddConnection (const std::shared_ptr< ChannelClientConnection > & client)
Add a client connection to the zone and register its world CID.
Parameters
client Pointer to a client connection to add
Definition at line 171 of file Zone.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetWorldCID(), mConnections, mLock, RegisterEntityState(), and channel::state().
void Zone::AddEnemy (const std::shared_ptr< EnemyState > & enemy)
Add an enemy to the zone.
Parameters
enemy Pointer to the enemy to add
Definition at line 333 of file Zone.cpp.
References mEnemies, mLock, mRespawnTimes, mServerZone, mSpawnGroups, mSpawnLocationGroups, mSpotsSpawned, and RegisterEntityState().
Referenced by CreateEncounter().
void Zone::AddLootBox (const std::shared_ptr< LootBoxState > & box, uint32_t bossGroupID = 0)
Add a loot body to the zone.
Parameters
box Pointer to the loot box to add
bossGroupID Optional ID of the group to bind looting to for boss boxes
Definition at line 373 of file Zone.cpp.
References mBossBoxGroups, mLock, mLootBoxes, and RegisterEntityState().
void Zone::AddNPC (const std::shared_ptr< NPCState > & npc)
Add an NPC to the zone.
Parameters
npc Pointer to the NPC to add
Definition at line 389 of file Zone.cpp.
References mActors, mNPCs, and RegisterEntityState().
void Zone::AddObject (const std::shared_ptr< ServerObjectState > & object)
Add an object to the zone.
Parameters
object Pointer to the object to add
Definition at line 401 of file Zone.cpp.
References mActors, mObjects, and RegisterEntityState().
void Zone::AddPlasma (const std::shared_ptr< PlasmaState > & plasma)
Add a plasma grouping to the zone.
Parameters
object Pointer to the plasma to add
Definition at line 413 of file Zone.cpp.
References mPlasma, and RegisterEntityState().
bool Zone::ClaimBossBox (int32_t id, int32_t looterID)
Mark a boss box as belonging to the specified entity if the box is not already claimed and the entity has not already claimed the box.
Parameters
id Instance ID of the boss box.
looterID ID of the entity claiming the box
Returns
true if the box was claimed, false if it was not
Definition at line 508 of file Zone.cpp.
References GetLootBox(), mBossBoxGroups, mBossBoxOwners, and mLock.
void Zone::Cleanup ()
Perform pre-deletion cleanup actions.
Definition at line 972 of file Zone.cpp.
References mAllEntities, mEnemies, mLock, mNPCs, mObjects, mSpawnGroups, mSpawnLocationGroups, mZoneInstance, and channel::ActiveEntityState::SetZone().
void Zone::CreateEncounter (const std::list< std::shared_ptr< EnemyState >> & enemies, std::shared_ptr< objects::ActionSpawn > spawnSource = nullptr)
Create an encounter from a group of enemies and register them with the zone.
Encounter information will be retained until a check via EncounterDefeated is called.
Parameters
enemies List of the enemies to add to the encounter
spawnSource Optional pointer to spawn action that created the encounter. If this is specified, it will be returned as the defeatActionSource when calling EncounterDefeated
Definition at line 698 of file Zone.cpp.
References AddEnemy(), mEncounters, mEncounterSpawnSources, mLock, and mNextEncounterID.
bool Zone::DisableSpawnGroups (const std::set< uint32_t > & spawnGroupIDs) private
Disable a set of spawn groups and update any spawn location groups that now have all groups disabled.
Parameters
spawnGroupIDs Set of spawn group IDs to disable
Definition at line 1157 of file Zone.cpp.
References mDisabledSpawnGroups, mDisabledSpawnLocationGroups, mPendingDespawnEntities, mRespawnTimes, mServerZone, and mSpawnGroups.
Referenced by EnableDisableSpawnGroups(), UpdateTimedSpawns(), and Zone().
bool Zone::EnableDisableSpawnGroups (const std::set< uint32_t > & spawnGroupIDs, bool enable)
Enable or disable the supplied spawn groups and also disable (or enable) any spawn location groups that now have all groups disabled (or one enabled)
Parameters
spawnGroupIDs Set of spawn group IDs to adjust
enable true if the group should be enabled, false if it should be disabled
Returns
true if any updates were performed that the zone manager needs to react to, false if none occurred or they can be processed later
Definition at line 835 of file Zone.cpp.
References DisableSpawnGroups(), EnableSpawnGroups(), and mLock.
void Zone::EnableSpawnGroups (const std::set< uint32_t > & spawnGroupIDs) private
Enable a set of spawn groups and update any spawn location groups that previously had all groups disabled.
Parameters
spawnGroupIDs Set of spawn group IDs to enable
Definition at line 1109 of file Zone.cpp.
References channel::ChannelServer::GetServerTime(), mDisabledSpawnGroups, mDisabledSpawnLocationGroups, mRespawnTimes, and mServerZone.
Referenced by EnableDisableSpawnGroups(), and UpdateTimedSpawns().
bool Zone::EncounterDefeated (uint32_t encounterID, std::shared_ptr< objects::ActionSpawn > & defeatActionSource)
Determine if an enemy encounter has been defeated and clean up the encounter information for the zone.
Parameters
encounterID ID of the encounter
defeatActionSource Output parameter to contain the original spawn action source that can contain defeat actions to execute
Returns
true if the encounter has been defeated, false if at least one enemy from the group is still alive
Definition at line 724 of file Zone.cpp.
References mEncounters, mEncounterSpawnSources, and mLock.
const std::list< std::shared_ptr< ActiveEntityState > > Zone::GetActiveEntities ()
Get all active entities in the zone.
Returns
List of pointers to all active entities
Definition at line 441 of file Zone.cpp.
References mAllEntities, and mLock.
const std::list< std::shared_ptr< ActiveEntityState > > Zone::GetActiveEntitiesInRadius (float x, float y, double radius)
Get all active entities in the zone within a supplied radius.
Parameters
x X coordinate of the center of the radius
y Y coordinate of the center of the radius
radius Radius to check for entities
Returns
List of pointers to active entities in the radius
Definition at line 459 of file Zone.cpp.
References mAllEntities, and mLock.
const std::shared_ptr< ActiveEntityState > Zone::GetActiveEntity (int32_t entityID)
Get an active entity in the zone by ID.
Parameters
entityID ID of the active entity to retrieve
Returns
Pointer to the active entity or null if does not exist or is not active
Definition at line 436 of file Zone.cpp.
References GetEntity().
std::shared_ptr< objects::EntityStateObject > Zone::GetActor (int32_t actorID)
Get an entity instance with a specified actor ID.
Parameters
actorID Actor ID of the entity.
Returns
Pointer to the entity instance.
Definition at line 601 of file Zone.cpp.
References mActors.
std::shared_ptr< BazaarState > Zone::GetBazaar (int32_t id)
Get a bazaar instance by it's ID.
Parameters
id Instance ID of the bazaar.
Returns
Pointer to the bazaar instance.
Definition at line 478 of file Zone.cpp.
References GetEntity().
const std::list< std::shared_ptr< BazaarState > > Zone::GetBazaars () const
Get all bazaar instances in the zone.
Returns
List of all bazaar instances in the zone
Definition at line 483 of file Zone.cpp.
References mBazaars.
std::list< std::shared_ptr< ChannelClientConnection > > Zone::GetConnectionList ()
Get all client connections in the zone as a list.
Returns
List of all client connections in the zone
Definition at line 425 of file Zone.cpp.
References mConnections, and mLock.
std::unordered_map< int32_t, std::shared_ptr< ChannelClientConnection > > Zone::GetConnections ()
Get all client connections in the zone mapped by world CID.
Returns
Map of all client connections in the zone by world CID
Definition at line 420 of file Zone.cpp.
References mConnections.
const std::shared_ptr< objects::ServerZone > Zone::GetDefinition ()
Get the definition of the zone.
Returns
Pointer to the definition of the zone
Definition at line 570 of file Zone.cpp.
References mServerZone.
uint32_t Zone::GetDefinitionID ()
Get the defintion ID of the zone.
Returns
Defintion ID of the zone
Definition at line 131 of file Zone.cpp.
References mServerZone.
std::set< int32_t > Zone::GetDespawnEntities ()
Get the IDs of all entities in the zone marked for despawn.
Returns
Set of all entity IDs to despawn
Definition at line 758 of file Zone.cpp.
References mLock, and mPendingDespawnEntities.
std::set< uint32_t > Zone::GetDisabledSpawnGroups ()
Get all spawn groups in this zone that have been marked as disabled either due to time restrictions or manually.
Returns
Set of disabled spawn group IDs
Definition at line 764 of file Zone.cpp.
References mDisabledSpawnGroups, and mLock.
const std::shared_ptr< DynamicMap > Zone::GetDynamicMap () const
Get the dynamic map information bound to the zone.
Returns
Dynamic map information bound to the zone
Definition at line 156 of file Zone.cpp.
References mDynamicMap.
const std::list< std::shared_ptr< EnemyState > > Zone::GetEnemies () const
Get all enemy instances in the zone.
Returns
List of all enemy instances in the zone
Definition at line 493 of file Zone.cpp.
References mEnemies.
std::shared_ptr< EnemyState > Zone::GetEnemy (int32_t id)
Get an enemy instance by it's ID.
Parameters
id Instance ID of the enemy.
Returns
Pointer to the enemy instance.
Definition at line 488 of file Zone.cpp.
References GetEntity().
std::shared_ptr< objects::EntityStateObject > Zone::GetEntity (int32_t id)
Get an entity instance by it's ID.
Parameters
id Instance ID of the entity.
Returns
Pointer to the entity instance.
Definition at line 588 of file Zone.cpp.
References mAllEntities, and mLock.
Referenced by GetActiveEntity(), GetBazaar(), GetEnemy(), GetLootBox(), GetNPC(), GetServerObject(), and RemoveEntity().
bool Zone::GetFlagState (int32_t key, int32_t & value, int32_t worldCID)
Get the state of a zone flag.
Parameters
key Lookup key for the flag
value Output value for the flag if it exists
worldCID CID of the character the flag belongs to, 0 if it affects the entire instance
Returns
true if the flag exists, false if it does not
Definition at line 882 of file Zone.cpp.
References mFlagStates, and mLock.
Referenced by GetFlagStateValue().
std::unordered_map< int32_t, std::unordered_map< int32_t, int32_t > > Zone::GetFlagStates ()
Return the flag states for the zone.
Returns
Flag states for the zone.
Definition at line 905 of file Zone.cpp.
References mFlagStates, and mLock.
int32_t Zone::GetFlagStateValue (int32_t key, int32_t nullDefault, int32_t worldCID)
Get the state of a zone flag, returning the null default if it does not exist.
Parameters
key Lookup key for the flag
nullDefault Default value to return if the flag is not set
worldCID CID of the character the flag belongs to, 0 if it affects the entire instance
Returns
Value of the specified flag or the nullDefault value if it does not exist
Definition at line 912 of file Zone.cpp.
References GetFlagState().
const std::shared_ptr< ZoneGeometry > Zone::GetGeometry () const
Get the geometry information bound to the zone.
Returns
Geometry information bound to the zone
Definition at line 136 of file Zone.cpp.
References mGeometry.
uint32_t Zone::GetID ()
Get the unique server ID of the zone.
Returns
Unique server ID of the zone
Definition at line 126 of file Zone.cpp.
References mID.
std::shared_ptr< ZoneInstance > Zone::GetInstance () const
Get the instance the zone belongs to if on exists.
Returns
Instance the zone belongs to
Definition at line 146 of file Zone.cpp.
References mZoneInstance.
std::shared_ptr< LootBoxState > Zone::GetLootBox (int32_t id)
Get a loot box instance by it's ID.
Parameters
id Instance ID of the loot box.
Returns
Pointer to the loot box instance.
Definition at line 498 of file Zone.cpp.
References GetEntity().
Referenced by ClaimBossBox().
const std::list< std::shared_ptr< LootBoxState > > Zone::GetLootBoxes () const
Get all loot box instances in the zone.
Returns
List of all loot box instances in the zone
Definition at line 503 of file Zone.cpp.
References mLootBoxes.
std::shared_ptr< NPCState > Zone::GetNPC (int32_t id)
Get an NPC instance by it's ID.
Parameters
id Instance ID of the NPC.
Returns
Pointer to the NPC instance.
Definition at line 607 of file Zone.cpp.
References GetEntity().
const std::list< std::shared_ptr< NPCState > > Zone::GetNPCs () const
Get all NPC instances in the zone.
Returns
List of all NPC instances in the zone
Definition at line 548 of file Zone.cpp.
References mNPCs.
std::shared_ptr< PlasmaState > Zone::GetPlasma (uint32_t id)
Get a plasma instance by it's definition ID.
Parameters
id Definition ID of the plasma.
Returns
Pointer to the plasma instance.
Definition at line 553 of file Zone.cpp.
References mPlasma.
const std::unordered_map< uint32_t, std::shared_ptr< PlasmaState > > Zone::GetPlasma () const
Get all plasma instances in the zone.
Returns
List of all plasma instances in the zone
Definition at line 560 of file Zone.cpp.
References mPlasma.
std::set< uint32_t > Zone::GetRespawnLocations (uint64_t now)
Get the set of spawn location groups that need to be respawned.
Parameters
now System time representing the current server time
Returns
Set of spawn location group IDs to respawn
Definition at line 850 of file Zone.cpp.
References mLock, mRespawnTimes, and mSpawnLocationGroups.
std::shared_ptr< ServerObjectState > Zone::GetServerObject (int32_t id)
Get an object instance by it's ID.
Parameters
id Instance ID of the object.
Returns
Pointer to the object instance.
Definition at line 612 of file Zone.cpp.
References GetEntity().
const std::list< std::shared_ptr< ServerObjectState > > Zone::GetServerObjects () const
Get all object instances in the zone.
Returns
List of all object instances in the zone
Definition at line 565 of file Zone.cpp.
References mObjects.
std::list< std::shared_ptr< ActiveEntityState > > Zone::GetUpdatedStatusEffectEntities (uint32_t now)
Get the list of entities that have had registered status effect event times that have passed since the specified time.
Parameters
now System time representing the current server time
Returns
List of entities that have had registered status effect event times that have passed
Definition at line 634 of file Zone.cpp.
References mAllEntities, mLock, and mNextEntityStatusTimes.
bool Zone::GroupHasSpawned (uint32_t groupID, bool isLocation, bool aliveOnly)
Check if a spawn group/location group has ever been spawned in this zone or is currently spawned.
Parameters
groupID Group ID of the spawn to check
aliveOnly Only count living entities in the group
Returns
true if the group has already been spawned or contains, a living enemy, false otherwise
Definition at line 666 of file Zone.cpp.
References mLock, mSpawnGroups, and mSpawnLocationGroups.
bool Zone::HasRespawns () const
Check if the zone has respawnable entities associated to it.
Returns
true if the zone has respawnable entities associated to it
Definition at line 161 of file Zone.cpp.
References mHasRespawns.
void Zone::MarkDespawn (int32_t entityID)
Mark an entity for despawn in the zone.
Once marked, it cannot be unmarked.
Parameters
entityID ID of the entity to mark for despawn
Definition at line 770 of file Zone.cpp.
References mAllEntities, mLock, and mPendingDespawnEntities.
void Zone::RegisterEntityState (const std::shared_ptr< objects::EntityStateObject > & state) private
Register an entity as one that currently exists in the zone.
Parameters
state Pointer to an entity state in the zone
Definition at line 575 of file Zone.cpp.
References mAllEntities, mLock, and channel::state().
Referenced by AddBazaar(), AddConnection(), AddEnemy(), AddLootBox(), AddNPC(), AddObject(), and AddPlasma().
void Zone::RemoveConnection (const std::shared_ptr< ChannelClientConnection > & client)
Remove a client connection from the zone and unregister its world CID.
Parameters
client Pointer to a client connection to remove
Definition at line 184 of file Zone.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetWorldCID(), mConnections, mFlagStates, mLock, mZoneInstance, channel::state(), and UnregisterEntityState().
void Zone::RemoveEntity (int32_t entityID, uint32_t spawnDelay = 0)
Remove an entity from the zone.
For player entities, use RemoveConnection instead.
Parameters
entityID ID of the entity to remove
spawnDelay Optional parameter to update spawn groups with a timed delay (in seconds) instead of right away, should the group be empty after the change
Definition at line 211 of file Zone.cpp.
References GetEntity(), channel::ChannelServer::GetServerTime(), mBossBoxGroups, mBossBoxOwners, mEncounters, mEnemies, mLock, mLootBoxes, mRespawnTimes, mServerZone, mSpawnGroups, mSpawnLocationGroups, channel::state(), and UnregisterEntityState().
void Zone::SetDynamicMap (const std::shared_ptr< DynamicMap > & map)
Set the dynamic map information bound to the zone.
Parameters
map Dynamic maps information bound to the zone
Definition at line 166 of file Zone.cpp.
References mDynamicMap.
void Zone::SetFlagState (int32_t key, int32_t value, int32_t worldCID)
Set the state of a zone flag.
Parameters
key Lookup key for the flag
value Value to set for the flag
worldCID CID of the character the flag belongs to, 0 if it affects the entire instance
Definition at line 924 of file Zone.cpp.
References mFlagStates, and mLock.
void Zone::SetGeometry (const std::shared_ptr< ZoneGeometry > & geometry)
Set the geometry information bound to the zone.
Parameters
geometry Geometry information bound to the zone
Definition at line 141 of file Zone.cpp.
References mGeometry.
void Zone::SetInstance (const std::shared_ptr< ZoneInstance > & instance)
Set the instance the zone belongs to.
Parameters
instance Instance the zone belongs to
Definition at line 151 of file Zone.cpp.
References mZoneInstance.
void Zone::SetNextStatusEffectTime (uint32_t time, int32_t entityID)
Set the next status effect event time associated to an entity in the zone.
Parameters
time Time of the next status effect event time
entityID ID of the entity with a status effect event at the specified time
Definition at line 617 of file Zone.cpp.
References mLock, and mNextEntityStatusTimes.
bool Zone::SpawnedAtSpot (uint32_t spotID)
Check if an enemy has ever spawned at the specified spot.
Parameters
spotID Spot ID of the spawn to check
Returns
true if an enemy has ever spawned at the spot
Definition at line 692 of file Zone.cpp.
References mLock, and mSpotsSpawned.
std::unordered_map< size_t, std::shared_ptr< objects::Loot > > Zone::TakeLoot (std::shared_ptr< objects::LootBox > lBox, std::set< int8_t > slots, size_t freeSlots, std::unordered_map< uint32_t, uint16_t > stacksFree = {})
Take loot out of the specified loot box.
This should be the only way loot is removed from a box as it uses a mutex lock to ensure that the loot is not duplicated for two different people. This currently does NOT support splitting stacks within the loot box when the box being moved to becomes full.
Parameters
lBox Pointer to the loot box
slots Loot slots being requested or empty to request all
freeSlots Contextual number of free slots signifying how many loot items can be taken
stacksFree Contextual number of free stack slots used when determining how many items can be taken
Returns
Map of slot IDs to the loot taken
Definition at line 931 of file Zone.cpp.
References mLock.
bool Zone::TimeRestrictionActive (const WorldClock & clock, const std::shared_ptr< objects::SpawnRestriction > & restriction) private
Determine based on the supplied clock time if a spawn restriction is active or not.
Parameters
clock World clock set to the current time
restriction Pointer to the spawn restriction to evaluate
Returns
true if the current time is valid for the restriction, false if it is not
Definition at line 994 of file Zone.cpp.
References channel::WorldClock::Day, channel::WorldClockTime::Hour, channel::WorldClockTime::Min, channel::WorldClock::Month, channel::WorldClockTime::MoonPhase, channel::WorldClockTime::SystemHour, channel::WorldClockTime::SystemMin, and channel::WorldClock::WeekDay.
Referenced by UpdateTimedSpawns().
void Zone::UnregisterEntityState (int32_t entityID) private
Remove an entity that no longer exists in the zone by its ID.
Parameters
entityID ID of an entity to remove
Definition at line 581 of file Zone.cpp.
References mAllEntities, mLock, and mPendingDespawnEntities.
Referenced by RemoveConnection(), and RemoveEntity().
bool Zone::UpdateTimedSpawns (const WorldClock & clock)
Update all spawn groups and plasma states that have time restrictions based upon the supplie world clock time.
Parameters
clock World clock set to the current time
Returns
true if any updates were performed that the zone manager needs to react to, false if none occurred or they can be processed later
Todo:
Todo:
Definition at line 779 of file Zone.cpp.
References DisableSpawnGroups(), EnableSpawnGroups(), mLock, mServerZone, and TimeRestrictionActive().
Member Data Documentation
std::unordered_map<int32_t, std::shared_ptr<objects::EntityStateObject> > channel::Zone::mActors private
Map of entities in the zone with a specified actor ID for used when referencing in actions or events.
Definition at line 620 of file Zone.h.
Referenced by AddNPC(), AddObject(), and GetActor().
std::unordered_map<int32_t, std::shared_ptr<objects::EntityStateObject> > channel::Zone::mAllEntities private
Map of entities in the zone by their ID.
Definition at line 616 of file Zone.h.
Referenced by Cleanup(), GetActiveEntities(), GetActiveEntitiesInRadius(), GetEntity(), GetUpdatedStatusEffectEntities(), MarkDespawn(), RegisterEntityState(), and UnregisterEntityState().
std::list<std::shared_ptr<BazaarState> > channel::Zone::mBazaars private
List of pointers to bazaars instantiated for the zone.
Definition at line 574 of file Zone.h.
Referenced by AddBazaar(), and GetBazaars().
std::unordered_map<uint32_t, std::set<int32_t> > channel::Zone::mBossBoxGroups private
Map of boss box group IDs to the boxes included.
Definition at line 607 of file Zone.h.
Referenced by AddLootBox(), ClaimBossBox(), and RemoveEntity().
std::unordered_map<uint32_t, std::set<int32_t> > channel::Zone::mBossBoxOwners private
Map of boss box group IDs to entities that have claimed part of the group.
Definition at line 610 of file Zone.h.
Referenced by ClaimBossBox(), and RemoveEntity().
std::unordered_map<int32_t, std::shared_ptr<ChannelClientConnection> > channel::Zone::mConnections private
Map of world CIDs to client connections.
Definition at line 571 of file Zone.h.
Referenced by AddConnection(), GetConnectionList(), GetConnections(), and RemoveConnection().
std::set<uint32_t> channel::Zone::mDisabledSpawnGroups private
Set of spawn group IDs that have been disabled.
Definition at line 635 of file Zone.h.
Referenced by DisableSpawnGroups(), EnableSpawnGroups(), and GetDisabledSpawnGroups().
std::set<uint32_t> channel::Zone::mDisabledSpawnLocationGroups private
Set of spawn location group IDs where all associated groups are disabled.
Definition at line 638 of file Zone.h.
Referenced by DisableSpawnGroups(), and EnableSpawnGroups().
std::shared_ptr<DynamicMap> channel::Zone::mDynamicMap private
Dynamic map information bound to the zone.
Definition at line 648 of file Zone.h.
Referenced by GetDynamicMap(), and SetDynamicMap().
std::unordered_map<uint32_t, std::set<std::shared_ptr<EnemyState> > > channel::Zone::mEncounters private
Map of encounter IDs to enemies that belong to that encounter.
Definition at line 588 of file Zone.h.
Referenced by CreateEncounter(), EncounterDefeated(), and RemoveEntity().
std::unordered_map<uint32_t, std::shared_ptr<objects::ActionSpawn> > channel::Zone::mEncounterSpawnSources private
Map of encounter IDs to spawn actions that created the encounter.
Definition at line 592 of file Zone.h.
Referenced by CreateEncounter(), and EncounterDefeated().
std::list<std::shared_ptr<EnemyState> > channel::Zone::mEnemies private
List of pointers to enemies instantiated for the zone.
Definition at line 577 of file Zone.h.
Referenced by AddEnemy(), Cleanup(), GetEnemies(), and RemoveEntity().
std::unordered_map<int32_t, std::unordered_map<int32_t, int32_t> > channel::Zone::mFlagStates private
General use flags and associated values used for event sequences etc keyed on 0 for all characters or world CID if for a specific one.
Definition at line 642 of file Zone.h.
Referenced by GetFlagState(), GetFlagStates(), RemoveConnection(), and SetFlagState().
std::shared_ptr<ZoneGeometry> channel::Zone::mGeometry private
Geometry information bound to the zone.
Definition at line 645 of file Zone.h.
Referenced by GetGeometry(), and SetGeometry().
bool channel::Zone::mHasRespawns private
Quick reference flag to determine if the zone has respwa.
Definition at line 660 of file Zone.h.
Referenced by HasRespawns(), and Zone().
uint32_t channel::Zone::mID private
Unique server ID of the zone.
Definition at line 654 of file Zone.h.
Referenced by GetID().
std::mutex channel::Zone::mLock private
Server lock for shared resources.
Definition at line 663 of file Zone.h.
Referenced by AddConnection(), AddEnemy(), AddLootBox(), ClaimBossBox(), Cleanup(), CreateEncounter(), EnableDisableSpawnGroups(), EncounterDefeated(), GetActiveEntities(), GetActiveEntitiesInRadius(), GetConnectionList(), GetDespawnEntities(), GetDisabledSpawnGroups(), GetEntity(), GetFlagState(), GetFlagStates(), GetRespawnLocations(), GetUpdatedStatusEffectEntities(), GroupHasSpawned(), MarkDespawn(), RegisterEntityState(), RemoveConnection(), RemoveEntity(), SetFlagState(), SetNextStatusEffectTime(), SpawnedAtSpot(), TakeLoot(), UnregisterEntityState(), and UpdateTimedSpawns().
std::list<std::shared_ptr<LootBoxState> > channel::Zone::mLootBoxes private
List of pointers to lootable boxes for the zone.
Definition at line 604 of file Zone.h.
Referenced by AddLootBox(), GetLootBoxes(), and RemoveEntity().
uint32_t channel::Zone::mNextEncounterID private
Next ID to use for encounters registered for the zone.
Definition at line 657 of file Zone.h.
Referenced by CreateEncounter().
std::map<uint32_t, std::set<int32_t> > channel::Zone::mNextEntityStatusTimes private
Map of system times to active entities with status effects that need handling at that time.
Definition at line 624 of file Zone.h.
Referenced by GetUpdatedStatusEffectEntities(), and SetNextStatusEffectTime().
std::list<std::shared_ptr<NPCState> > channel::Zone::mNPCs private
List of pointers to NPCs instantiated for the zone.
Definition at line 598 of file Zone.h.
Referenced by AddNPC(), Cleanup(), and GetNPCs().
std::list<std::shared_ptr<ServerObjectState> > channel::Zone::mObjects private
List of pointers to objects instantiated for the zone.
Definition at line 601 of file Zone.h.
Referenced by AddObject(), Cleanup(), and GetServerObjects().
std::set<int32_t> channel::Zone::mPendingDespawnEntities private
Set of entity IDs waiting to despawn.
IDs are removed from this set when the entity is removed from the zone.
Definition at line 632 of file Zone.h.
Referenced by DisableSpawnGroups(), GetDespawnEntities(), MarkDespawn(), and UnregisterEntityState().
std::unordered_map<uint32_t, std::shared_ptr<PlasmaState> > channel::Zone::mPlasma private
Map of plasma states by definition ID.
Definition at line 613 of file Zone.h.
Referenced by AddPlasma(), and GetPlasma().
std::map<uint64_t, std::set<uint32_t> > channel::Zone::mRespawnTimes private
Map of server times to spawn location group IDs that need to be respawned at that time.
Definition at line 628 of file Zone.h.
Referenced by AddEnemy(), DisableSpawnGroups(), EnableSpawnGroups(), GetRespawnLocations(), and RemoveEntity().
std::shared_ptr<objects::ServerZone> channel::Zone::mServerZone private
Pointer to the ServerZone definition.
Definition at line 568 of file Zone.h.
Referenced by AddEnemy(), DisableSpawnGroups(), EnableSpawnGroups(), GetDefinition(), GetDefinitionID(), RemoveEntity(), and UpdateTimedSpawns().
std::unordered_map<uint32_t, std::list<std::shared_ptr<EnemyState> > > channel::Zone::mSpawnGroups private
Map of spawn group IDs to pointers to enemies created from that group.
Keys are never removed from this group so one time spawns can be checked.
Definition at line 581 of file Zone.h.
Referenced by AddEnemy(), Cleanup(), DisableSpawnGroups(), GroupHasSpawned(), and RemoveEntity().
std::unordered_map<uint32_t, std::list<std::shared_ptr<EnemyState> > > channel::Zone::mSpawnLocationGroups private
Map of spawn location group IDs to pointers to enemies created from the groups.
Keys are never removed from this group so one time spawns can be checked.
Definition at line 585 of file Zone.h.
Referenced by AddEnemy(), Cleanup(), GetRespawnLocations(), GroupHasSpawned(), and RemoveEntity().
std::set<uint32_t> channel::Zone::mSpotsSpawned private
Set of all spot IDs that have had an enemy spawned.
Definition at line 595 of file Zone.h.
Referenced by AddEnemy(), and SpawnedAtSpot().
std::shared_ptr<ZoneInstance> channel::Zone::mZoneInstance private
Zone instance pointer for non-global zones.
Definition at line 651 of file Zone.h.
Referenced by Cleanup(), GetInstance(), RemoveConnection(), and SetInstance().
The documentation for this class was generated from the following files:
Zone.h
Zone.cpp