COMP_hack: channel::ZoneInstance Class Reference
channel::ZoneInstance Class Reference
Represents an instance of a zone instance containing one or more non-global zone instances.
#include <ZoneInstance.h>
Public Member Functions
ZoneInstance (uint32_t id, const std::shared_ptr< objects::ServerZoneInstance > &definition, const std::shared_ptr< objects::InstanceAccess > &access)
Create a new zone instance.
~ZoneInstance ()
Clean up the zone instance.
bool AddZone (const std::shared_ptr< Zone > &zone)
Add a zone to the instance.
std::list< std::shared_ptr< ChannelClientConnection > > GetConnections ()
Get all client connections in all zones in the instance.
uint32_t GetDefinitionID ()
Get the defintion ID of the zone instance.
std::shared_ptr< objects::DestinyBox > GetDestinyBox (int32_t worldCID)
Get the destiny box the supplied world CID character has access to which can be an individual or shared box.
bool GetFlagState (int32_t key, int32_t &value, int32_t worldCID)
Get the state of a zone instance flag.
std::unordered_map< int32_t, std::unordered_map< int32_t, int32_t > > GetFlagStates ()
Return the flag states for the zone.
int32_t GetFlagStateValue (int32_t key, int32_t nullDefault, int32_t worldCID)
Get the state of a zone instance flag, returning the null default if it does not exist.
std::shared_ptr< Zone > GetZone (uint32_t zoneID, uint32_t dynamicMapID)
Get a zone in the instance by zone ID and dynamic map ID.
std::shared_ptr< Zone > GetZone (uint32_t uniqueID)
Get a zone in the instance by its unique ID.
std::list< std::shared_ptr< Zone > > GetZones ()
Get all zones in the instance.
void RefreshPlayerState ()
Refresh properties calculated dependent upon the players currently in the instance.
void SetFlagState (int32_t key, int32_t value, int32_t worldCID)
Set the state of a zone instance flag.
std::unordered_map< uint8_t, std::shared_ptr< objects::Loot > > UpdateDestinyBox (int32_t worldCID, uint8_t &newNext, const std::list< std::shared_ptr< objects::Loot >> &add, const std::set< uint8_t > &remove)
Update the loot assigned to the destiny box assigned to a specific world CID.
Private Attributes
std::unordered_map< int32_t, std::unordered_map< int32_t, int32_t > > mFlagStates
General use flags and associated values used for event sequences etc keyed on 0 for all characters or world CID if for a specific one.
std::mutex mLock
Server lock for shared resources.
std::unordered_map< uint32_t, std::unordered_map< uint32_t, std::shared_ptr< Zone > > > mZones
Map of zones in the instance by zone ID and dynamic map ID.
Detailed Description
Represents an instance of a zone instance containing one or more non-global zone instances.
Definition at line 50 of file ZoneInstance.h.
Constructor & Destructor Documentation
ZoneInstance()
ZoneInstance::ZoneInstance (uint32_t id, const std::shared_ptr< objects::ServerZoneInstance > & definition, const std::shared_ptr< objects::InstanceAccess > & access)
Create a new zone instance.
Parameters
id Unique server ID of the zone instance
definition Pointer to the ServerZoneInstance definition
access Access definition for the instance
Definition at line 70 of file ZoneInstance.cpp.
~ZoneInstance()
ZoneInstance::~ZoneInstance ()
Clean up the zone instance.
Definition at line 84 of file ZoneInstance.cpp.
References LOG_DEBUG.
Member Function Documentation
AddZone()
bool ZoneInstance::AddZone (const std::shared_ptr< Zone > & zone)
Add a zone to the instance.
Parameters
Pointer to the zone to add
Returns
true if the zone was successfully added, false if it was not
Definition at line 98 of file ZoneInstance.cpp.
References mLock, and mZones.
GetConnections()
std::list< std::shared_ptr< ChannelClientConnection > > ZoneInstance::GetConnections ()
Get all client connections in all zones in the instance.
Returns
List of all client connections in the instance
Definition at line 171 of file ZoneInstance.cpp.
References GetZones().
Referenced by RefreshPlayerState().
GetDefinitionID()
uint32_t ZoneInstance::GetDefinitionID ()
Get the defintion ID of the zone instance.
Returns
Defintion ID of the zone instance
Definition at line 93 of file ZoneInstance.cpp.
GetDestinyBox()
std::shared_ptr< objects::DestinyBox > ZoneInstance::GetDestinyBox (int32_t worldCID)
Get the destiny box the supplied world CID character has access to which can be an individual or shared box.
Parameters
worldCID World CID of the character who has access to the box
Returns
Pointer to the destiny box the character has access to or null if none exists
Definition at line 288 of file ZoneInstance.cpp.
References mLock.
Referenced by UpdateDestinyBox().
GetFlagState()
bool ZoneInstance::GetFlagState (int32_t key, int32_t & value, int32_t worldCID)
Get the state of a zone instance flag.
Parameters
key Lookup key for the flag
value Output value for the flag if it exists
worldCID CID of the character the flag belongs to, 0 if it affects the entire instance
Returns
true if the flag exists, false if it does not
Definition at line 240 of file ZoneInstance.cpp.
References mFlagStates, and mLock.
Referenced by GetFlagStateValue().
GetFlagStates()
std::unordered_map< int32_t, std::unordered_map< int32_t, int32_t > > ZoneInstance::GetFlagStates ()
Return the flag states for the zone.
Returns
Flag states for the zone.
Definition at line 263 of file ZoneInstance.cpp.
References mFlagStates, and mLock.
GetFlagStateValue()
int32_t ZoneInstance::GetFlagStateValue (int32_t key, int32_t nullDefault, int32_t worldCID)
Get the state of a zone instance flag, returning the null default if it does not exist.
Parameters
key Lookup key for the flag
nullDefault Default value to return if the flag is not set
worldCID CID of the character the flag belongs to, 0 if it affects the entire instance
Returns
Value of the specified flag or the nullDefault value if it does not exist
Definition at line 270 of file ZoneInstance.cpp.
References GetFlagState().
GetZone() [1/2]
std::shared_ptr< Zone > ZoneInstance::GetZone (uint32_t zoneID, uint32_t dynamicMapID)
Get a zone in the instance by zone ID and dynamic map ID.
Parameters
zoneID ID of the zone
dynamicMapID Dynamic ID of the zone
Returns
Pointer to the zone in the instance
Definition at line 134 of file ZoneInstance.cpp.
References mLock, and mZones.
GetZone() [2/2]
std::shared_ptr< Zone > ZoneInstance::GetZone (uint32_t uniqueID)
Get a zone in the instance by its unique ID.
Parameters
uniqueID Unique ID of the zone in the instance
Returns
Pointer to the zone in the instance
Definition at line 158 of file ZoneInstance.cpp.
References GetZones().
GetZones()
std::list< std::shared_ptr< Zone > > ZoneInstance::GetZones ()
Get all zones in the instance.
Returns
List of zones in the instance
Definition at line 118 of file ZoneInstance.cpp.
References mLock, and mZones.
Referenced by GetConnections(), and GetZone().
RefreshPlayerState()
void ZoneInstance::RefreshPlayerState ()
Refresh properties calculated dependent upon the players currently in the instance.
Definition at line 185 of file ZoneInstance.cpp.
References GetConnections(), channel::ClientState::GetDemonState(), mLock, and channel::state().
SetFlagState()
void ZoneInstance::SetFlagState (int32_t key, int32_t value, int32_t worldCID)
Set the state of a zone instance flag.
Parameters
key Lookup key for the flag
value Value to set for the flag
worldCID CID of the character the flag belongs to, 0 if it affects the entire instance
Definition at line 282 of file ZoneInstance.cpp.
References mFlagStates, and mLock.
UpdateDestinyBox()
std::unordered_map< uint8_t, std::shared_ptr< objects::Loot > > ZoneInstance::UpdateDestinyBox (int32_t worldCID, uint8_t & newNext, const std::list< std::shared_ptr< objects::Loot >> & add, const std::set< uint8_t > & remove)
Update the loot assigned to the destiny box assigned to a specific world CID.
Parameters
worldCID World CID that has access to the box
add List of pointers to loot to add
remove Optional set of slots to clear before adding loot
Returns
Map of all loot that was removed upon request from the box by slot they were removed from
Definition at line 325 of file ZoneInstance.cpp.
References GetDestinyBox(), and mLock.
Member Data Documentation
mFlagStates
std::unordered_map<int32_t, std::unordered_map<int32_t, int32_t> > channel::ZoneInstance::mFlagStates private
General use flags and associated values used for event sequences etc keyed on 0 for all characters or world CID if for a specific one.
Definition at line 180 of file ZoneInstance.h.
Referenced by GetFlagState(), GetFlagStates(), and SetFlagState().
mLock
std::mutex channel::ZoneInstance::mLock private
Server lock for shared resources.
Definition at line 187 of file ZoneInstance.h.
Referenced by AddZone(), GetDestinyBox(), GetFlagState(), GetFlagStates(), GetZone(), GetZones(), RefreshPlayerState(), SetFlagState(), and UpdateDestinyBox().
mZones
std::unordered_map<uint32_t, std::unordered_map<uint32_t, std::shared_ptr<Zone> > > channel::ZoneInstance::mZones private
Map of zones in the instance by zone ID and dynamic map ID.
Definition at line 184 of file ZoneInstance.h.
Referenced by AddZone(), GetZone(), and GetZones().
The documentation for this class was generated from the following files:
ZoneInstance.h
ZoneInstance.cpp