COMP_hack: channel::ActiveEntityState Class Reference
channel::ActiveEntityState Class Reference
Represents an active entity on the channel server.
#include <ActiveEntityState.h>
Public Member Functions
ActiveEntityState ()
Create a new active entity state.
ActiveEntityState (const ActiveEntityState &other)
Explicitly defined copy constructor necessary due to removal of implicit constructor from non-copyable mutex member.
size_t AddRemoveOpponent (bool add, int32_t opponentID)
Add or remove an opponent with the specified entity ID.
std::set< uint32_t > AddStatusEffects (const AddStatusEffectMap &effects, libcomp::DefinitionManager *definitionManager, uint32_t now=0, bool queueChanges=true)
Add new status effects to the entity and activate them.
bool CanAct ()
Check if the entity is able to move or activate a skill.
void CancelStatusEffects (uint8_t cancelFlags)
Cancel existing status effects via cancel event flags.
bool CanMove ()
Check if the entity is able to move.
void ExpireStatusEffects (const std::set< uint32_t > &effectTypes)
Expire existing status effects by effect type ID.
void ExpireStatusTimes (uint64_t now)
Expire any status times that have passed.
uint64_t GetActionTime (const libcomp::String &action)
Retrieves a timestamp associated to an enemy specific action.
std::shared_ptr< channel::AIState > GetAIState () const
Get the AIState of the entity.
virtual std::set< uint32_t > GetAllSkills (libcomp::DefinitionManager *definitionManager, bool includeTokusei)
Get all skills that the entity currently has available.
virtual std::shared_ptr< objects::EntityStats > GetCoreStats ()
Get the core stats associated to the active entity.
int16_t GetCorrectValue (CorrectTbl tableID, std::shared_ptr< objects::CalculatedEntityState > calcState=nullptr)
Get the adjusted correct table value associated to the entity.
std::list< std::pair< std::shared_ptr< objects::StatusEffect >, uint32_t > > GetCurrentStatusEffectStates (libcomp::DefinitionManager *definitionManager, uint32_t now=0)
Get a snapshot of status effects currently on the entity with their corresponding expiration time which is based upon he supplied time for relative duration effects.
float GetDistance (float x, float y, bool squared=false)
Calculate the distance between the entity and the specified X and Y coordiates.
virtual const libobjgen::UUID GetEntityUUID ()
Get the the entity UUID associated to the entity this state represents.
virtual uint8_t GetLNCType ()
Get a numeric representation (also stored in constants) of the entity's current alignment.
float GetMovementSpeed (bool altSpeed=false)
Get the entity's adjusted movement speed.
int8_t GetNextActivatedAbilityID ()
Get the next activated ability ID from 0 to 127.
int16_t GetNRAChance (uint8_t nraIdx, CorrectTbl type, std::shared_ptr< objects::CalculatedEntityState > calcState=nullptr)
Get the entity's chance to null, reflect or absorb the specified affinity.
std::set< int32_t > GetOpponentIDs () const
Get the entity IDs of opponents this entity is in combat against.
const std::unordered_map< uint32_t, std::shared_ptr< objects::StatusEffect > > & GetStatusEffects () const
Get the current status effect map.
std::shared_ptr< Zone > GetZone () const
Get the zone the entity currently exists in.
bool HasOpponent (int32_t opponentID=0)
Check if the entity has an opponent with the specified entity ID.
bool IsAlive () const
Check if the entity is currently alive.
bool IsLNCType (uint8_t lncType, bool invertFlag)
Check if the entity matches the supplied LNC type.
bool IsMoving () const
Check if the entity is currently not at their destination position.
bool IsRotating () const
Check if the entity is currently not at their destination rotation.
void Move (float xPos, float yPos, uint64_t now)
Set the entity's destination position based on the supplied values and uses the current position values to set the origin.
bool PopEffectTicks (libcomp::DefinitionManager *definitionManager, uint32_t time, int32_t &hpTDamage, int32_t &mpTDamage, std::set< uint32_t > &added, std::set< uint32_t > &updated, std::set< uint32_t > &removed)
Pop effect events that have occurred past the specified time off the event mapping for the entity and their current zone.
std::set< uint8_t > PopNRAShields (const std::list< CorrectTbl > &types)
Decrease the corresponding NRA affinity shield effect stacks and return the NRA correct table indexes that apply.
virtual bool Ready (bool ignoreDisplayState=false)
Check if the entity state has everything needed to start being used.
virtual bool RecalcDisabledSkills (libcomp::DefinitionManager *definitionManager)
Recalculate the set of skills available ot the entity that are currently disabled.
virtual uint8_t RecalculateStats (libcomp::DefinitionManager *definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState=nullptr)
Recalculate the entity's stats, adjusted by equipment and effects.
void RefreshCurrentPosition (uint64_t now)
Update the entity's current position and rotation values based upon the source/destination ticks and the current time.
void RefreshKnockback (uint64_t now, float recoveryBoost)
Update the entity's current knockback value based on the last ticks associated to the value and the current time.
void Rotate (float rot, uint64_t now)
Set the entity's destination rotation based on the supplied values and uses the current rotation values to set the origin.
void SetActionTime (const libcomp::String &action, uint64_t time)
Stores a timestamp associated to an enemy specific action.
void SetAIState (const std::shared_ptr< channel::AIState > &aiState)
Set the AIState of the entity.
bool SetHPMP (int32_t hp, int32_t mp, bool adjust, bool canOverflow=false)
Set the HP and/or MP of the entity to either a specified or adjusted value.
bool SetHPMP (int32_t hp, int32_t mp, bool adjust, bool canOverflow, int32_t clenchChance, int32_t &hpAdjusted, int32_t &mpAdjusted)
Set the HP and/or MP of the entity to either a specified or adjusted value.
void SetStatusEffects (const std::list< std::shared_ptr< objects::StatusEffect >> &effects)
Set the status effects currently on the entity.
void SetStatusEffectsActive (bool activate, libcomp::DefinitionManager *definitionManager, uint32_t now=0)
Activate or deactivate the entity's status effect states.
void SetZone (const std::shared_ptr< Zone > &zone, bool updatePrevious=true)
Set the entity's current zone.
bool SkillAvailable (uint32_t skillID)
Check if the entity has the supplied skill learned and not currently disabled.
void Stop (uint64_t now)
Stop the entity's movement based on the current postion information.
float UpdateKnockback (uint64_t now, float decrease, float recoveryBoost)
Refresh and then reduce the entity's knockback value.
Static Public Member Functions
static float CorrectRotation (float rot)
Corrects rotation values that have exceeded the minimum or maximum allowed range.
Protected Member Functions
void ActivateStatusEffect (const std::shared_ptr< objects::StatusEffect > &effect, libcomp::DefinitionManager *definitionManager, uint32_t now, bool timeOnly)
Activate a status effect added to the entity's current status effect set.
void AdjustStats (const std::list< std::shared_ptr< objects::MiCorrectTbl >> &adjustments, libcomp::EnumMap< CorrectTbl, int16_t > &stats, std::shared_ptr< objects::CalculatedEntityState > calcState, bool baseMode)
Adjust the supplied correct table stat values based upon adjustments from equipment or status effects.
virtual void BaseStatsCalculated (libcomp::DefinitionManager *definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState, libcomp::EnumMap< CorrectTbl, int16_t > &stats, std::list< std::shared_ptr< objects::MiCorrectTbl >> &adjustments)
Generic handler for anything that needs to occur between calculating entity base stats and calculating the rest of the entity.
uint8_t CalculateLNCType (int16_t lncPoints) const
Calculate the numeric representation (also stored in constants) of the entity's alignment based off the supplied LNC point value.
uint8_t CompareAndResetStats (libcomp::EnumMap< CorrectTbl, int16_t > &stats, int32_t extraHP=0)
Compare and set the entity's current stats and also keep track of if a change occurred.
void GetAdditionalCorrectTbls (libcomp::DefinitionManager *definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState, std::list< std::shared_ptr< objects::MiCorrectTbl >> &adjustments)
Get the correct table value adjustments from the entity's current skills and status effects.
uint32_t GetCurrentExpiration (const std::shared_ptr< objects::StatusEffect > &effect, libcomp::DefinitionManager *definitionManager, uint32_t nextTime, uint32_t now)
Calculate the relative or absolute expiration for an effect based upon the current system time and an absolute system time.
std::set< uint32_t > GetEffectiveTokuseiSkills (libcomp::DefinitionManager *definitionManager)
Get the set of skill IDs granted by effective tokusei.
uint8_t RecalculateDemonStats (libcomp::DefinitionManager *definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState)
Recalculate a demon or enemy entity's stats.
void RegisterNextEffectTime ()
Register the entity's next effect event time with the current zone.
void RemoveInactiveSwitchSkills ()
Remove any switch skills marked as active that are no longer available to the entity.
void RemoveStatusEffects (const std::set< uint32_t > &effectTypes)
Remove the set of supplied status effects from all registered collections.
void SetNextEffectTime (uint32_t effectType, uint32_t time)
Set the next effect event time for a specified effect type for the entity's event map.
void SetStatusEffects (const std::list< libcomp::ObjectReference< objects::StatusEffect >> &effects)
Set the status effects currently on the entity.
void UpdateNRAChances (libcomp::EnumMap< CorrectTbl, int16_t > &stats, std::shared_ptr< objects::CalculatedEntityState > calcState, const std::list< std::shared_ptr< objects::MiCorrectTbl >> &adjustments={})
Update the entity's calculated NRA chances for each affinity from base and equipment values.
Protected Attributes
std::unordered_map< std::string, uint64_t > mActionTimes
Map of timestamps associated to AI specific actions.
std::shared_ptr< AIState > mAIState
Pointer to the AI state information bound to the entity.
bool mAlive
Signifies that the entity is alive.
std::unordered_map< uint8_t, std::set< uint32_t > > mCancelConditions
Active effect type IDs mapped to cancel condition flags for quick access.
std::shared_ptr< Zone > mCurrentZone
Pointer to the current zone the entity is in.
bool mEffectsActive
true if the status effects have been activated for the current zone
bool mInitialCalc
false if the entity has been assigned but never calculated
uint64_t mLastRefresh
Last timestamp the entity's state was refreshed.
std::mutex mLock
Server lock for shared resources.
int8_t mNextActivatedAbilityID
Next available activated ability ID.
std::map< uint32_t, std::set< uint32_t > > mNextEffectTimes
Map of server system times mapped to the next event time associated to each active status effect.
std::unordered_map< uint32_t, libcomp::EnumMap< CorrectTbl, std::set< uint8_t > > > mNRAShields
Map of effect type IDs to NRA types and NRA indexes.
std::set< int32_t > mOpponentIDs
Set of entity IDs representing opponents that the entity is currently fighting.
std::unordered_map< uint32_t, std::shared_ptr< objects::StatusEffect > > mStatusEffects
Map of active status effects by effect type ID.
std::set< uint32_t > mTimeDamageEffects
IDs of status effects currently active that deal time damage for quick access.
Detailed Description
Represents an active entity on the channel server.
An entity is active if it can move or perform actions independent of other entities. Active entities have stats and status effects in addition to the usual current zone position shared with non-active entities.
Definition at line 114 of file ActiveEntityState.h.
Constructor & Destructor Documentation
ActiveEntityState::ActiveEntityState ()
Create a new active entity state.
Definition at line 106 of file ActiveEntityState.cpp.
ActiveEntityState::ActiveEntityState (const ActiveEntityState & other)
Explicitly defined copy constructor necessary due to removal of implicit constructor from non-copyable mutex member.
This should never actually be used.
Parameters
other The other entity to copy
Definition at line 112 of file ActiveEntityState.cpp.
Member Function Documentation
void ActiveEntityState::ActivateStatusEffect (const std::shared_ptr< objects::StatusEffect > & effect, libcomp::DefinitionManager * definitionManager, uint32_t now, bool timeOnly) protected
Activate a status effect added to the entity's current status effect set.
By activating an effect, it will be registered with the ActiveEntityState and its current zone via their absolute server time expiration in addition to setting any quick access properties on the entity.
Parameters
effect Pointer to the effect to activate
definitionManager Pointer to the DefinitionManager to use when determining how the effect behaves
now Current system timestamp to use when activating the effect
timeOnly true if only the time will be registered, should only be used if the expiration is being updated
Definition at line 1447 of file ActiveEntityState.cpp.
References libcomp::DefinitionManager::GetStatusData(), mCancelConditions, mNextEffectTimes, mNRAShields, and mTimeDamageEffects.
Referenced by AddStatusEffects(), and SetStatusEffectsActive().
size_t ActiveEntityState::AddRemoveOpponent (bool add, int32_t opponentID)
Add or remove an opponent with the specified entity ID.
Parameters
add true if the opponent will be added, false if it will be removed
opponentID Entity ID of an opponent to add or remove
Returns
Number of opponents associated to the entity after the operation
Definition at line 1297 of file ActiveEntityState.cpp.
References mLock, and mOpponentIDs.
Referenced by channel::CharacterManager::AddRemoveOpponent(), and channel::ZoneManager::LeaveZone().
std::set< uint32_t > ActiveEntityState::AddStatusEffects (const AddStatusEffectMap & effects, libcomp::DefinitionManager * definitionManager, uint32_t now = 0, bool queueChanges = true)
Add new status effects to the entity and activate them.
If there are status effects that are replaced by the application of the new ones they will be expired and returned.
Parameters
effects Map of status effect stacks and whether they are replaces or not by effect type ID
definitionManager Pointer to the DefinitionManager to use when determining how the effects behave
now Current system timestamp to use when activating the effects, defaults to the current time if not specified
queueChanges If true and the entity is in an effect active state, the effect inserts, updates and removes will be queued as the next entity time-based events to be processed by the next server tick. Set to false if the changes will be communicated by some other means
Returns
Set of expired effect IDs if any added effects cancel existing effects
Definition at line 641 of file ActiveEntityState.cpp.
References ActivateStatusEffect(), GetEntityUUID(), libcomp::DefinitionManager::GetStatusData(), mEffectsActive, mLock, mNextEffectTimes, mStatusEffects, RegisterNextEffectTime(), and RemoveStatusEffects().
Referenced by channel::ChatManager::GMCommand_Effect().
void ActiveEntityState::AdjustStats (const std::list< std::shared_ptr< objects::MiCorrectTbl >> & adjustments, libcomp::EnumMap< CorrectTbl, int16_t > & stats, std::shared_ptr< objects::CalculatedEntityState > calcState, bool baseMode) protected
Adjust the supplied correct table stat values based upon adjustments from equipment or status effects.
Parameters
adjustments List of adjustments to the correct table values supplied
stats Output map parameter of base or calculated stats to adjust for the current entity
calcState Override CalculatedEntityState to use instead of the entity's default
baseMode If true only base stat correct table types will be adjusted, if false only the non-base stat correct table types will be adjusted and NRA values will be updated immediately.
Definition at line 2177 of file ActiveEntityState.cpp.
References channel::CharacterManager::AdjustStatBounds(), channel::TokuseiManager::CalculateAttributeValue(), NRA_ABSORB, NRA_NULL, and NRA_REFLECT.
Referenced by RecalculateDemonStats(), and channel::ActiveEntityStateImp< T >::RecalculateStats().
void ActiveEntityState::BaseStatsCalculated (libcomp::DefinitionManager * definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState, libcomp::EnumMap< CorrectTbl, int16_t > & stats, std::list< std::shared_ptr< objects::MiCorrectTbl >> & adjustments) protected virtual
Generic handler for anything that needs to occur between calculating entity base stats and calculating the rest of the entity.
This is also reponsible for setting the CalculatedEntityState's final tokusei effects. Should base stats be adjusted further by the outcome of this function, it is also responsible for setting the new values.
Parameters
definitionManager Pointer to the DefinitionManager to use when determining how various things interact with the entity
calcState Override CalculatedEntityState to use instead of the entity's default
stats Output map parameter of base or calculated stats to adjust for the current entity
adjustments List of adjustments to the correct table values supplied
Reimplemented in channel::CharacterState.
Definition at line 2338 of file ActiveEntityState.cpp.
Referenced by channel::CharacterState::BaseStatsCalculated(), RecalculateDemonStats(), and channel::ActiveEntityStateImp< T >::RecalculateStats().
uint8_t ActiveEntityState::CalculateLNCType (int16_t lncPoints) const protected
Calculate the numeric representation (also stored in constants) of the entity's alignment based off the supplied LNC point value.
Parameters
lncPoints LNC points representing degrees of alignment
Returns
Numeric representation of the entity's current alignment
Definition at line 2563 of file ActiveEntityState.cpp.
References LNC_CHAOS, LNC_LAW, and LNC_NEUTRAL.
Referenced by channel::ActiveEntityStateImp< T >::GetLNCType().
bool ActiveEntityState::CanAct ()
Check if the entity is able to move or activate a skill.
Returns
true if the entity can act, false if it cannot
Definition at line 199 of file ActiveEntityState.cpp.
References CanMove(), and mAlive.
void ActiveEntityState::CancelStatusEffects (uint8_t cancelFlags)
Cancel existing status effects via cancel event flags.
The expire event will be queued up for processing on the next server tick.
Parameters
cancelFlags Flags indicating conditions that can cause status effects to be cancelled. The set of valid status conditions are listed as constants on ActiveEntityState
Definition at line 1041 of file ActiveEntityState.cpp.
References ExpireStatusEffects(), mCancelConditions, and mLock.
bool ActiveEntityState::CanMove ()
Check if the entity is able to move.
Returns
true if the entity can move, false if it cannot
Definition at line 204 of file ActiveEntityState.cpp.
References GetCorrectValue(), mAlive, STATUS_CHARGING, STATUS_HIT_STUN, STATUS_IMMOBILE, STATUS_KNOCKBACK, and STATUS_RESTING.
Referenced by CanAct(), Move(), and Rotate().
uint8_t ActiveEntityState::CompareAndResetStats (libcomp::EnumMap< CorrectTbl, int16_t > & stats, int32_t extraHP = 0) protected
Compare and set the entity's current stats and also keep track of if a change occurred.
Parameters
stats Map of correct table IDs to calculated stats to set on the entity
extraHP Extra HP amount to add to the base MaxHP. Used by enemies.
Returns
1 if the calculation resulted in a change to the stats that should be sent to the client, 2 if one of the changes should be communicated to the world (for party members etc), 0 if no change resulted from the recalculation
Definition at line 2632 of file ActiveEntityState.cpp.
References ENTITY_CALC_MOVE_SPEED, ENTITY_CALC_STAT_LOCAL, ENTITY_CALC_STAT_WORLD, and GetCoreStats().
Referenced by RecalculateDemonStats(), and channel::ActiveEntityStateImp< T >::RecalculateStats().
float ActiveEntityState::CorrectRotation (float rot) static
Corrects rotation values that have exceeded the minimum or maximum allowed range.
Parameters
rot Original rotation value to correct
Returns
Equivalent but corrected rotation value
Definition at line 243 of file ActiveEntityState.cpp.
Referenced by channel::SkillManager::ProcessSkillResult(), RefreshCurrentPosition(), and Rotate().
void ActiveEntityState::ExpireStatusEffects (const std::set< uint32_t > & effectTypes)
Expire existing status effects by effect type ID.
The expire event will be queued up for processing on the next server tick.
Parameters
effectTypes Set of effect type IDs to expire
Definition at line 1008 of file ActiveEntityState.cpp.
References mEffectsActive, mLock, mNextEffectTimes, mStatusEffects, RegisterNextEffectTime(), RemoveStatusEffects(), and SetNextEffectTime().
Referenced by CancelStatusEffects(), and PopNRAShields().
void ActiveEntityState::ExpireStatusTimes (uint64_t now)
Expire any status times that have passed.
Parameters
now Current timestamp of the server
Definition at line 371 of file ActiveEntityState.cpp.
uint64_t ActiveEntityState::GetActionTime (const libcomp::String & action)
Retrieves a timestamp associated to an enemy specific action.
Parameters
action Name of the action to retrieve information from
Returns
Timestamp associated to the action or 0 if not found
Definition at line 396 of file ActiveEntityState.cpp.
References libcomp::String::C(), mActionTimes, and mLock.
void ActiveEntityState::GetAdditionalCorrectTbls (libcomp::DefinitionManager * definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState, std::list< std::shared_ptr< objects::MiCorrectTbl >> & adjustments) protected
Get the correct table value adjustments from the entity's current skills and status effects.
Parameters
definitionManager Pointer to the DefinitionManager to use when determining how the skills and effects behave
calcState Override CalculatedEntityState to use instead of the entity's default
adjustments Output list parameter to add the adjustments to
Definition at line 2415 of file ActiveEntityState.cpp.
References libcomp::DefinitionManager::GetSkillData(), libcomp::DefinitionManager::GetStatusData(), GetStatusEffects(), and libcomp::DefinitionManager::GetTokuseiData().
Referenced by RecalculateDemonStats(), and channel::ActiveEntityStateImp< T >::RecalculateStats().
std::shared_ptr< AIState > ActiveEntityState::GetAIState () const
Get the AIState of the entity.
Returns
Pointer to the AIState of the entity or null if the entity is not AI controlled
Definition at line 386 of file ActiveEntityState.cpp.
References mAIState.
Referenced by channel::CharacterManager::AddRemoveOpponent().
std::set< uint32_t > ActiveEntityState::GetAllSkills (libcomp::DefinitionManager * definitionManager, bool includeTokusei) virtual
Get all skills that the entity currently has available.
Parameters
definitionManager Pointer to the definition manager to use for skill source definitions
includeTokusei false if tokusei skills should not be included
Returns
Set of all skill IDs the entity currently has available
Reimplemented in channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< objects::Demon >, channel::ActiveEntityStateImp< objects::Enemy >, and channel::ActiveEntityStateImp< objects::Character >.
Definition at line 1667 of file ActiveEntityState.cpp.
Referenced by channel::ActiveEntityStateImp< T >::RecalculateStats().
std::shared_ptr< objects::EntityStats > ActiveEntityState::GetCoreStats () virtual
Get the core stats associated to the active entity.
Returns
Pointer to the active entity's core stats
Reimplemented in channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< objects::Demon >, channel::ActiveEntityStateImp< objects::Enemy >, and channel::ActiveEntityStateImp< objects::Character >.
Definition at line 1680 of file ActiveEntityState.cpp.
Referenced by channel::TokuseiManager::CalculateAttributeValue(), CompareAndResetStats(), RecalculateDemonStats(), and SetHPMP().
int16_t ActiveEntityState::GetCorrectValue (CorrectTbl tableID, std::shared_ptr< objects::CalculatedEntityState > calcState = nullptr)
Get the adjusted correct table value associated to the entity.
Parameters
tableID ID of the correct table value to retrieve
calcState Override CalculatedEntityState to use instead of the entity's default
Returns
Adjusted correct table value
Definition at line 117 of file ActiveEntityState.cpp.
Referenced by CanMove(), GetMovementSpeed(), PopEffectTicks(), and RefreshKnockback().
uint32_t ActiveEntityState::GetCurrentExpiration (const std::shared_ptr< objects::StatusEffect > & effect, libcomp::DefinitionManager * definitionManager, uint32_t nextTime, uint32_t now) protected
Calculate the relative or absolute expiration for an effect based upon the current system time and an absolute system time.
Parameters
effect Pointer to the effect to calculate the expiration of
definitionManager Pointer to the DefinitionManager to use when determining how the effect behaves
nextTime Absolute system time to use when calculating the expiration
now Current system timestamp to use when activating the effect
Returns
Calculated expiration for the effect
Definition at line 1570 of file ActiveEntityState.cpp.
References libcomp::DefinitionManager::GetStatusData().
Referenced by GetCurrentStatusEffectStates(), and SetStatusEffectsActive().
std::list< std::pair< std::shared_ptr< objects::StatusEffect >, uint32_t > > ActiveEntityState::GetCurrentStatusEffectStates (libcomp::DefinitionManager * definitionManager, uint32_t now = 0)
Get a snapshot of status effects currently on the entity with their corresponding expiration time which is based upon he supplied time for relative duration effects.
Parameters
definitionManager Pointer to the DefinitionManager to use when determining how the effects behave
now Current system timestamp to use for caculating relative duration expirations remaining, if nothing is specified, the current time will be used
Returns
List of current status effects paired with their expiration time remaining
Definition at line 1229 of file ActiveEntityState.cpp.
References GetCurrentExpiration(), mEffectsActive, mLock, mNextEffectTimes, and mStatusEffects.
float ActiveEntityState::GetDistance (float x, float y, bool squared = false)
Calculate the distance between the entity and the specified X and Y coordiates.
Parameters
x X coordinate to calculate the distance for
y Y coordinate to calculate the distance for
squared Optional parameter to return the distance squared for faster radius comparisons
Returns
Distance between the entity and the specified point
Definition at line 257 of file ActiveEntityState.cpp.
Referenced by Move().
std::set< uint32_t > ActiveEntityState::GetEffectiveTokuseiSkills (libcomp::DefinitionManager * definitionManager) protected
Get the set of skill IDs granted by effective tokusei.
Parameters
definitionManager Pointer to the definition manager to use for tokusei definitions
Returns
Set of skill IDs granted by effective tokusei
Definition at line 2591 of file ActiveEntityState.cpp.
References libcomp::DefinitionManager::GetTokuseiData().
Referenced by channel::ActiveEntityStateImp< T >::GetAllSkills().
const libobjgen::UUID ActiveEntityState::GetEntityUUID () virtual
Get the the entity UUID associated to the entity this state represents.
Returns
Entity UUID or null UUID if not specified
Reimplemented in channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< objects::Demon >, channel::ActiveEntityStateImp< objects::Enemy >, and channel::ActiveEntityStateImp< objects::Character >.
Definition at line 124 of file ActiveEntityState.cpp.
Referenced by AddStatusEffects().
uint8_t ActiveEntityState::GetLNCType () virtual
Get a numeric representation (also stored in constants) of the entity's current alignment.
Returns
Numeric representation of the entity's current alignment
Reimplemented in channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< objects::Demon >, channel::ActiveEntityStateImp< objects::Enemy >, and channel::ActiveEntityStateImp< objects::Character >.
Definition at line 1675 of file ActiveEntityState.cpp.
Referenced by IsLNCType().
float ActiveEntityState::GetMovementSpeed (bool altSpeed = false)
Get the entity's adjusted movement speed.
Parameters
altSpeed true if the alternate speed used for walking should be retrieved instead of the default run speed
Returns
Movement speed of the entity
Definition at line 264 of file ActiveEntityState.cpp.
References GetCorrectValue(), and mOpponentIDs.
Referenced by Move(), and Rotate().
int8_t ActiveEntityState::GetNextActivatedAbilityID ()
Get the next activated ability ID from 0 to 127.
Returns
The next activated ability ID for the client
Definition at line 1381 of file ActiveEntityState.cpp.
References mLock, and mNextActivatedAbilityID.
int16_t ActiveEntityState::GetNRAChance (uint8_t nraIdx, CorrectTbl type, std::shared_ptr< objects::CalculatedEntityState > calcState = nullptr)
Get the entity's chance to null, reflect or absorb the specified affinity.
Parameters
nraIdx Correct table index for affinity NRA 1) Null 2) Reflect 3) Absorb Defines exist in the Constants header for each of these.
type Correct table type of the affinity to retrieve
calcState Override CalculatedEntityState to use instead of the entity's default
Returns
Integer representation of the chance to avoid affinity damage, 0 if the supplied values are invalid
Definition at line 1312 of file ActiveEntityState.cpp.
References NRA_ABSORB, NRA_NULL, and NRA_REFLECT.
std::set< int32_t > ActiveEntityState::GetOpponentIDs () const
Get the entity IDs of opponents this entity is in combat against.
Returns
Set of opponent entity IDs
Definition at line 1285 of file ActiveEntityState.cpp.
References mOpponentIDs.
const std::unordered_map< uint32_t, std::shared_ptr< objects::StatusEffect > > & ActiveEntityState::GetStatusEffects () const
Get the current status effect map.
Returns
Map of current status effects by type ID
Definition at line 618 of file ActiveEntityState.cpp.
References mStatusEffects.
Referenced by channel::EventManager::EvaluateCondition(), and GetAdditionalCorrectTbls().
std::shared_ptr< Zone > ActiveEntityState::GetZone () const
Get the zone the entity currently exists in.
Returns
Pointer to the entity's current zone, nullptr if they are not currently in a zone
Definition at line 468 of file ActiveEntityState.cpp.
References mCurrentZone.
Referenced by channel::TokuseiManager::CalculateAttributeValue(), channel::SkillManager::ExecuteNormalSkill(), channel::SkillManager::FinalizeSkillExecution(), channel::SkillManager::ProcessSkillResult(), channel::SkillManager::ProcessSkillResultFinal(), channel::SkillManager::SendActivateSkill(), channel::SkillManager::SendCompleteSkill(), channel::SkillManager::SendExecuteSkill(), and channel::SkillManager::SendExecuteSkillInstant().
bool ActiveEntityState::HasOpponent (int32_t opponentID = 0)
Check if the entity has an opponent with the specified entity ID.
Parameters
opponentID Entity ID of an opponent to find or 0 to check for any
Returns
true if the entity ID is associated as an opponent to this entity
Definition at line 1290 of file ActiveEntityState.cpp.
References mLock, and mOpponentIDs.
bool ActiveEntityState::IsAlive () const
Check if the entity is currently alive.
Returns
true if the entity is alive, false if they are not
Definition at line 183 of file ActiveEntityState.cpp.
References mAlive.
bool ActiveEntityState::IsLNCType (uint8_t lncType, bool invertFlag)
Check if the entity matches the supplied LNC type.
Parameters
lncType LNC tpe to compare to. This can be in two formats based upon the invertFlag parameter.
invertFlag If true compare using the inverted flag format
Returns
true if the LNC matches, false if it does not
Definition at line 1608 of file ActiveEntityState.cpp.
References GetLNCType(), LNC_CHAOS, LNC_LAW, and LNC_NEUTRAL.
bool ActiveEntityState::IsMoving () const
Check if the entity is currently not at their destination position.
Returns
true if the entity is moving, false if they are not
Definition at line 188 of file ActiveEntityState.cpp.
bool ActiveEntityState::IsRotating () const
Check if the entity is currently not at their destination rotation.
Returns
true if the entity is rotating, false if they are not
Definition at line 194 of file ActiveEntityState.cpp.
void ActiveEntityState::Move (float xPos, float yPos, uint64_t now)
Set the entity's destination position based on the supplied values and uses the current position values to set the origin.
Communicating that the move has taken place must be done elsewhere.
Parameters
xPos X position to move to
yPos Y position to move to
now Server time to use as the origin ticks
Definition at line 129 of file ActiveEntityState.cpp.
References CanMove(), GetDistance(), and GetMovementSpeed().
bool ActiveEntityState::PopEffectTicks (libcomp::DefinitionManager * definitionManager, uint32_t time, int32_t & hpTDamage, int32_t & mpTDamage, std::set< uint32_t > & added, std::set< uint32_t > & updated, std::set< uint32_t > & removed)
Pop effect events that have occurred past the specified time off the event mapping for the entity and their current zone.
Parameters
definitionManager Pointer to the DefinitionManager to use when determining how the effects behave
time System timestamp to use for comparing effect events that have passed
hpTDamage Output parameter to store the amount of HP time damage that should be dealt
mpTDamage Output parameter to store the amount of MP time damage that should be dealt
added Output set to store the effect type IDs of newly added effects that have been queued since the specified time
updated Output set to store the effect type IDs of updated effects that have been queued since the specified time
removed Output set to store the effect type IDs of removed effects that have been queued since the specified time
Returns
true if any events have passed, false if none have
Definition at line 1122 of file ActiveEntityState.cpp.
References GetCorrectValue(), libcomp::DefinitionManager::GetStatusData(), mAlive, mLock, mNextEffectTimes, mTimeDamageEffects, RegisterNextEffectTime(), RemoveStatusEffects(), and SetNextEffectTime().
std::set< uint8_t > ActiveEntityState::PopNRAShields (const std::list< CorrectTbl > & types)
Decrease the corresponding NRA affinity shield effect stacks and return the NRA correct table indexes that apply.
Index values are 1) Null 2) Reflect 3) Absorb Defines exist in the Constants header for each of these.
Parameters
types Correct table types of the affinity to retrieve
Returns
Set of all corresponding NRA indexes that existed as shield effects
Definition at line 1333 of file ActiveEntityState.cpp.
References ExpireStatusEffects(), mLock, mNRAShields, and mStatusEffects.
bool ActiveEntityState::Ready (bool ignoreDisplayState = false) virtual
Check if the entity state has everything needed to start being used.
Parameters
ignoreDisplayState Optional parameter to ignore the display state of the entity and return true if the entity is at least set, defaults to false
Returns
true if the state is ready to use, otherwise false
Reimplemented in channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< objects::Demon >, channel::ActiveEntityStateImp< objects::Enemy >, and channel::ActiveEntityStateImp< objects::Character >.
Definition at line 1685 of file ActiveEntityState.cpp.
bool ActiveEntityState::RecalcDisabledSkills (libcomp::DefinitionManager * definitionManager) virtual
Recalculate the set of skills available ot the entity that are currently disabled.
Parameters
definitionManager Pointer to the DefinitionManager to use when determining skill definitions
Returns
true if the set of disabled skills has been updated, false if it has not
Reimplemented in channel::CharacterState.
Definition at line 1661 of file ActiveEntityState.cpp.
uint8_t ActiveEntityState::RecalculateDemonStats (libcomp::DefinitionManager * definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState) protected
Recalculate a demon or enemy entity's stats.
Parameters
definitionManager Pointer to the DefinitionManager to use when determining how effects and items interact with the entity
calcState Override CalculatedEntityState to use instead of the entity's default
Returns
1 if the calculation resulted in a change to the stats that should be sent to the client, 2 if one of the changes should be communicated to the world (for party members etc), 0 otherwise
Definition at line 2498 of file ActiveEntityState.cpp.
References AdjustStats(), BaseStatsCalculated(), channel::CharacterManager::CalculateDependentStats(), CompareAndResetStats(), GetAdditionalCorrectTbls(), GetCoreStats(), mInitialCalc, mLock, and UpdateNRAChances().
Referenced by channel::ActiveEntityStateImp< T >::RecalculateStats().
uint8_t ActiveEntityState::RecalculateStats (libcomp::DefinitionManager * definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState = nullptr) virtual
Recalculate the entity's stats, adjusted by equipment and effects.
Parameters
definitionManager Pointer to the DefinitionManager to use when determining how effects and items interact with the entity
calcState Override CalculatedEntityState to use instead of the entity's default. If a value is supplied for this, the entity's stats will not be updated as a result of the calculation, instead the supplied state will be updated to simulate "effective stats".
Returns
Flags indicating if the calculation resulted in a change that should be communicated to the client or world: 0x01) ENTITY_CALC_STAT_LOCAL = locallly visible stats were changed 0x02) ENTITY_CALC_STAT_WORLD = stats changed that are visible to the world 0x04) ENTITY_CALC_SKILL = skill set has changed (character only)
Reimplemented in channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< T >, channel::ActiveEntityStateImp< objects::Demon >, channel::ActiveEntityStateImp< objects::Enemy >, and channel::ActiveEntityStateImp< objects::Character >.
Definition at line 1653 of file ActiveEntityState.cpp.
void ActiveEntityState::RefreshCurrentPosition (uint64_t now)
Update the entity's current position and rotation values based upon the source/destination ticks and the current time.
If now matches the last refresh time, no work is done.
Parameters
now Current timestamp of the server
Definition at line 290 of file ActiveEntityState.cpp.
References CorrectRotation(), and mLastRefresh.
void ActiveEntityState::RefreshKnockback (uint64_t now, float recoveryBoost)
Update the entity's current knockback value based on the last ticks associated to the value and the current time.
If the value reaches or exceeds the maximum knockback resistance, the max value will be used and the last update tick will be cleared.
Parameters
now Current timestamp of the server
recoveryBoost Recovery rate increase percentage
Definition at line 414 of file ActiveEntityState.cpp.
References GetCorrectValue(), and mLock.
Referenced by UpdateKnockback().
void ActiveEntityState::RegisterNextEffectTime () protected
Register the entity's next effect event time with the current zone.
Definition at line 1561 of file ActiveEntityState.cpp.
References mCurrentZone, mEffectsActive, and mNextEffectTimes.
Referenced by AddStatusEffects(), ExpireStatusEffects(), PopEffectTicks(), SetStatusEffects(), SetStatusEffectsActive(), and SetZone().
void ActiveEntityState::RemoveInactiveSwitchSkills () protected
Remove any switch skills marked as active that are no longer available to the entity.
Definition at line 2579 of file ActiveEntityState.cpp.
Referenced by channel::ActiveEntityStateImp< T >::RecalculateStats().
void ActiveEntityState::RemoveStatusEffects (const std::set< uint32_t > & effectTypes) protected
Remove the set of supplied status effects from all registered collections.
This function should not be called directly in place of being expired first.
Parameters
effectTypes Set of effect type IDs to remove
Definition at line 1421 of file ActiveEntityState.cpp.
References mCancelConditions, mNRAShields, mStatusEffects, and mTimeDamageEffects.
Referenced by AddStatusEffects(), ExpireStatusEffects(), and PopEffectTicks().
void ActiveEntityState::Rotate (float rot, uint64_t now)
Set the entity's destination rotation based on the supplied values and uses the current rotation values to set the origin.
Communicating that the rotation has taken place must be done elsewhere.
Parameters
rot New rotation value to set
now Server time to use as the origin ticks
Definition at line 153 of file ActiveEntityState.cpp.
References CanMove(), CorrectRotation(), and GetMovementSpeed().
void ActiveEntityState::SetActionTime (const libcomp::String & action, uint64_t time)
Stores a timestamp associated to an enemy specific action.
Parameters
action Name of the action to store
time Timestamp of the specified action
Definition at line 408 of file ActiveEntityState.cpp.
References libcomp::String::C(), mActionTimes, and mLock.
void ActiveEntityState::SetAIState (const std::shared_ptr< channel::AIState > & aiState)
Set the AIState of the entity.
Parameters
Pointer to the AIState of the entity
Definition at line 391 of file ActiveEntityState.cpp.
References mAIState.
bool ActiveEntityState::SetHPMP (int32_t hp, int32_t mp, bool adjust, bool canOverflow = false)
Set the HP and/or MP of the entity to either a specified or adjusted value.
Use this instead of a raw EntityStats function to avoid conflicting updats running at the same time.
Parameters
hp Specified or adjusted HP value to apply
mp Specified or adjusted MP value to apply
adjust If true the supplied HP and MP values will be added to the current value instead of being set explicitly
canOverflow true if the entity can be changed from alive to dead and vice-versa
Returns
If adjust and canOverflow are both true, the returned value will be whether the entity's HP has overflowed. If one of those params is false, the returned value represents if the HP or MP were changed
Definition at line 485 of file ActiveEntityState.cpp.
bool ActiveEntityState::SetHPMP (int32_t hp, int32_t mp, bool adjust, bool canOverflow, int32_t clenchChance, int32_t & hpAdjusted, int32_t & mpAdjusted)
Set the HP and/or MP of the entity to either a specified or adjusted value.
Use this instead of a raw EntityStats function to avoid conflicting updats running at the same time.
Parameters
hp Specified or adjusted HP value to apply
mp Specified or adjusted MP value to apply
adjust If true the supplied HP and MP values will be added to the current value instead of being set explicitly
canOverflow true if the entity can be changed from alive to dead and vice-versa
clenchChance Chance to survive a lethal hit from more than 1 starting HP, represented as a 2 decimal precision value (10000 = 100%)
hpAdjusted If not adjusting, this will be the HP damage dealt, otherwise it matches the value supplied
mpAdjusted If not adjusting, this will be the MP damage dealt, otherwise it matches the value supplied
Returns
If adjust and canOverflow are both true, the returned value will be whether the entity's HP has overflowed. If one of those params is false, the returned value represents if the HP or MP were changed
Definition at line 492 of file ActiveEntityState.cpp.
References GetCoreStats(), channel::ChannelServer::GetServerTime(), mAlive, mLock, RNG, and Stop().
void ActiveEntityState::SetNextEffectTime (uint32_t effectType, uint32_t time) protected
Set the next effect event time for a specified effect type for the entity's event map.
The zone itself must be updated using RegisterNextEffectTime after each effect is set using this function.
Parameters
effectType Effect type ID to register an event for
time Absolute system time to register for the event
Definition at line 1533 of file ActiveEntityState.cpp.
References mNextEffectTimes.
Referenced by ExpireStatusEffects(), PopEffectTicks(), and SetStatusEffectsActive().
void ActiveEntityState::SetStatusEffects (const std::list< std::shared_ptr< objects::StatusEffect >> & effects)
Set the status effects currently on the entity.
Parameters
List of status effects currently on the entity
Definition at line 623 of file ActiveEntityState.cpp.
References mCancelConditions, mLock, mNextEffectTimes, mNRAShields, mStatusEffects, mTimeDamageEffects, and RegisterNextEffectTime().
Referenced by channel::ActiveEntityStateImp< T >::SetEntity(), and SetStatusEffects().
void ActiveEntityState::SetStatusEffects (const std::list< libcomp::ObjectReference< objects::StatusEffect >> & effects) protected
Set the status effects currently on the entity.
Parameters
List of status effects currently on the entity as object references
Definition at line 1410 of file ActiveEntityState.cpp.
References SetStatusEffects().
void ActiveEntityState::SetStatusEffectsActive (bool activate, libcomp::DefinitionManager * definitionManager, uint32_t now = 0)
Activate or deactivate the entity's status effect states.
By activating effects, they will be registered with the ActiveEntityState and its current zone via their absolute server time expiration in addition to setting any quick access properties on the entity. By deactivating effects, they will be unregistered from the zone, the quick access properties will be cleared and the expiration time of relative effects will be updated.
Parameters
activate true if the effects will activated, else they will be deactivated
definitionManager Pointer to the DefinitionManager to use when determining how the effects behave
now Current system timestamp to use when activating the effects, defaults to the current time if not specified
Definition at line 1065 of file ActiveEntityState.cpp.
References ActivateStatusEffect(), GetCurrentExpiration(), mCancelConditions, mCurrentZone, mEffectsActive, mLock, mNextEffectTimes, mStatusEffects, mTimeDamageEffects, RegisterNextEffectTime(), and SetNextEffectTime().
void ActiveEntityState::SetZone (const std::shared_ptr< Zone > & zone, bool updatePrevious = true)
Set the entity's current zone.
Parameters
zone Pointer to the zone the entity has entered
updatePrevious true if the previous zone should be notified of the change, false if this is being handled elsewhere
Definition at line 473 of file ActiveEntityState.cpp.
References mCurrentZone, and RegisterNextEffectTime().
Referenced by channel::Zone::Cleanup().
bool ActiveEntityState::SkillAvailable (uint32_t skillID)
Check if the entity has the supplied skill learned and not currently disabled.
Parameters
skillID ID of the skill to check
Returns
true if the skill is available, false if it is not
Definition at line 1603 of file ActiveEntityState.cpp.
void ActiveEntityState::Stop (uint64_t now)
Stop the entity's movement based on the current postion information.
Communicating that the movement has stopped must be done elsewhere.
Parameters
now Server time to use as the origin ticks
Definition at line 171 of file ActiveEntityState.cpp.
Referenced by SetHPMP().
float ActiveEntityState::UpdateKnockback (uint64_t now, float decrease, float recoveryBoost)
Refresh and then reduce the entity's knockback value.
If the value goes under zero, it will be set to zero.
Parameters
now Current timestamp of the server
decrease Value to decrease the knockback value by
recoveryBoost Recovery rate increase percentage
Definition at line 444 of file ActiveEntityState.cpp.
References mLock, and RefreshKnockback().
void ActiveEntityState::UpdateNRAChances (libcomp::EnumMap< CorrectTbl, int16_t > & stats, std::shared_ptr< objects::CalculatedEntityState > calcState, const std::list< std::shared_ptr< objects::MiCorrectTbl >> & adjustments = {}) protected
Update the entity's calculated NRA chances for each affinity from base and equipment values.
NRA chances will further be modified for status effects within AdjustStats during the calculated stat mode.
Parameters
stats Map containing the base NRA values
calcState Override CalculatedEntityState to use instead of the entity's default
adjustments List of adjustments to the correct table values supplied by equipment
Definition at line 2351 of file ActiveEntityState.cpp.
References NRA_ABSORB, NRA_NULL, and NRA_REFLECT.
Referenced by RecalculateDemonStats(), and channel::ActiveEntityStateImp< T >::RecalculateStats().
Member Data Documentation
std::unordered_map<std::string, uint64_t> channel::ActiveEntityState::mActionTimes protected
Map of timestamps associated to AI specific actions.
Definition at line 810 of file ActiveEntityState.h.
Referenced by GetActionTime(), and SetActionTime().
std::shared_ptr<AIState> channel::ActiveEntityState::mAIState protected
Pointer to the AI state information bound to the entity.
Definition at line 813 of file ActiveEntityState.h.
Referenced by GetAIState(), channel::ActiveEntityStateImp< T >::RecalculateStats(), and SetAIState().
bool channel::ActiveEntityState::mAlive protected
Signifies that the entity is alive.
Definition at line 798 of file ActiveEntityState.h.
Referenced by CanAct(), CanMove(), IsAlive(), PopEffectTicks(), channel::ActiveEntityStateImp< T >::SetEntity(), and SetHPMP().
std::unordered_map<uint8_t, std::set<uint32_t> > channel::ActiveEntityState::mCancelConditions protected
Active effect type IDs mapped to cancel condition flags for quick access.
Definition at line 768 of file ActiveEntityState.h.
Referenced by ActivateStatusEffect(), CancelStatusEffects(), RemoveStatusEffects(), SetStatusEffects(), and SetStatusEffectsActive().
std::shared_ptr<Zone> channel::ActiveEntityState::mCurrentZone protected
Pointer to the current zone the entity is in.
Definition at line 780 of file ActiveEntityState.h.
Referenced by GetZone(), RegisterNextEffectTime(), SetStatusEffectsActive(), and SetZone().
bool channel::ActiveEntityState::mEffectsActive protected
true if the status effects have been activated for the current zone
Definition at line 795 of file ActiveEntityState.h.
Referenced by AddStatusEffects(), ExpireStatusEffects(), GetCurrentStatusEffectStates(), RegisterNextEffectTime(), and SetStatusEffectsActive().
bool channel::ActiveEntityState::mInitialCalc protected
false if the entity has been assigned but never calculated
Definition at line 801 of file ActiveEntityState.h.
Referenced by RecalculateDemonStats(), channel::ActiveEntityStateImp< T >::RecalculateStats(), and channel::ActiveEntityStateImp< T >::SetEntity().
uint64_t channel::ActiveEntityState::mLastRefresh protected
Last timestamp the entity's state was refreshed.
Definition at line 804 of file ActiveEntityState.h.
Referenced by RefreshCurrentPosition().
std::mutex channel::ActiveEntityState::mLock protected
Server lock for shared resources.
Definition at line 816 of file ActiveEntityState.h.
Referenced by AddRemoveOpponent(), AddStatusEffects(), CancelStatusEffects(), ExpireStatusEffects(), GetActionTime(), GetCurrentStatusEffectStates(), GetNextActivatedAbilityID(), HasOpponent(), PopEffectTicks(), PopNRAShields(), RecalculateDemonStats(), channel::ActiveEntityStateImp< T >::RecalculateStats(), RefreshKnockback(), SetActionTime(), channel::ActiveEntityStateImp< T >::SetEntity(), SetHPMP(), SetStatusEffects(), SetStatusEffectsActive(), and UpdateKnockback().
int8_t channel::ActiveEntityState::mNextActivatedAbilityID protected
Next available activated ability ID.
Definition at line 807 of file ActiveEntityState.h.
Referenced by GetNextActivatedAbilityID().
std::map<uint32_t, std::set<uint32_t> > channel::ActiveEntityState::mNextEffectTimes protected
Map of server system times mapped to the next event time associated to each active status effect.
Natural HP/MP regen is stored here as a 0. Actual effects will be stored here as reserved values 1 (inticating a new effect was added), 2 (indicating an efect has been updated) or 3 (indicating an effect has expired). Any other value stored will be an absolute system time when the regen or T-Damage will be applied or the effect associated will be expired.
Definition at line 777 of file ActiveEntityState.h.
Referenced by ActivateStatusEffect(), AddStatusEffects(), ExpireStatusEffects(), GetCurrentStatusEffectStates(), PopEffectTicks(), RegisterNextEffectTime(), SetNextEffectTime(), SetStatusEffects(), and SetStatusEffectsActive().
std::unordered_map<uint32_t, libcomp::EnumMap<CorrectTbl, std::set<uint8_t> > > channel::ActiveEntityState::mNRAShields protected
Map of effect type IDs to NRA types and NRA indexes.
This represents a 100% NRA result whenever a skill of the corresponding type is used which will decrease the effect stack until being cancelled out should it occur before the effect's expiration time.
Definition at line 792 of file ActiveEntityState.h.
Referenced by ActivateStatusEffect(), PopNRAShields(), RemoveStatusEffects(), and SetStatusEffects().
std::set<int32_t> channel::ActiveEntityState::mOpponentIDs protected
Set of entity IDs representing opponents that the entity is currently fighting.
If an entity is in this set, this entity should be in their set as well.
Definition at line 785 of file ActiveEntityState.h.
Referenced by AddRemoveOpponent(), GetMovementSpeed(), GetOpponentIDs(), and HasOpponent().
std::unordered_map<uint32_t, std::shared_ptr<objects::StatusEffect> > channel::ActiveEntityState::mStatusEffects protected
Map of active status effects by effect type ID.
Definition at line 760 of file ActiveEntityState.h.
Referenced by AddStatusEffects(), ExpireStatusEffects(), GetCurrentStatusEffectStates(), GetStatusEffects(), PopNRAShields(), RemoveStatusEffects(), SetStatusEffects(), and SetStatusEffectsActive().
std::set<uint32_t> channel::ActiveEntityState::mTimeDamageEffects protected
IDs of status effects currently active that deal time damage for quick access.
Definition at line 764 of file ActiveEntityState.h.
Referenced by ActivateStatusEffect(), PopEffectTicks(), RemoveStatusEffects(), SetStatusEffects(), and SetStatusEffectsActive().
The documentation for this class was generated from the following files:
ActiveEntityState.h
ActiveEntityState.cpp