COMP_hack: channel::PerformanceTimer Class Reference
channel::PerformanceTimer Class Reference
Timer to measure performance of a task.
#include <PerformanceTimer.h>
Public Member Functions
PerformanceTimer (ChannelServer *pServer)
Create the performance timer.
void Start ()
Start a performance measurement.
void Stop (const libcomp::String &metric)
Stop a performance measurement and log it.
Protected Attributes
bool mEnabled
If the performance monitor is enabled.
ChannelServer * mServer
Channel server pointer. Should stay valid while the object exists.
ServerTime mStart
Start time of the performance measurement.
Detailed Description
Timer to measure performance of a task.
Definition at line 48 of file PerformanceTimer.h.
Constructor & Destructor Documentation
PerformanceTimer()
PerformanceTimer::PerformanceTimer (ChannelServer * pServer)
Create the performance timer.
Parameters
pServer Channel server to create the timer for.
Definition at line 40 of file PerformanceTimer.cpp.
References libcomp::BaseServer::GetConfig(), and mEnabled.
Member Function Documentation
Start()
void PerformanceTimer::Start ()
Start a performance measurement.
Definition at line 48 of file PerformanceTimer.cpp.
References channel::ChannelServer::GetServerTime(), mEnabled, mServer, and mStart.
Referenced by channel::ChannelServer::Tick(), and channel::ZoneManager::UpdateActiveZoneStates().
Stop()
void PerformanceTimer::Stop (const libcomp::String & metric)
Stop a performance measurement and log it.
Parameters
metric Name of the task that was measured.
Definition at line 56 of file PerformanceTimer.cpp.
References channel::ChannelServer::GetServerTime(), LOG_DEBUG, mEnabled, mServer, and mStart.
Referenced by channel::ChannelServer::Tick().
Member Data Documentation
mEnabled
bool channel::PerformanceTimer::mEnabled protected
If the performance monitor is enabled.
Definition at line 58 of file PerformanceTimer.h.
Referenced by PerformanceTimer(), Start(), and Stop().
mServer
ChannelServer* channel::PerformanceTimer::mServer protected
Channel server pointer. Should stay valid while the object exists.
Definition at line 52 of file PerformanceTimer.h.
Referenced by Start(), and Stop().
mStart
ServerTime channel::PerformanceTimer::mStart protected
Start time of the performance measurement.
Definition at line 55 of file PerformanceTimer.h.
Referenced by Start(), and Stop().
The documentation for this class was generated from the following files:
PerformanceTimer.h
PerformanceTimer.cpp