COMP_hack: channel::ZoneGeometryLoader Class Reference
channel::ZoneGeometryLoader Class Reference
Loader for QMP zone geometry.
#include <ZoneGeometryLoader.h>
Public Member Functions
std::unordered_map< std::string, std::shared_ptr< ZoneGeometry > > LoadQMP (std::unordered_map< uint32_t, std::set< uint32_t >> localZoneIDs, const std::shared_ptr< ChannelServer > &server)
Load all QMP zone geometry files.
Private Member Functions
bool LoadZoneQMP (const std::shared_ptr< ChannelServer > &server)
Load a QMP for the next zone in the list.
Private Attributes
std::mutex mDataLock
Mutex to lock access to the input and output data by threads.
std::unordered_map< std::string, std::shared_ptr< ZoneGeometry > > mZoneGeometry
Map of QMP filenames to the geometry structures built from them.
std::list< std::pair< uint32_t, std::set< uint32_t > > > mZonePairs
List of zone pairs for the QMP loading process.
Detailed Description
Loader for QMP zone geometry.
Definition at line 43 of file ZoneGeometryLoader.h.
Member Function Documentation
LoadQMP()
std::unordered_map< std::string, std::shared_ptr< ZoneGeometry > > ZoneGeometryLoader::LoadQMP (std::unordered_map< uint32_t, std::set< uint32_t >> localZoneIDs, const std::shared_ptr< ChannelServer > & server)
Load all QMP zone geometry files.
Parameters
localZoneIDs IDs of the zones to load the geometry for.
server Pointer to the channel server.
Returns
Loaded zone geometry.
Definition at line 49 of file ZoneGeometryLoader.cpp.
References LoadZoneQMP(), mZoneGeometry, and mZonePairs.
Referenced by channel::ZoneManager::LoadGeometry().
LoadZoneQMP()
bool ZoneGeometryLoader::LoadZoneQMP (const std::shared_ptr< ChannelServer > & server) private
Load a QMP for the next zone in the list.
Parameters
server Pointer to the channel server.
Definition at line 78 of file ZoneGeometryLoader.cpp.
References libcomp::String::Arg(), libcomp::String::C(), libcomp::String::IsEmpty(), LOG_DEBUG, LOG_ERROR, mDataLock, mZoneGeometry, and mZonePairs.
Referenced by LoadQMP().
Member Data Documentation
mDataLock
std::mutex channel::ZoneGeometryLoader::mDataLock private
Mutex to lock access to the input and output data by threads.
Definition at line 64 of file ZoneGeometryLoader.h.
Referenced by LoadZoneQMP().
mZoneGeometry
std::unordered_map<std::string, std::shared_ptr<ZoneGeometry> > channel::ZoneGeometryLoader::mZoneGeometry private
Map of QMP filenames to the geometry structures built from them.
Definition at line 71 of file ZoneGeometryLoader.h.
Referenced by LoadQMP(), and LoadZoneQMP().
mZonePairs
std::list<std::pair<uint32_t, std::set<uint32_t> > > channel::ZoneGeometryLoader::mZonePairs private
List of zone pairs for the QMP loading process.
Definition at line 67 of file ZoneGeometryLoader.h.
Referenced by LoadQMP(), and LoadZoneQMP().
The documentation for this class was generated from the following files:
ZoneGeometryLoader.h
ZoneGeometryLoader.cpp