COMP_hack: channel::ChannelClientConnection Class Reference
channel::ChannelClientConnection Class Reference
Represents a connection to the game client.
#include <ChannelClientConnection.h>
Public Types
enum ConnectionStatus_t
enum Role_t
Public Member Functions
ChannelClientConnection (asio::ip::tcp::socket &socket, DH *pDiffieHellman)
Create a new connection.
virtual ~ChannelClientConnection ()
Clean up the connection.
virtual bool Close ()
bool Connect (const String &host, uint16_t port=0, bool async=true)
virtual void ConnectionSuccess ()
void FlushOutgoing (bool closeConnection=false)
ClientState * GetClientState () const
Get the state of the client.
String GetName () const
String GetRemoteAddress () const
Role_t GetRole () const
ConnectionStatus_t GetStatus () const
uint64_t GetTimeout () const
Get the next client timeout timestamp.
void Kill ()
Close the connection after marking it to not save any logout data.
virtual bool QueueObject (const Object &obj)
virtual void QueuePacket (Packet &packet)
virtual void QueuePacket (ReadOnlyPacket &packet)
virtual void QueuePacketCopy (libcomp::Packet &packet)
void RefreshTimeout (uint64_t now, uint16_t aliveUntil)
Refresh the client timeout.
bool RequestPacket (size_t size)
virtual bool SendObject (const Object &obj, bool closeConnection=false)
virtual void SendPacket (ReadOnlyPacket &packet, bool closeConnection=false)
virtual void SendPacket (Packet &packet, bool closeConnection=false)
virtual void SendPacketCopy (libcomp::Packet &packet, bool closeConnection=false)
void SetMessageQueue (const std::shared_ptr< MessageQueue< libcomp::Message::Message * >> &messageQueue)
void SetName (const String &name)
void SetServerConfig (const std::shared_ptr< objects::ServerConfig > &config)
Static Public Member Functions
static void BroadcastPacket (const std::list< std::shared_ptr< TcpConnection >> &connections, Packet &packet)
static void BroadcastPacket (const std::list< std::shared_ptr< TcpConnection >> &connections, ReadOnlyPacket &packet)
static void BroadcastPacket (const std::list< std::shared_ptr< ChannelClientConnection >> &clients, libcomp::Packet &packet, bool queue=false)
Broadcast the supplied packet to each client connection in the list.
static void BroadcastPackets (const std::list< std::shared_ptr< ChannelClientConnection >> &clients, std::list< libcomp::Packet > &packets)
Broadcast the supplied list of packets to each client connection in the list.
static void FlushAllOutgoing (const std::list< std::shared_ptr< ChannelClientConnection >> &clients)
Flush all client connection outgoing packets.
static String GenerateDiffieHellmanPublic (DH *pDiffieHellman)
static std::vector< char > GenerateDiffieHellmanSharedData (DH *pDiffieHellman, const String &otherPublic)
static String GetDiffieHellmanPrime (const DH *pDiffieHellman)
static void SendRelativeTimePacket (const std::list< std::shared_ptr< ChannelClientConnection >> &clients, libcomp::Packet &p, const RelativeTimeMap &timeMap, bool queue=false)
Send (or queue) a packet to a list of client connections.
Public Attributes
ROLE_CLIENT
ROLE_SERVER
STATUS_CONNECTED
STATUS_CONNECTING
STATUS_ENCRYPTED
STATUS_NOT_CONNECTED
STATUS_WAITING_ENCRYPTION
Protected Types
typedef void(EncryptedConnection::* PacketParser_t) (libcomp::Packet &packet)
Protected Member Functions
virtual void Connect (const asio::ip::tcp::endpoint &endpoint, bool async=true)
virtual void ConnectionEncrypted ()
virtual void ConnectionFailed ()
virtual bool DecompressPacket (libcomp::Packet &packet, uint32_t &paddedSize, uint32_t &realSize, uint32_t &dataStart)
virtual std::list< ReadOnlyPacket > GetCombinedPackets ()
virtual uint32_t GetHeaderSize ()
virtual void PacketReceived (libcomp::Packet &packet)
virtual void PacketSent (ReadOnlyPacket &packet)
void ParseClientEncryptionStart (libcomp::Packet &packet)
virtual bool ParseExtensionConnection (libcomp::Packet &packet)
void ParsePacket (libcomp::Packet &packet)
void ParsePacket (libcomp::Packet &packet, uint32_t paddedSize, uint32_t realSize)
void ParseServerEncryptionFinish (libcomp::Packet &packet)
void ParseServerEncryptionStart (libcomp::Packet &packet)
virtual void PreparePackets (std::list< ReadOnlyPacket > &packets)
void SendMessage (const std::function< libcomp::Message::Message *(const std::shared_ptr< libcomp::TcpConnection > &)> &messageAllocFunction)
void SetEncryptionKey (const void *pData, size_t dataSize)
void SetEncryptionKey (const std::vector< char > &data)
virtual void SocketError (const libcomp::String &errorMessage=libcomp::String())
Protected Attributes
std::ofstream * mCaptureFile
DH * mDiffieHellman
BF_KEY mEncryptionKey
std::shared_ptr< MessageQueue< libcomp::Message::Message *> > mMessageQueue
ReadOnlyPacket mOutgoing
std::mutex mOutgoingMutex
std::list< ReadOnlyPacket > mOutgoingPackets
PacketParser_t mPacketParser
bool mSendingPacket
std::shared_ptr< objects::ServerConfig > mServerConfig
ConnectionStatus_t mStatus
Private Attributes
std::shared_ptr< ClientState > mClientState
State of the client.
uint64_t mTimeout
Server timestamp used to disconnect the client should it pass without refreshing beforehand.
Detailed Description
Represents a connection to the game client.
Definition at line 44 of file ChannelClientConnection.h.
Constructor & Destructor Documentation
ChannelClientConnection()
ChannelClientConnection::ChannelClientConnection (asio::ip::tcp::socket & socket, DH * pDiffieHellman)
Create a new connection.
Parameters
socket Socket provided by the server for the new client.
pDiffieHellman Asymmetric encryption information.
Definition at line 33 of file ChannelClientConnection.cpp.
~ChannelClientConnection()
ChannelClientConnection::~ChannelClientConnection () virtual
Clean up the connection.
Definition at line 39 of file ChannelClientConnection.cpp.
Member Function Documentation
BroadcastPacket()
void ChannelClientConnection::BroadcastPacket (const std::list< std::shared_ptr< ChannelClientConnection >> & clients, libcomp::Packet & packet, bool queue = false) static
Broadcast the supplied packet to each client connection in the list.
Parameters
clients List of client connections to send the packet to
packet Packet to send to the supplied clients
queue Optional parameter to queue packets for the supplied connections instead of sending immediately
Definition at line 64 of file ChannelClientConnection.cpp.
References libcomp::TcpConnection::BroadcastPacket().
Referenced by channel::ManagerConnection::BroadcastPacketToClients(), channel::FusionManager::EndExchange(), channel::ZoneManager::EndInstanceTimer(), channel::MatchManager::EndPvPMatch(), channel::MatchManager::EndUltimateBattlePhase(), channel::FusionManager::HandleTriFusion(), channel::EventManager::HandleTriFusion(), channel::ZoneManager::MultiZoneBossKilled(), channel::ZoneManager::PopEntityForProduction(), channel::ZoneManager::RemoveEntities(), channel::ChatManager::SendChatMessage(), channel::SkillManager::SendCompleteSkill(), channel::MatchManager::SendDiasporaLocation(), channel::SkillManager::SendExecuteSkillInstant(), channel::SkillManager::SendFailure(), channel::ZoneManager::SendInstanceTimer(), channel::CharacterManager::SendOtherCharacterData(), channel::CharacterManager::SendOtherPartnerData(), channel::MatchManager::SendPhase(), channel::MatchManager::SendPvPLocation(), channel::MatchManager::SendZiotite(), channel::ActionManager::SetNPCState(), channel::ZoneManager::ShowEntity(), channel::ZoneManager::ShowNPC(), channel::ZoneManager::ShowObject(), channel::MatchManager::StartUltimateBattle(), channel::MatchManager::UltimateBattleBegin(), channel::MatchManager::UltimateBattleRecruit(), channel::MatchManager::UltimateBattleTick(), channel::AIManager::UpdateAggro(), channel::ZoneManager::UpdateDestinyBox(), channel::MatchManager::UpdatePvPPoints(), channel::ZoneManager::UpdateTrackedTeam(), and channel::ZoneManager::UpdateTrackedZone().
BroadcastPackets()
void ChannelClientConnection::BroadcastPackets (const std::list< std::shared_ptr< ChannelClientConnection >> & clients, std::list< libcomp::Packet > & packets) static
Broadcast the supplied list of packets to each client connection in the list.
Parameters
clients List of client connections to send the packet to
packets Packets to send to the supplied clients
Definition at line 86 of file ChannelClientConnection.cpp.
Referenced by channel::CharacterManager::AddRemoveOpponent(), and channel::ZoneManager::UpdateStatusEffectStates().
FlushAllOutgoing()
void ChannelClientConnection::FlushAllOutgoing (const std::list< std::shared_ptr< ChannelClientConnection >> & clients) static
Flush all client connection outgoing packets.
Parameters
clients List of client connections to flush
Definition at line 100 of file ChannelClientConnection.cpp.
Referenced by channel::ActionManager::CreateLoot(), channel::SkillManager::HandleKills(), channel::SkillManager::HandleNegotiations(), channel::ZoneManager::RemoveEntities(), channel::SkillManager::ScheduleFreeLoot(), channel::ZoneManager::SendAllyData(), channel::ZoneManager::SendEnemyData(), channel::ZoneManager::SendLootBoxData(), channel::ZoneManager::ShowNPC(), channel::ZoneManager::ShowObject(), and channel::AIManager::UpdateActiveStates().
GetClientState()
ClientState * ChannelClientConnection::GetClientState () const
Get the state of the client.
Returns
Pointer to the ClientState
Definition at line 43 of file ChannelClientConnection.cpp.
References mClientState.
GetTimeout()
uint64_t ChannelClientConnection::GetTimeout () const
Get the next client timeout timestamp.
Returns
Server time representation of the next timeout timestamp
Definition at line 53 of file ChannelClientConnection.cpp.
References mTimeout.
Kill()
void ChannelClientConnection::Kill ()
Close the connection after marking it to not save any logout data.
This is useful for if the client gets into a state that is too complex to recover from to avoid data corruption.
Definition at line 58 of file ChannelClientConnection.cpp.
References libcomp::ChannelConnection::Close(), and mClientState.
RefreshTimeout()
void ChannelClientConnection::RefreshTimeout (uint64_t now, uint16_t aliveUntil)
Refresh the client timeout.
Parameters
now Current server time
aliveUntil Time in seconds that needs to pass before the refresh time is no longer valid and the timeout countdown starts
Definition at line 48 of file ChannelClientConnection.cpp.
References mTimeout.
SendRelativeTimePacket()
void ChannelClientConnection::SendRelativeTimePacket (const std::list< std::shared_ptr< ChannelClientConnection >> & clients, libcomp::Packet & p, const RelativeTimeMap & timeMap, bool queue = false) static
Send (or queue) a packet to a list of client connections.
Server tick times are converted to relative client times before sending.
Parameters
clients List of client connections to send the packet to
packet Packet to send to the supplied clients
timeMap Map of packet positions to server times to transform
queue Optional parameter to queue packets for the supplied connections instead of sending immediately
Definition at line 109 of file ChannelClientConnection.cpp.
References libcomp::Packet::Seek(), channel::state(), channel::ClientState::ToClientTime(), and libcomp::Packet::WriteFloat().
Referenced by channel::ZoneManager::FixCurrentPosition(), channel::SkillManager::ProcessSkillResultFinal(), channel::SkillManager::SendActivateSkill(), channel::SkillManager::SendCompleteSkill(), channel::SkillManager::SendExecuteSkill(), channel::SkillManager::SendExecuteSkillInstant(), channel::ZoneManager::SendInstanceTimer(), channel::AIManager::UpdateActiveStates(), and channel::ZoneManager::Warp().
Member Data Documentation
mClientState
std::shared_ptr<ClientState> channel::ChannelClientConnection::mClientState private
State of the client.
Definition at line 128 of file ChannelClientConnection.h.
Referenced by GetClientState(), and Kill().
mTimeout
uint64_t channel::ChannelClientConnection::mTimeout private
Server timestamp used to disconnect the client should it pass without refreshing beforehand.
Definition at line 132 of file ChannelClientConnection.h.
Referenced by GetTimeout(), and RefreshTimeout().
The documentation for this class was generated from the following files:
ChannelClientConnection.h
ChannelClientConnection.cpp