COMP_hack: channel::ChatManager Class Reference
channel::ChatManager Class Reference
Manager to handle chat communication and processing of GM commands.
#include <ChatManager.h>
Public Member Functions
ChatManager (const std::weak_ptr< ChannelServer > &server)
Create a new ChatManager.
~ChatManager ()
Clean up the ChatManager.
bool ExecuteGMCommand (const std::shared_ptr< channel::ChannelClientConnection > &client, const libcomp::String &cmd, const std::list< libcomp::String > &args)
Execute a GM command using the supplied arguments.
bool HandleGMand (const std::shared_ptr< ChannelClientConnection > &client, const libcomp::String &message)
Determine if a message being sent should be handled as a GMand.
bool SendChatMessage (const std::shared_ptr< channel::ChannelClientConnection > &client, ChatType_t chatChannel, const libcomp::String &message)
Send a chat message to the specified chat channel.
bool SendTeamChatMessage (const std::shared_ptr< ChannelClientConnection > &client, const libcomp::String &message, int32_t teamID)
Send a chat message to the client's team.
bool SendTellMessage (const std::shared_ptr< ChannelClientConnection > &client, const libcomp::String &message, const libcomp::String &targetName)
Send a tell message to the specified character.
Private Member Functions
template<typename T >
bool GetDecimalArg (T &outVal, std::list< libcomp::String > &args) const
Get next argument from the supplied argument list as a float/long type.
int8_t GetEquipTypeArg (const std::shared_ptr< channel::ChannelClientConnection > &client, std::list< libcomp::String > &args, const libcomp::String &gmandName, const std::set< int8_t > &validTypes)
Get the valid equip type index associated to the next argument in a list by equip type name or index.
template<typename T >
bool GetIntegerArg (T &outVal, std::list< libcomp::String > &args) const
Get the next argument from the supplied argument list as an integer type.
bool GetStringArg (libcomp::String &outVal, std::list< libcomp::String > &args, libcomp::Convert::Encoding_t encoding=libcomp::Convert::Encoding_t::ENCODING_UTF8) const
Get the next argument from the supplied argument list as a string.
bool GetTargetCharacterAccount (libcomp::String &targetName, bool currentOnly, std::shared_ptr< objects::Character > &targetCharacter, std::shared_ptr< objects::Account > &targetAccount, std::shared_ptr< channel::ChannelClientConnection > &targetClient)
Get channel accessible character, account and client pointers based upon the supplied character name.
bool GMCommand_AddCP (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to add CP to a target account.
bool GMCommand_Announce (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to announce message to server .
bool GMCommand_Ban (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to ban a player currently on the channel.
bool GMCommand_BattlePoints (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to update the client's Battle Points (BP).
bool GMCommand_Bethel (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to update the client's bethel directly.
bool GMCommand_Coin (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to set the total casino coins the character has.
bool GMCommand_Contract (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to add a demon to a character's COMP.
bool GMCommand_Counter (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to view a world level or view/change a character level counter.
bool GMCommand_Cowrie (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to update the client's current cowrie.
bool GMCommand_Crash (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to crash the server (for testing).
bool GMCommand_DigitalizePoints (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to gain digitalize points.
bool GMCommand_Effect (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to apply a status effect to the client's character or demon.
bool GMCommand_Enchant (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to set the tarot/soul effects on an equipped item.
bool GMCommand_Enemy (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to spawn an entity in the client's zone.
bool GMCommand_Event (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to start an event or return the current event name.
bool GMCommand_ExpertiseExtend (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to extend a character's max expertise points available.
bool GMCommand_ExpertiseSet (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to update a character's expertise to an explicit rank (and class).
bool GMCommand_Familiarity (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to update the familiarity level of the client's partner demon.
bool GMCommand_Flag (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to display or update a zone or instance flag.
bool GMCommand_FusionGauge (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to update the client's fusion gauge.
bool GMCommand_Goto (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to move one player to another player.
bool GMCommand_GradePoints (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to update a specific player's Grade Points (GP).
bool GMCommand_Help (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to display help for other commands.
bool GMCommand_Homepoint (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to set the client character's homepoint to their current zone's first spawn in point encountered.
bool GMCommand_Instance (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to create a new zone instance and enter it.
bool GMCommand_Item (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to add an item to a character's inventory.
bool GMCommand_Kick (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to kick a player from the channel.
bool GMCommand_Kill (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to kill a character in the same zone.
bool GMCommand_LevelUp (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to level up a character or demon.
bool GMCommand_License (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to print the server license.
bool GMCommand_LNC (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to set a character's LNC alignment value.
bool GMCommand_Map (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to set a character's obtained maps.
bool GMCommand_Online (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to get the number of players on each channel or to determine if a specific character is currently online.
bool GMCommand_PenaltyReset (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to reset a specific player's PvP penalties.
bool GMCommand_Plugin (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to set a character's obtained plugins.
bool GMCommand_Position (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to get a character's position.
bool GMCommand_Post (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to add an item to a character's post.
bool GMCommand_Quest (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to set a specific quest to a specific phase, ignoring prior requirements and state.
bool GMCommand_Reported (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to get reported players that have not been resolved yet.
bool GMCommand_Resolve (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to resolve reported players records.
bool GMCommand_Reunion (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to perform a demon reunion by changing its growth type.
bool GMCommand_Scrap (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to throw away an item in the client or target character's inventory.
bool GMCommand_Skill (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to have the client's character or partner demon learn a skill.
bool GMCommand_SkillPoint (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to have the client's character gain allocatable skill points.
bool GMCommand_SlotAdd (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to add a mod slot to an item equipped by the client's character.
bool GMCommand_SoulPoints (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to have the client's partner demon gain soul points.
bool GMCommand_Spawn (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to refresh all the spawn groups in the client's zone.
bool GMCommand_Speed (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to update the client character or partner demon's running speed.
bool GMCommand_Spirit (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to set the spirit fusion effects on an equipped item.
bool GMCommand_Support (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to set the the client character's SupportDisplay flag.
bool GMCommand_TickerMessage (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to set the default ticker message upon login.
bool GMCommand_Title (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to add an available title to the character.
bool GMCommand_Tokusei (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to add a tokusei to the client's character or partner demon, detached from any item, skill or status effect.
bool GMCommand_Valuable (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to set a character's current valuables.
bool GMCommand_Version (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to print the server version.
bool GMCommand_WorldTime (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to offset the world time (of this channel only) by a specified number of seconds.
bool GMCommand_XP (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to increase the XP of a character or demon.
bool GMCommand_Ziotite (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to update the client's team's ziotite.
bool GMCommand_Zone (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< libcomp::String > &args)
GM command to zone to a new map.
bool HaveUserLevel (const std::shared_ptr< channel::ChannelClientConnection > &client, uint32_t requiredLevel)
Determine if the client has appropriate user level necessary to execute a GMand.
Private Attributes
std::unordered_map< libcomp::String, std::function< bool(ChatManager &, const std::shared_ptr< channel::ChannelClientConnection > &, const std::list< libcomp::String > &)> > mGMands
List of GM command parsers.
std::weak_ptr< ChannelServer > mServer
Pointer to the channel server.
Detailed Description
Manager to handle chat communication and processing of GM commands.
Definition at line 79 of file ChatManager.h.
Constructor & Destructor Documentation
ChatManager()
ChatManager::ChatManager (const std::weak_ptr< ChannelServer > & server)
Create a new ChatManager.
Parameters
server Pointer back to the channel server this belongs to
Definition at line 91 of file ChatManager.cpp.
References GMCommand_AddCP(), GMCommand_Announce(), GMCommand_Ban(), GMCommand_BattlePoints(), GMCommand_Bethel(), GMCommand_Coin(), GMCommand_Contract(), GMCommand_Counter(), GMCommand_Cowrie(), GMCommand_Crash(), GMCommand_DigitalizePoints(), GMCommand_Effect(), GMCommand_Enchant(), GMCommand_Enemy(), GMCommand_Event(), GMCommand_ExpertiseExtend(), GMCommand_ExpertiseSet(), GMCommand_Familiarity(), GMCommand_Flag(), GMCommand_FusionGauge(), GMCommand_Goto(), GMCommand_GradePoints(), GMCommand_Help(), GMCommand_Homepoint(), GMCommand_Instance(), GMCommand_Item(), GMCommand_Kick(), GMCommand_Kill(), GMCommand_LevelUp(), GMCommand_License(), GMCommand_LNC(), GMCommand_Map(), GMCommand_Online(), GMCommand_PenaltyReset(), GMCommand_Plugin(), GMCommand_Position(), GMCommand_Post(), GMCommand_Quest(), GMCommand_Reported(), GMCommand_Resolve(), GMCommand_Reunion(), GMCommand_Scrap(), GMCommand_Skill(), GMCommand_SkillPoint(), GMCommand_SlotAdd(), GMCommand_SoulPoints(), GMCommand_Spawn(), GMCommand_Speed(), GMCommand_Spirit(), GMCommand_Support(), GMCommand_TickerMessage(), GMCommand_Title(), GMCommand_Tokusei(), GMCommand_Valuable(), GMCommand_Version(), GMCommand_WorldTime(), GMCommand_XP(), GMCommand_Ziotite(), GMCommand_Zone(), and mGMands.
~ChatManager()
ChatManager::~ChatManager ()
Clean up the ChatManager.
Definition at line 155 of file ChatManager.cpp.
Member Function Documentation
ExecuteGMCommand()
bool ChatManager::ExecuteGMCommand (const std::shared_ptr< channel::ChannelClientConnection > & client, const libcomp::String & cmd, const std::list< libcomp::String > & args)
Execute a GM command using the supplied arguments.
Parameters
client Pointer to the client that sent the command
cmd Command to execute
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 452 of file ChatManager.cpp.
References LOG_WARNING, and mGMands.
Referenced by HandleGMand().
GetDecimalArg()
template<typename T > bool channel::ChatManager::GetDecimalArg (T & outVal, std::list< libcomp::String > & args) const inline private
Get next argument from the supplied argument list as a float/long type.
Parameters
outVal Output variable to return the argument to
args List of arguments to read and update
Returns
true if there was an argument in the list that was an float/long, else false
Definition at line 845 of file ChatManager.h.
GetEquipTypeArg()
int8_t ChatManager::GetEquipTypeArg (const std::shared_ptr< channel::ChannelClientConnection > & client, std::list< libcomp::String > & args, const libcomp::String & gmandName, const std::set< int8_t > & validTypes) private
Get the valid equip type index associated to the next argument in a list by equip type name or index.
Parameters
client Pointer to the client that sent the command
args List of arguments to read and update
gmandName Name of the gmand being executed
validTypes Equipment type indexes that are valid to return
Returns
Equipment index or -1 if invalid
Definition at line 4044 of file ChatManager.cpp.
References channel::CHAT_SELF, GetIntegerArg(), GetStringArg(), SendChatMessage(), and libcomp::String::ToLower().
Referenced by GMCommand_Enchant(), GMCommand_SlotAdd(), and GMCommand_Spirit().
GetIntegerArg()
template<typename T > bool channel::ChatManager::GetIntegerArg (T & outVal, std::list< libcomp::String > & args) const inline private
Get the next argument from the supplied argument list as an integer type.
Parameters
outVal Output variable to return the integer argument to
args List of arguments to read and update
Returns
true if there was an argument in the list that was an integer, else false
Definition at line 820 of file ChatManager.h.
Referenced by GetEquipTypeArg(), GMCommand_Ban(), GMCommand_BattlePoints(), GMCommand_Bethel(), GMCommand_Coin(), GMCommand_Counter(), GMCommand_Cowrie(), GMCommand_DigitalizePoints(), GMCommand_Enchant(), GMCommand_ExpertiseSet(), GMCommand_FusionGauge(), GMCommand_GradePoints(), GMCommand_Kick(), GMCommand_Reported(), GMCommand_Reunion(), GMCommand_Spirit(), GMCommand_Support(), GMCommand_TickerMessage(), and GMCommand_Ziotite().
GetStringArg()
bool ChatManager::GetStringArg (libcomp::String & outVal, std::list< libcomp::String > & args, libcomp::Convert::Encoding_t encoding = libcomp::Convert::Encoding_t::ENCODING_UTF8) const private
Get the next argument from the supplied argument list as a string.
Parameters
outVal Output variable to return the string argument to
args List of arguments read and update
encoding Optional encoding to use when reading the string. Defaults to UTF8.
Returns
true if there was an argument in the list, else false
Definition at line 4108 of file ChatManager.cpp.
References libcomp::String::At(), libcomp::String::Length(), libcomp::String::Mid(), libcomp::String::Replace(), and libcomp::Convert::ToEncoding().
Referenced by GetEquipTypeArg(), GMCommand_AddCP(), GMCommand_Ban(), GMCommand_Contract(), GMCommand_Counter(), GMCommand_Effect(), GMCommand_Enemy(), GMCommand_Event(), GMCommand_Flag(), GMCommand_Goto(), GMCommand_GradePoints(), GMCommand_Item(), GMCommand_Kick(), GMCommand_Kill(), GMCommand_LevelUp(), GMCommand_Online(), GMCommand_PenaltyReset(), GMCommand_Post(), GMCommand_Reported(), GMCommand_Resolve(), GMCommand_Scrap(), GMCommand_Skill(), GMCommand_Speed(), GMCommand_Tokusei(), and GMCommand_XP().
GetTargetCharacterAccount()
bool ChatManager::GetTargetCharacterAccount (libcomp::String & targetName, bool currentOnly, std::shared_ptr< objects::Character > & targetCharacter, std::shared_ptr< objects::Account > & targetAccount, std::shared_ptr< channel::ChannelClientConnection > & targetClient) private
Get channel accessible character, account and client pointers based upon the supplied character name.
If the character's account is logged in as a different character on the channel, the client will still be returned unless otherwise specified.
Parameters
targetName Name of the character to retrieve information from
currentOnly If true, the client will not be returned if the account is logged into the channel but not as the specified character
targetCharacter Output pointer to the retrieved character
targetAccount Output pointer to the retrieved character's account
targetClient Output pointer to the retrieved character's client
Returns
true if the character and account exist, false if they do not
Definition at line 4008 of file ChatManager.cpp.
References channel::ClientState::GetCharacterState(), libcomp::PersistentObject::LoadObjectByUUID(), mServer, and channel::state().
Referenced by GMCommand_AddCP(), GMCommand_Ban(), GMCommand_Counter(), GMCommand_Goto(), GMCommand_GradePoints(), GMCommand_Kick(), and GMCommand_PenaltyReset().
GMCommand_AddCP()
bool ChatManager::GMCommand_AddCP (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to add CP to a target account.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 469 of file ChatManager.cpp.
References channel::CHAT_SELF, GetStringArg(), GetTargetCharacterAccount(), HaveUserLevel(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Announce()
bool ChatManager::GMCommand_Announce (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to announce message to server .
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 538 of file ChatManager.cpp.
References channel::CHAT_SELF, HaveUserLevel(), libcomp::String::Join(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Ban()
bool ChatManager::GMCommand_Ban (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to ban a player currently on the channel.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 563 of file ChatManager.cpp.
References channel::CHAT_SELF, GetIntegerArg(), GetStringArg(), GetTargetCharacterAccount(), HaveUserLevel(), mServer, SendChatMessage(), SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().
Referenced by ChatManager().
GMCommand_BattlePoints()
bool ChatManager::GMCommand_BattlePoints (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to update the client's Battle Points (BP).
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 638 of file ChatManager.cpp.
References channel::CHAT_SELF, GetIntegerArg(), HaveUserLevel(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Bethel()
bool ChatManager::GMCommand_Bethel (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to update the client's bethel directly.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 675 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetCharacterState(), GetIntegerArg(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Coin()
bool ChatManager::GMCommand_Coin (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to set the total casino coins the character has.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 716 of file ChatManager.cpp.
References channel::CHAT_SELF, GetIntegerArg(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Contract()
bool ChatManager::GMCommand_Contract (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to add a demon to a character's COMP.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 752 of file ChatManager.cpp.
References channel::CHAT_SELF, GetStringArg(), HaveUserLevel(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Counter()
bool ChatManager::GMCommand_Counter (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to view a world level or view/change a character level counter.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 799 of file ChatManager.cpp.
References channel::CHAT_SELF, GetIntegerArg(), GetStringArg(), GetTargetCharacterAccount(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Cowrie()
bool ChatManager::GMCommand_Cowrie (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to update the client's current cowrie.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 876 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetCharacterState(), GetIntegerArg(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Crash()
bool ChatManager::GMCommand_Crash (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to crash the server (for testing).
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 913 of file ChatManager.cpp.
References HaveUserLevel(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_DigitalizePoints()
bool ChatManager::GMCommand_DigitalizePoints (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to gain digitalize points.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 928 of file ChatManager.cpp.
References channel::CHAT_SELF, GetIntegerArg(), HaveUserLevel(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Effect()
bool ChatManager::GMCommand_Effect (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to apply a status effect to the client's character or demon.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 970 of file ChatManager.cpp.
References libcomp::String::C(), channel::CHAT_SELF, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetStringArg(), HaveUserLevel(), libcomp::String::IsEmpty(), mServer, SendChatMessage(), channel::state(), SVR_CONST, and libcomp::String::ToLower().
Referenced by ChatManager().
GMCommand_Enchant()
bool ChatManager::GMCommand_Enchant (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to set the tarot/soul effects on an equipped item.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 1036 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), GetEquipTypeArg(), GetIntegerArg(), libcomp::PersistentObject::GetObjectByUUID(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Enemy()
bool ChatManager::GMCommand_Enemy (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to spawn an entity in the client's zone.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 1136 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetCharacterState(), channel::ChannelServer::GetServerTime(), GetStringArg(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Event()
bool ChatManager::GMCommand_Event (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to start an event or return the current event name.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 1234 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetCharacterState(), GetStringArg(), HaveUserLevel(), libcomp::String::IsEmpty(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_ExpertiseExtend()
bool ChatManager::GMCommand_ExpertiseExtend (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to extend a character's max expertise points available.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 1307 of file ChatManager.cpp.
References channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), HaveUserLevel(), mServer, channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_ExpertiseSet()
bool ChatManager::GMCommand_ExpertiseSet (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to update a character's expertise to an explicit rank (and class).
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 1351 of file ChatManager.cpp.
References channel::ClientState::GetCharacterState(), GetIntegerArg(), HaveUserLevel(), mServer, channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Familiarity()
bool ChatManager::GMCommand_Familiarity (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to update the familiarity level of the client's partner demon.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 1396 of file ChatManager.cpp.
References HaveUserLevel(), mServer, and SVR_CONST.
Referenced by ChatManager().
GMCommand_Flag()
bool ChatManager::GMCommand_Flag (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to display or update a zone or instance flag.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 1420 of file ChatManager.cpp.
References channel::CHAT_SELF, GetStringArg(), HaveUserLevel(), SendChatMessage(), SVR_CONST, and libcomp::String::ToLower().
Referenced by ChatManager().
GMCommand_FusionGauge()
bool ChatManager::GMCommand_FusionGauge (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to update the client's fusion gauge.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 1543 of file ChatManager.cpp.
References GetIntegerArg(), HaveUserLevel(), mServer, and SVR_CONST.
Referenced by ChatManager().
GMCommand_Goto()
bool ChatManager::GMCommand_Goto (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to move one player to another player.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 1567 of file ChatManager.cpp.
References channel::CHAT_SELF, GetStringArg(), GetTargetCharacterAccount(), HaveUserLevel(), libcomp::String::IsEmpty(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_GradePoints()
bool ChatManager::GMCommand_GradePoints (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to update a specific player's Grade Points (GP).
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 1650 of file ChatManager.cpp.
References channel::CHAT_SELF, GetIntegerArg(), GetStringArg(), GetTargetCharacterAccount(), HaveUserLevel(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Help()
bool ChatManager::GMCommand_Help (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to display help for other commands.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 1717 of file ChatManager.cpp.
References channel::CHAT_SELF, HaveUserLevel(), libcomp::String::IsEmpty(), SendChatMessage(), SVR_CONST, libcomp::String::ToLower(), and libcomp::String::ToUtf8().
Referenced by ChatManager().
GMCommand_Homepoint()
bool ChatManager::GMCommand_Homepoint (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to set the client character's homepoint to their current zone's first spawn in point encountered.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2079 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), SVR_CONST, libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by ChatManager().
GMCommand_Instance()
bool ChatManager::GMCommand_Instance (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to create a new zone instance and enter it.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2124 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Item()
bool ChatManager::GMCommand_Item (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to add an item to a character's inventory.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2236 of file ChatManager.cpp.
References GetStringArg(), HaveUserLevel(), mServer, SVR_CONST, and libcomp::String::ToLower().
Referenced by ChatManager().
GMCommand_Kick()
bool ChatManager::GMCommand_Kick (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to kick a player from the channel.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2293 of file ChatManager.cpp.
References channel::CHAT_SELF, GetIntegerArg(), GetStringArg(), GetTargetCharacterAccount(), HaveUserLevel(), mServer, SendChatMessage(), SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().
Referenced by ChatManager().
GMCommand_Kill()
bool ChatManager::GMCommand_Kill (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to kill a character in the same zone.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2363 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetCharacterState(), GetStringArg(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), SVR_CONST, libcomp::Packet::WriteBlank(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by ChatManager().
GMCommand_LevelUp()
bool ChatManager::GMCommand_LevelUp (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to level up a character or demon.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2455 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetStringArg(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), SVR_CONST, and libcomp::String::ToLower().
Referenced by ChatManager().
GMCommand_License()
bool ChatManager::GMCommand_License (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to print the server license.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2522 of file ChatManager.cpp.
References channel::CHAT_SELF, and SendChatMessage().
Referenced by ChatManager().
GMCommand_LNC()
bool ChatManager::GMCommand_LNC (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to set a character's LNC alignment value.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2562 of file ChatManager.cpp.
References HaveUserLevel(), mServer, and SVR_CONST.
Referenced by ChatManager().
GMCommand_Map()
bool ChatManager::GMCommand_Map (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to set a character's obtained maps.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2585 of file ChatManager.cpp.
References HaveUserLevel(), mServer, and SVR_CONST.
Referenced by ChatManager().
GMCommand_Online()
bool ChatManager::GMCommand_Online (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to get the number of players on each channel or to determine if a specific character is currently online.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2608 of file ChatManager.cpp.
References channel::CHAT_SELF, GetStringArg(), HaveUserLevel(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_PenaltyReset()
bool ChatManager::GMCommand_PenaltyReset (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to reset a specific player's PvP penalties.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2677 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetCharacterState(), GetStringArg(), GetTargetCharacterAccount(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Plugin()
bool ChatManager::GMCommand_Plugin (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to set a character's obtained plugins.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2724 of file ChatManager.cpp.
References channel::CHAT_SELF, HaveUserLevel(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Position()
bool ChatManager::GMCommand_Position (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to get a character's position.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2751 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Post()
bool ChatManager::GMCommand_Post (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to add an item to a character's post.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2802 of file ChatManager.cpp.
References channel::CHAT_SELF, GetStringArg(), HaveUserLevel(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Quest()
bool ChatManager::GMCommand_Quest (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to set a specific quest to a specific phase, ignoring prior requirements and state.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3107 of file ChatManager.cpp.
References channel::CHAT_SELF, HaveUserLevel(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Reported()
bool ChatManager::GMCommand_Reported (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to get reported players that have not been resolved yet.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2860 of file ChatManager.cpp.
References channel::CHAT_SELF, GetIntegerArg(), GetStringArg(), HaveUserLevel(), libcomp::String::IsEmpty(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Resolve()
bool ChatManager::GMCommand_Resolve (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to resolve reported players records.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 2973 of file ChatManager.cpp.
References libcomp::String::C(), channel::CHAT_SELF, channel::ClientState::GetAccountUID(), GetStringArg(), HaveUserLevel(), libcomp::PersistentObject::LoadObjectByUUID(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Reunion()
bool ChatManager::GMCommand_Reunion (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to perform a demon reunion by changing its growth type.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3032 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetDemonState(), GetIntegerArg(), channel::ClientState::GetObjectID(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Scrap()
bool ChatManager::GMCommand_Scrap (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to throw away an item in the client or target character's inventory.
Useful for destroying items that cannot be stored or thrown away.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3148 of file ChatManager.cpp.
References channel::CHAT_SELF, GetStringArg(), HaveUserLevel(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Skill()
bool ChatManager::GMCommand_Skill (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to have the client's character or partner demon learn a skill.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3230 of file ChatManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetStringArg(), HaveUserLevel(), mServer, channel::state(), SVR_CONST, and libcomp::String::ToLower().
Referenced by ChatManager().
GMCommand_SkillPoint()
bool ChatManager::GMCommand_SkillPoint (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to have the client's character gain allocatable skill points.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3268 of file ChatManager.cpp.
References HaveUserLevel(), mServer, and SVR_CONST.
Referenced by ChatManager().
GMCommand_SlotAdd()
bool ChatManager::GMCommand_SlotAdd (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to add a mod slot to an item equipped by the client's character.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3291 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), GetEquipTypeArg(), libcomp::PersistentObject::GetObjectByUUID(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_SoulPoints()
bool ChatManager::GMCommand_SoulPoints (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to have the client's partner demon gain soul points.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3357 of file ChatManager.cpp.
References HaveUserLevel(), mServer, and SVR_CONST.
Referenced by ChatManager().
GMCommand_Spawn()
bool ChatManager::GMCommand_Spawn (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to refresh all the spawn groups in the client's zone.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3380 of file ChatManager.cpp.
References HaveUserLevel(), mServer, and SVR_CONST.
Referenced by ChatManager().
GMCommand_Speed()
bool ChatManager::GMCommand_Speed (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to update the client character or partner demon's running speed.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3399 of file ChatManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetStringArg(), HaveUserLevel(), mServer, channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Spirit()
bool ChatManager::GMCommand_Spirit (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to set the spirit fusion effects on an equipped item.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3441 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), GetEquipTypeArg(), GetIntegerArg(), libcomp::PersistentObject::GetObjectByUUID(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Support()
bool ChatManager::GMCommand_Support (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to set the the client character's SupportDisplay flag.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3581 of file ChatManager.cpp.
References channel::CHAT_SELF, GetIntegerArg(), HaveUserLevel(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_TickerMessage()
bool ChatManager::GMCommand_TickerMessage (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to set the default ticker message upon login.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled problerly, else false
Definition at line 3611 of file ChatManager.cpp.
References channel::CHAT_SELF, GetIntegerArg(), HaveUserLevel(), libcomp::String::Join(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Title()
bool ChatManager::GMCommand_Title (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to add an available title to the character.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled problerly, else false
Definition at line 3643 of file ChatManager.cpp.
References HaveUserLevel(), mServer, and SVR_CONST.
Referenced by ChatManager().
GMCommand_Tokusei()
bool ChatManager::GMCommand_Tokusei (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to add a tokusei to the client's character or partner demon, detached from any item, skill or status effect.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled problerly, else false
Definition at line 3666 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetStringArg(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), SVR_CONST, and libcomp::String::ToLower().
Referenced by ChatManager().
GMCommand_Valuable()
bool ChatManager::GMCommand_Valuable (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to set a character's current valuables.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3734 of file ChatManager.cpp.
References channel::CHAT_SELF, HaveUserLevel(), mServer, SendChatMessage(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Version()
bool ChatManager::GMCommand_Version (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to print the server version.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3762 of file ChatManager.cpp.
References channel::CHAT_SELF, and SendChatMessage().
Referenced by ChatManager().
GMCommand_WorldTime()
bool ChatManager::GMCommand_WorldTime (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to offset the world time (of this channel only) by a specified number of seconds.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3785 of file ChatManager.cpp.
References HaveUserLevel(), mServer, SVR_CONST, libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS8().
Referenced by ChatManager().
GMCommand_XP()
bool ChatManager::GMCommand_XP (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to increase the XP of a character or demon.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3963 of file ChatManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetStringArg(), HaveUserLevel(), mServer, channel::state(), SVR_CONST, and libcomp::String::ToLower().
Referenced by ChatManager().
GMCommand_Ziotite()
bool ChatManager::GMCommand_Ziotite (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to update the client's team's ziotite.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3819 of file ChatManager.cpp.
References channel::CHAT_SELF, GetIntegerArg(), channel::ClientState::GetWorldCID(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
GMCommand_Zone()
bool ChatManager::GMCommand_Zone (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< libcomp::String > & args) private
GM command to zone to a new map.
Parameters
client Pointer to the client that sent the command
args List of arguments for the command
Returns
true if the command was handled properly, else false
Definition at line 3865 of file ChatManager.cpp.
References channel::CHAT_SELF, channel::ClientState::GetCharacterState(), HaveUserLevel(), mServer, SendChatMessage(), channel::state(), and SVR_CONST.
Referenced by ChatManager().
HandleGMand()
bool ChatManager::HandleGMand (const std::shared_ptr< ChannelClientConnection > & client, const libcomp::String & message)
Determine if a message being sent should be handled as a GMand.
Parameters
client Pointer to the client that sent the message
message Message that may be a GMand
Returns
true if the message was a GMand, false if it should be sent as a message
Definition at line 399 of file ChatManager.cpp.
References libcomp::String::C(), ExecuteGMCommand(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetUserLevel(), libcomp::String::IsEmpty(), LOG_DEBUG, LOG_INFO, LOG_WARNING, mServer, libcomp::String::Split(), channel::state(), and libcomp::String::ToLower().
HaveUserLevel()
bool ChatManager::HaveUserLevel (const std::shared_ptr< channel::ChannelClientConnection > & client, uint32_t requiredLevel) private
Determine if the client has appropriate user level necessary to execute a GMand.
If the client's level is too low, a message will be returned informing them of the error.
Parameters
client Pointer to the client that sent the command
requiredLevel User level required to execute the GMand
Returns
true if the client has the necessary user level
Definition at line 3993 of file ChatManager.cpp.
References channel::CHAT_SELF, and SendChatMessage().
Referenced by GMCommand_AddCP(), GMCommand_Announce(), GMCommand_Ban(), GMCommand_BattlePoints(), GMCommand_Bethel(), GMCommand_Coin(), GMCommand_Contract(), GMCommand_Counter(), GMCommand_Cowrie(), GMCommand_Crash(), GMCommand_DigitalizePoints(), GMCommand_Effect(), GMCommand_Enchant(), GMCommand_Enemy(), GMCommand_Event(), GMCommand_ExpertiseExtend(), GMCommand_ExpertiseSet(), GMCommand_Familiarity(), GMCommand_Flag(), GMCommand_FusionGauge(), GMCommand_Goto(), GMCommand_GradePoints(), GMCommand_Help(), GMCommand_Homepoint(), GMCommand_Instance(), GMCommand_Item(), GMCommand_Kick(), GMCommand_Kill(), GMCommand_LevelUp(), GMCommand_LNC(), GMCommand_Map(), GMCommand_Online(), GMCommand_PenaltyReset(), GMCommand_Plugin(), GMCommand_Position(), GMCommand_Post(), GMCommand_Quest(), GMCommand_Reported(), GMCommand_Resolve(), GMCommand_Reunion(), GMCommand_Scrap(), GMCommand_Skill(), GMCommand_SkillPoint(), GMCommand_SlotAdd(), GMCommand_SoulPoints(), GMCommand_Spawn(), GMCommand_Speed(), GMCommand_Spirit(), GMCommand_Support(), GMCommand_TickerMessage(), GMCommand_Title(), GMCommand_Tokusei(), GMCommand_Valuable(), GMCommand_WorldTime(), GMCommand_XP(), GMCommand_Ziotite(), and GMCommand_Zone().
SendChatMessage()
bool ChatManager::SendChatMessage (const std::shared_ptr< channel::ChannelClientConnection > & client, ChatType_t chatChannel, const libcomp::String & message)
Send a chat message to the specified chat channel.
Parameters
client Pointer to the client that sent the message
chatChannel Channel to send the chat message to
message Message to send
Returns
true if the message was handled properly, else false
Definition at line 159 of file ChatManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::CHAT_CLAN, channel::CHAT_PARTY, channel::CHAT_SAY, channel::CHAT_SELF, channel::CHAT_SHOUT, channel::CHAT_TEAM, channel::CHAT_VERSUS, channel::CHAT_VIS_CLAN, channel::CHAT_VIS_PARTY, channel::CHAT_VIS_RANGE, channel::CHAT_VIS_SELF, channel::CHAT_VIS_TEAM, channel::CHAT_VIS_VERSUS, channel::CHAT_VIS_ZONE, channel::ClientState::GetCharacterState(), channel::ClientState::GetClanID(), channel::ClientState::GetClientStringEncoding(), channel::ClientState::GetPartyID(), channel::ClientState::GetTeamID(), channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), libcomp::String::IsEmpty(), LOG_ERROR, LOG_INFO, mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteU16Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by GetEquipTypeArg(), GMCommand_AddCP(), GMCommand_Announce(), GMCommand_Ban(), GMCommand_BattlePoints(), GMCommand_Bethel(), GMCommand_Coin(), GMCommand_Contract(), GMCommand_Counter(), GMCommand_Cowrie(), GMCommand_DigitalizePoints(), GMCommand_Effect(), GMCommand_Enchant(), GMCommand_Enemy(), GMCommand_Event(), GMCommand_Flag(), GMCommand_Goto(), GMCommand_GradePoints(), GMCommand_Help(), GMCommand_Homepoint(), GMCommand_Instance(), GMCommand_Kick(), GMCommand_Kill(), GMCommand_LevelUp(), GMCommand_License(), GMCommand_Online(), GMCommand_PenaltyReset(), GMCommand_Plugin(), GMCommand_Position(), GMCommand_Post(), GMCommand_Quest(), GMCommand_Reported(), GMCommand_Resolve(), GMCommand_Reunion(), GMCommand_Scrap(), GMCommand_SlotAdd(), GMCommand_Spirit(), GMCommand_Support(), GMCommand_TickerMessage(), GMCommand_Tokusei(), GMCommand_Valuable(), GMCommand_Version(), GMCommand_Ziotite(), GMCommand_Zone(), HaveUserLevel(), and SendTeamChatMessage().
SendTeamChatMessage()
bool ChatManager::SendTeamChatMessage (const std::shared_ptr< ChannelClientConnection > & client, const libcomp::String & message, int32_t teamID)
Send a chat message to the client's team.
Parameters
client Pointer to the client that sent the message
message Message to send
teamID ID of the team the client belongs to. If it does not match, the message will not be sent.
Returns
true if the message was handled properly, else false
Definition at line 386 of file ChatManager.cpp.
References channel::CHAT_TEAM, channel::ClientState::GetTeamID(), SendChatMessage(), and channel::state().
SendTellMessage()
bool ChatManager::SendTellMessage (const std::shared_ptr< ChannelClientConnection > & client, const libcomp::String & message, const libcomp::String & targetName)
Send a tell message to the specified character.
Parameters
client Pointer to the client that sent the message
message Message to send
targetName Name of the player the message is sending to
Returns
true if the message was handled properly, else false
Definition at line 354 of file ChatManager.cpp.
References channel::CHAT_TELL, channel::ClientState::GetCharacterState(), channel::ClientState::GetClientStringEncoding(), channel::ClientState::GetWorldCID(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU8().
Member Data Documentation
mGMands
std::unordered_map<libcomp::String, std::function<bool(ChatManager&, const std::shared_ptr<channel::ChannelClientConnection>&, const std::list<libcomp::String>&)> > channel::ChatManager::mGMands private
List of GM command parsers.
Definition at line 868 of file ChatManager.h.
Referenced by ChatManager(), and ExecuteGMCommand().
mServer
std::weak_ptr<ChannelServer> channel::ChatManager::mServer private
Pointer to the channel server.
Definition at line 863 of file ChatManager.h.
Referenced by GetTargetCharacterAccount(), GMCommand_AddCP(), GMCommand_Announce(), GMCommand_Ban(), GMCommand_BattlePoints(), GMCommand_Bethel(), GMCommand_Coin(), GMCommand_Contract(), GMCommand_Counter(), GMCommand_Cowrie(), GMCommand_DigitalizePoints(), GMCommand_Effect(), GMCommand_Enchant(), GMCommand_Enemy(), GMCommand_Event(), GMCommand_ExpertiseExtend(), GMCommand_ExpertiseSet(), GMCommand_Familiarity(), GMCommand_FusionGauge(), GMCommand_Goto(), GMCommand_GradePoints(), GMCommand_Homepoint(), GMCommand_Instance(), GMCommand_Item(), GMCommand_Kick(), GMCommand_Kill(), GMCommand_LevelUp(), GMCommand_LNC(), GMCommand_Map(), GMCommand_Online(), GMCommand_PenaltyReset(), GMCommand_Plugin(), GMCommand_Position(), GMCommand_Post(), GMCommand_Quest(), GMCommand_Reported(), GMCommand_Resolve(), GMCommand_Reunion(), GMCommand_Scrap(), GMCommand_Skill(), GMCommand_SkillPoint(), GMCommand_SlotAdd(), GMCommand_SoulPoints(), GMCommand_Spawn(), GMCommand_Speed(), GMCommand_Spirit(), GMCommand_Support(), GMCommand_TickerMessage(), GMCommand_Title(), GMCommand_Tokusei(), GMCommand_Valuable(), GMCommand_WorldTime(), GMCommand_XP(), GMCommand_Ziotite(), GMCommand_Zone(), HandleGMand(), SendChatMessage(), and SendTellMessage().
The documentation for this class was generated from the following files:
ChatManager.h
ChatManager.cpp