COMP_hack: MitamaReset.cpp File Reference
MitamaReset.cpp File Reference
Request from the client to reset a mitama reunion growth path.
#include "Packets.h"
#include <ManagerPacket.h>
#include <Packet.h>
#include <PacketCodes.h>
#include "ChannelServer.h"
#include "CharacterManager.h"
#include "EventManager.h"
#include "TokuseiManager.h"
Functions
void HandleMitamaReset (const std::shared_ptr< ChannelServer > server, const std::shared_ptr< ChannelClientConnection > client, int8_t reunionIdx)
Detailed Description
Request from the client to reset a mitama reunion growth path.
Author
HACKfrost
This file is part of the Channel Server (channel).
Copyright (C) 2012-2018 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file MitamaReset.cpp.
Function Documentation
void HandleMitamaReset (const std::shared_ptr< ChannelServer > server, const std::shared_ptr< ChannelClientConnection > client, int8_t reunionIdx)
Definition at line 42 of file MitamaReset.cpp.
References libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetCharacterState(), channel::ClientState::GetCurrentMenuShopID(), channel::ClientState::GetDemonState(), libcomp::ManagerPacket::GetServer(), libcomp::ReadOnlyPacket::ReadS8(), libcomp::ReadOnlyPacket::Size(), channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS8().