COMP_hack: channel Namespace Reference
channel Namespace Reference
Namespaces
Parsers
Classes
class AccountManager
Manager to handle Account focused actions.
class ActionManager
Class to manage actions when triggering a spot or interacting with an object/NPC.
struct ActionOptions
Struct containing optional parameters supplied to ActionManager::PerformActions to simplify the function signature.
class ActiveEntityState
Represents an active entity on the channel server.
class ActiveEntityStateImp
Contains the state of an active entity related to a channel.
class AICommand
Base class for all AI commands to be handled by the AIManager on server ticks.
class AIManager
Class to manage actions when triggering a spot or interacting with an object/NPC.
class AIMoveCommand
AI command defining where the entity will move and contains pathing information about how to get there.
class AIScriptedCommand
AI command used to execute a script function bound to an AIState.
class AIState
Contains the state of an entity's AI information when controlled by the channel.
class AIUseSkillCommand
AI command used to activate or execute a skill.
class AllyState
Contains the state of an ally entity related to a channel as well as functionality to be used by the scripting engine for AI.
class BazaarState
Contains the state of an bazaar related to a channel.
class ChannelClientConnection
Represents a connection to the game client.
class ChannelServer
Channel server that handles client packets in game.
class ChannelSyncManager
Channel specific implementation of the DataSyncManager in charge of performing server side update operations.
class CharacterManager
Manager to handle Character focused actions.
class CharacterState
Contains the state of a player character on the channel.
class ChatManager
Manager to handle chat communication and processing of GM commands.
class ClientState
Contains the state of a game client currently connected to the channel.
class CultureMachineState
Contains the state of a culture machine related to a channel.
class DemonState
Contains the state of a partner demon related to a channel.
class DynamicMap
Container for dynamic map geometry information.
class EnemyState
Contains the state of an enemy related to a channel as well as functionality to be used by the scripting engine for AI.
class EntityState
Contains the state of a non-active entity related to a channel.
class EventManager
Manager class in charge of processing event sequences as well as quest phase progression and condition evaluation.
struct EventOptions
Struct containing optional parameters supplied to EventManager::HandleEvent to simplify the function signature.
class FusionManager
Manager class used to handle all demon fusion based actions.
class Line
Pair of points representing a line.
class ManagerClientPacket
Manager class responsible for handling client side packets.
class ManagerConnection
Class to handle messages pertaining to connecting to the world or game clients.
class ManagerSystem
Class to handle messages pertaining to connecting to the world or game clients.
class MatchManager
Manager class used to handle all channel side match logic.
class PerformanceTimer
Timer to measure performance of a task.
class PlasmaPoint
Represents a specific point within a plasma state.
class PlasmaState
Contains the state of an plasma spawn related to a channel.
class Point
Simple X, Y coordinate point.
class ProcessingSkill
class SkillExecutionContext
Container for skill execution contextual parameters.
class SkillManager
Manager to handle skill focused actions.
class SkillTargetResult
class StatusEffectChange
Represents a request to add or remove a status effect with any applicable modifications to the normal definition.
class TokuseiManager
Manages tokusei specific logic for the server and validates the definitions read at run time.
class WorldClock
Multi-number representation of the time in the current world containing more time information than WorldClockTime as well as an adjustable offset and calculation info.
class WorldClockTime
Multi-number representation of the time in the current world.
class Zone
Represents a server zone containing client connections, objects, enemies, etc.
class ZoneGeometry
Represents all zone geometry retrieved from a QMP file for use in calculating collisions.
class ZoneGeometryLoader
Loader for QMP zone geometry.
class ZoneInstance
Represents an instance of a zone instance containing one or more non-global zone instances.
class ZoneManager
Manager to handle zone focused actions.
class ZoneQmpShape
Represents a shape created from QMP file collisions.
class ZoneShape
Represents a multi-point shape in a particular zone to be used for calculating collisions.
class ZoneSpotShape
Represents a shape created from zone spot data.
Typedefs
typedef std::unordered_map< uint16_t, std::list< AISkillWeight_t > > AISkillMap_t
typedef std::pair< std::shared_ptr< objects::MiSkillData >, uint16_t > AISkillWeight_t
typedef float ClientTime
typedef EntityState< objects::DiasporaBase > DiasporaBaseState
typedef objects::EntityStateObject::EntityType_t EntityType_t
typedef ServerTime(* GET_SERVER_TIME) ()
typedef objects::ServerZoneInstanceVariant::InstanceType_t InstanceType_t
typedef EntityState< objects::LootBox > LootBoxState
typedef EntityState< objects::ServerNPC > NPCState
typedef EntityState< objects::PvPBase > PvPBaseState
typedef std::unordered_map< uint32_t, uint64_t > RelativeTimeMap
typedef EntityState< objects::ServerObject > ServerObjectState
typedef uint64_t ServerTime
typedef std::unordered_map< uint32_t, StatusEffectChange > StatusEffectChanges
typedef objects::ServerZoneTrigger::Trigger_t ZoneTrigger_t
Enumerations
enum ActionRunScriptResult_t : int8_t { SUCCESS = 0, FAIL = -1, LOG_OFF = -2 }
Possible results from an ActionRunScript action returned from the script being executed.
enum AICommandType_t : uint8_t { NONE = 0, MOVE, USE_SKILL, SCRIPTED }
Type of AI command used to specify what should happen to an AI controlled entity upon state update.
enum AIStatus_t : uint8_t { IDLE = 0, WANDERING, AGGRO, COMBAT }
Possible AI statuses for an active AI controlled entity.
enum ChatType_t : uint16_t {
CHAT_PARTY = 41, CHAT_SHOUT = 44, CHAT_SAY = 45, CHAT_TELL = 46,
CHAT_SELF = 47, CHAT_CLAN = 48, CHAT_VERSUS = 597, CHAT_TEAM = 714
}
Chat type sent from and returned to the client to signify what type of chat message is being sent.
enum ChatVis_t : uint16_t {
CHAT_VIS_SELF, CHAT_VIS_PARTY, CHAT_VIS_ZONE, CHAT_VIS_RANGE,
CHAT_VIS_CLAN, CHAT_VIS_VERSUS, CHAT_VIS_TEAM
}
enum LogoutCode_t : uint8_t {
LOGOUT_CODE_UNKNOWN_MIN = 5, LOGOUT_CODE_QUIT = 6, LOGOUT_CODE_CANCEL = 7, LOGOUT_CODE_SWITCH = 8,
LOGOUT_CODE_UNKNOWN_MAX = 9
}
Codes sent from the client to request a logout related action.
Functions
template<>
void ChannelSyncManager::SyncComplete< objects::CharacterLogin > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
void ChannelSyncManager::SyncComplete< objects::InstanceAccess > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
void ChannelSyncManager::SyncComplete< objects::MatchEntry > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
void ChannelSyncManager::SyncComplete< objects::PvPMatch > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
void ChannelSyncManager::SyncComplete< objects::UBResult > (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<>
int8_t ChannelSyncManager::Update< objects::EventCounter > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t ChannelSyncManager::Update< objects::PentalphaMatch > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t ChannelSyncManager::Update< objects::SearchEntry > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t ChannelSyncManager::Update< objects::UBTournament > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
static ClientState * state (const std::shared_ptr< libcomp::TcpConnection > &connection)
Variables
const uint16_t AI_SKILL_TYPE_CLSR = 0x01
AI skill type for close ranged attacks.
const uint16_t AI_SKILL_TYPE_DEF = 0x04
AI skill type for defensive skills.
const uint16_t AI_SKILL_TYPE_HEAL = 0x08
AI skill type for healing skills.
const uint16_t AI_SKILL_TYPE_LNGR = 0x02
AI skill type for long ranged attacks.
const uint16_t AI_SKILL_TYPE_SUPPORT = 0x10
AI skill type for support skills.
const uint16_t AI_SKILL_TYPES_ALL = 0x1F
AI skill type mask for all skills.
const uint16_t AI_SKILL_TYPES_ALLY = 0x1C
AI skill type mask for ally affecting skills.
const uint16_t AI_SKILL_TYPES_ENEMY = 0x03
AI skill type mask for enemy affecting skills.
Typedef Documentation
AISkillMap_t
typedef std::unordered_map<uint16_t, std::list<AISkillWeight_t> > channel::AISkillMap_t
Definition at line 73 of file AIState.h.
AISkillWeight_t
typedef std::pair< std::shared_ptr<objects::MiSkillData>, uint16_t> channel::AISkillWeight_t
Definition at line 72 of file AIState.h.
ClientTime
typedef float channel::ClientTime
Definition at line 55 of file ClientState.h.
DiasporaBaseState
typedef EntityState<objects::DiasporaBase> channel::DiasporaBaseState
Definition at line 68 of file Zone.h.
EntityType_t
typedef objects::EntityStateObject::EntityType_t channel::EntityType_t
Definition at line 36 of file EntityState.h.
GET_SERVER_TIME
typedef ServerTime(* channel::GET_SERVER_TIME) ()
Definition at line 59 of file ChannelServer.h.
InstanceType_t
typedef objects::ServerZoneInstanceVariant::InstanceType_t channel::InstanceType_t
Definition at line 76 of file Zone.h.
LootBoxState
typedef EntityState<objects::LootBox> channel::LootBoxState
Definition at line 71 of file Zone.h.
NPCState
typedef EntityState<objects::ServerNPC> channel::NPCState
Definition at line 72 of file Zone.h.
PvPBaseState
typedef EntityState<objects::PvPBase> channel::PvPBaseState
Definition at line 73 of file Zone.h.
RelativeTimeMap
typedef std::unordered_map<uint32_t, uint64_t> channel::RelativeTimeMap
Definition at line 39 of file ChannelClientConnection.h.
ServerObjectState
typedef EntityState<objects::ServerObject> channel::ServerObjectState
Definition at line 74 of file Zone.h.
ServerTime
typedef uint64_t channel::ServerTime
Definition at line 58 of file ChannelServer.h.
StatusEffectChanges
typedef std::unordered_map<uint32_t, StatusEffectChange> channel::StatusEffectChanges
Definition at line 169 of file ActiveEntityState.h.
ZoneTrigger_t
typedef objects::ServerZoneTrigger::Trigger_t channel::ZoneTrigger_t
Definition at line 57 of file ZoneManager.h.
Enumeration Type Documentation
ActionRunScriptResult_t
enum channel::ActionRunScriptResult_t : int8_t
Possible results from an ActionRunScript action returned from the script being executed.
Enumerator
SUCCESS
No error.
FAIL
Generic failure.
LOG_OFF
Not a failure but log off the client.
Definition at line 56 of file ActionManager.h.
AICommandType_t
enum channel::AICommandType_t : uint8_t
Type of AI command used to specify what should happen to an AI controlled entity upon state update.
Enumerator
NONE
No special action is taken but the entity may still wait.
MOVE
Entity moves from one point to another.
USE_SKILL
Entity is either activating or executing a skill.
SCRIPTED
Entity is executing a function on.
Definition at line 49 of file AICommand.h.
AIStatus_t
enum channel::AIStatus_t : uint8_t
Possible AI statuses for an active AI controlled entity.
Enumerator
IDLE
Entity is either stationary or otherwise not active.
WANDERING
Enemy entity is wandering around its spawn location.
AGGRO
Entity is not in combat yet but is pursuing a target.
COMBAT
Entity is engaged in combat with one or more opponent.
Definition at line 78 of file AIState.h.
ChatType_t
enum channel::ChatType_t : uint16_t
Chat type sent from and returned to the client to signify what type of chat message is being sent.
This value is used to determine the ChatVis_t level.
Enumerator
CHAT_PARTY
CHAT_SHOUT
CHAT_SAY
CHAT_TELL
CHAT_SELF
CHAT_CLAN
CHAT_VERSUS
CHAT_TEAM
Definition at line 48 of file ChatManager.h.
ChatVis_t
enum channel::ChatVis_t : uint16_t
Enumerator
CHAT_VIS_SELF
CHAT_VIS_PARTY
CHAT_VIS_ZONE
CHAT_VIS_RANGE
CHAT_VIS_CLAN
CHAT_VIS_VERSUS
CHAT_VIS_TEAM
Definition at line 65 of file ChatManager.h.
LogoutCode_t
enum channel::LogoutCode_t : uint8_t
Codes sent from the client to request a logout related action.
Enumerator
LOGOUT_CODE_UNKNOWN_MIN
LOGOUT_CODE_QUIT
LOGOUT_CODE_CANCEL
LOGOUT_CODE_SWITCH
LOGOUT_CODE_UNKNOWN_MAX
Definition at line 53 of file AccountManager.h.
Function Documentation
ChannelSyncManager::SyncComplete< objects::CharacterLogin >()
template<> void channel::ChannelSyncManager::SyncComplete< objects::CharacterLogin > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 408 of file ChannelSyncManager.cpp.
ChannelSyncManager::SyncComplete< objects::InstanceAccess >()
template<> void channel::ChannelSyncManager::SyncComplete< objects::InstanceAccess > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 496 of file ChannelSyncManager.cpp.
References LOG_ERROR.
ChannelSyncManager::SyncComplete< objects::MatchEntry >()
template<> void channel::ChannelSyncManager::SyncComplete< objects::MatchEntry > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 586 of file ChannelSyncManager.cpp.
ChannelSyncManager::SyncComplete< objects::PvPMatch >()
template<> void channel::ChannelSyncManager::SyncComplete< objects::PvPMatch > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 613 of file ChannelSyncManager.cpp.
ChannelSyncManager::SyncComplete< objects::UBResult >()
template<> void channel::ChannelSyncManager::SyncComplete< objects::UBResult > (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Definition at line 635 of file ChannelSyncManager.cpp.
ChannelSyncManager::Update< objects::EventCounter >()
template<> int8_t channel::ChannelSyncManager::Update< objects::EventCounter > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 436 of file ChannelSyncManager.cpp.
References libcomp::PersistentObject::GetObjectByUUID(), and state().
ChannelSyncManager::Update< objects::PentalphaMatch >()
template<> int8_t channel::ChannelSyncManager::Update< objects::PentalphaMatch > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 560 of file ChannelSyncManager.cpp.
ChannelSyncManager::Update< objects::SearchEntry >()
template<> int8_t channel::ChannelSyncManager::Update< objects::SearchEntry > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 239 of file ChannelSyncManager.cpp.
References LOG_WARNING, libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
ChannelSyncManager::Update< objects::UBTournament >()
template<> int8_t channel::ChannelSyncManager::Update< objects::UBTournament > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 657 of file ChannelSyncManager.cpp.
state()
static ClientState* channel::state (const std::shared_ptr< libcomp::TcpConnection > & connection) inline static
Definition at line 135 of file ChannelClientConnection.h.
Referenced by channel::CharacterState::ActionCooldownActive(), channel::Zone::AddConnection(), channel::BazaarState::AddItem(), channel::CharacterManager::AddMap(), channel::CharacterManager::AddPlugin(), channel::ActionManager::AddRemoveItems(), channel::CharacterManager::AddRemoveItems(), channel::CharacterManager::AddRemoveOpponent(), channel::ActionManager::AddRemoveStatus(), channel::CharacterManager::AddRemoveValuable(), channel::Zone::AddSpawnedEntity(), channel::CharacterManager::AddTitle(), channel::CharacterManager::AdjustMitamaStats(), AllocatePoint(), channel::AccountManager::Authenticate(), AuthenticateAccount(), channel::TokuseiManager::CalculateAttributeValue(), channel::CharacterManager::CalculateItemRemoval(), channel::CharacterManager::CalculateMaccaPayment(), channel::SkillManager::Cameo(), channel::CharacterManager::CancelMount(), channel::MatchManager::CancelQueue(), channel::CharacterManager::CancelStatusEffects(), channel::ZoneManager::CanEnterRestrictedZone(), ChannelSyncManager::Update< objects::EventCounter >(), channel::MatchManager::CleanupPendingMatch(), CombineStacks(), channel::MatchManager::CompleteBaseCapture(), channel::MatchManager::ConfirmMatch(), channel::EventManager::ContinueChannelChangeEvent(), channel::CharacterManager::ContractDemon(), channel::ZoneManager::CreateEnemy(), channel::ZoneManager::CreateZone(), channel::CharacterManager::CultureItemPickup(), channel::SkillManager::DCM(), channel::ActionManager::Delay(), DemonLockSet(), channel::SkillManager::Desummon(), channel::SkillManager::DetermineCosts(), channel::SkillManager::Digitalize(), channel::SkillManager::DigitalizeCancel(), channel::CharacterManager::DigitalizeEnd(), channel::CharacterManager::DigitalizeStart(), DismissDemon(), DropItem(), channel::BazaarState::DropItem(), channel::BazaarState::DropItemFromMarket(), channel::BazaarState::DropItemInternal(), DumpAccount(), channel::AccountManager::DumpAccount(), channel::EventManager::EndDemonQuest(), channel::EventManager::EndEvent(), channel::FusionManager::EndExchange(), channel::CharacterManager::EndExchange(), channel::ZoneManager::EndInstanceTimer(), channel::MatchManager::EndUltimateBattlePhase(), channel::EventManager::EndWebGame(), channel::MatchManager::EnterPvP(), channel::MatchManager::EnterUltimateBattle(), channel::ZoneManager::EnterZone(), channel::CharacterManager::EquipItem(), channel::EventManager::EvaluateCondition(), channel::EventManager::EvaluateEventCondition(), channel::EventManager::EvaluatePartnerCondition(), channel::EventManager::EvaluateQuestCondition(), channel::EventManager::EvaluateQuestPhaseRequirements(), channel::TokuseiManager::EvaluateTokuseiCondition(), channel::SkillManager::EvaluateTokuseiSkillCondition(), channel::SkillManager::ExecuteSkill(), channel::CharacterManager::ExperienceGain(), ExtractReunionPoints(), channel::ZoneManager::FailPlasma(), channel::SkillManager::FamiliarityUp(), channel::SkillManager::FamiliarityUpItem(), channel::SkillManager::FinalizeSkillExecution(), channel::SkillManager::ForgetAllExpertiseSkills(), channel::ActionManager::GetActionContextCIDs(), channel::TokuseiManager::GetAllTokuseiEntities(), channel::CharacterManager::GetDemonBox(), channel::CharacterManager::GetDemonPacketData(), channel::ManagerConnection::GetEntityClient(), channel::ClientState::GetEntityState(), channel::CharacterManager::GetEntityStatsPacketData(), channel::CharacterState::GetEventCounter(), channel::CharacterManager::GetItemBox(), channel::ZoneManager::GetMatchStartPosition(), channel::ManagerConnection::GetPartyConnections(), channel::MatchManager::GetPvPData(), channel::FusionManager::GetResultDemon(), channel::SkillManager::GetSummonSpeed(), channel::ChatManager::GetTargetCharacterAccount(), channel::ActiveEntityState::GetWorldCID(), channel::ZoneManager::GetZone(), channel::ChatManager::GMCommand_Bethel(), channel::ChatManager::GMCommand_Coin(), channel::ChatManager::GMCommand_Counter(), channel::ChatManager::GMCommand_Cowrie(), channel::ChatManager::GMCommand_Effect(), channel::ChatManager::GMCommand_Enchant(), channel::ChatManager::GMCommand_Enemy(), channel::ChatManager::GMCommand_Event(), channel::ChatManager::GMCommand_ExpertiseExtend(), channel::ChatManager::GMCommand_ExpertiseSet(), channel::ChatManager::GMCommand_Homepoint(), channel::ChatManager::GMCommand_Instance(), channel::ChatManager::GMCommand_Kill(), channel::ChatManager::GMCommand_LevelUp(), channel::ChatManager::GMCommand_PenaltyReset(), channel::ChatManager::GMCommand_Position(), channel::ChatManager::GMCommand_Resolve(), channel::ChatManager::GMCommand_Reunion(), channel::ChatManager::GMCommand_Skill(), channel::ChatManager::GMCommand_SlotAdd(), channel::ChatManager::GMCommand_Speed(), channel::ChatManager::GMCommand_Spirit(), channel::ChatManager::GMCommand_Tokusei(), channel::ChatManager::GMCommand_XP(), channel::ChatManager::GMCommand_Ziotite(), channel::ChatManager::GMCommand_Zone(), channel::ActionManager::GrantSkills(), channel::ActionManager::GrantXP(), HandleBarter(), HandleCultureItem(), channel::ZoneManager::HandleDeathTimeOut(), channel::ChannelServer::HandleDemonQuestReset(), channel::SkillManager::HandleDigitalizeXP(), channel::EventManager::HandleEvent(), channel::ChatManager::HandleGMand(), channel::SkillManager::HandleKills(), channel::AccountManager::HandleLoginRequest(), channel::AccountManager::HandleLoginResponse(), HandleMitamaReset(), HandleMitamaReunion(), channel::EventManager::HandleNext(), channel::EventManager::HandleResponse(), HandleShopPurchase(), HandleShopSale(), channel::ZoneManager::HandleSpecialInstancePopulate(), channel::FusionManager::HandleTriFusion(), channel::EventManager::HandleTriFusion(), channel::EventManager::HandleWebGame(), channel::ActiveEntityState::HasActiveEvent(), channel::AccountManager::InitializeCharacter(), InjectReunionPoints(), channel::EventManager::InterruptEvent(), channel::MatchManager::JoinQueue(), channel::CharacterManager::LearnSkill(), channel::MatchManager::LeaveBase(), channel::MatchManager::LeaveTeam(), channel::MatchManager::LeaveUltimateBattle(), channel::ZoneManager::LeaveZone(), channel::CharacterManager::LevelUp(), channel::MatchManager::LoadPentalphaData(), channel::MatchManager::LoadUltimateBattleData(), channel::AccountManager::Logout(), channel::AccountManager::LogoutCharacter(), channel::CharacterManager::MitamaDemon(), channel::SkillManager::Mooch(), channel::SkillManager::Mount(), channel::ZoneManager::MoveToInstance(), channel::ZoneManager::MoveToLobby(), channel::ZoneManager::MoveToZoneChannel(), channel::Zone::OccupyPvPBase(), channel::EventManager::OpenMenu(), channel::CharacterManager::PayMacca(), channel::ActionManager::PerformActions(), channel::MatchManager::PlayerKilled(), channel::AccountManager::PrepareChannelChange(), channel::SkillManager::PrepareFusionSkill(), channel::FusionManager::ProcessFusion(), channel::SkillManager::ProcessSkillResult(), channel::SkillManager::ProcessSkillResultFinal(), channel::MatchManager::PvPInviteReply(), QueuePartyMemberInfo(), channel::SkillManager::RandomItem(), channel::TokuseiManager::RecalcCostAdjustments(), channel::TokuseiManager::RecalcTimedTokusei(), channel::TokuseiManager::Recalculate(), channel::TokuseiManager::RecalculateParty(), channel::CharacterManager::RecalculateStats(), channel::ActionManager::RecordTimeTrial(), channel::CharacterState::RefreshActionCooldowns(), channel::ZoneInstance::RefreshPlayerState(), channel::Zone::RegisterEntityState(), channel::MatchManager::RejectPvPMatch(), channel::ManagerConnection::RemoveClientConnection(), channel::Zone::RemoveConnection(), channel::Zone::RemoveEntity(), channel::ActiveEntityState::RemoveStatusEffects(), channel::EventManager::RequestMenu(), channel::MatchManager::RequestTeamPvPMatch(), channel::EventManager::ResetDemonQuests(), channel::SkillManager::Respec(), channel::CharacterManager::ReunionDemon(), channel::CharacterManager::ReviveCharacter(), channel::ActionManager::RunScript(), SaveHotbarItems(), channel::ZoneManager::ScheduleEntityRemoval(), channel::ZoneManager::SendAccessMessage(), channel::EventManager::SendActiveQuestList(), channel::CharacterManager::SendAutoRecovery(), channel::CharacterManager::SendCharacterData(), channel::CharacterManager::SendCharacterTitle(), channel::ChatManager::SendChatMessage(), SendClientReadyData(), channel::CharacterManager::SendCoinTotal(), channel::EventManager::SendCompletedQuestList(), channel::TokuseiManager::SendCostAdjustments(), channel::CharacterManager::SendCowrieBethel(), channel::AccountManager::SendCPBalance(), channel::CharacterManager::SendDemonBoxData(), channel::CharacterManager::SendDemonData(), SendDemonQuestData(), channel::ZoneManager::SendDestinyBox(), channel::CharacterManager::SendDevilBook(), channel::MatchManager::SendDiasporaLocation(), channel::CharacterManager::SendEntityStats(), SendEquipmentList(), channel::CharacterManager::SendExpertiseExtension(), channel::CharacterManager::SendFusionGauge(), SendHotbarData(), channel::ZoneManager::SendInstanceTimer(), channel::CharacterManager::SendInvokeStatus(), channel::CharacterManager::SendItemBoxData(), channel::CharacterManager::SendLootItemData(), channel::CharacterManager::SendMapFlags(), channel::CharacterManager::SendMaterials(), channel::CharacterManager::SendPartnerData(), channel::CharacterManager::SendPluginFlags(), channel::ZoneManager::SendPopulateZoneData(), channel::CharacterManager::SendPvPCharacterInfo(), channel::ChannelClientConnection::SendRelativeTimePacket(), SendStateData(), channel::ChatManager::SendTeamChatMessage(), channel::ChatManager::SendTellMessage(), channel::ZoneManager::SendToRange(), channel::MatchManager::SendUltimateBattleMembers(), channel::MatchManager::SendUltimateBattleRankings(), channel::CharacterManager::SendValuableFlags(), channel::EventManager::SetChannelLoginEvent(), channel::ManagerConnection::SetClientConnection(), channel::ActionManager::SetHomepoint(), channel::CharacterManager::SetStatusIcon(), channel::MatchManager::SpectatingMatch(), SplitStack(), channel::MatchManager::StartPvPBaseCapture(), channel::Zone::StartStopCombat(), channel::EventManager::StartSystemEvent(), channel::EventManager::StartWebGame(), channel::ZoneManager::StopInstanceTimer(), channel::CharacterManager::StoreDemon(), channel::SkillManager::StoreDemon(), channel::CharacterManager::SummonDemon(), channel::SkillManager::SummonDemon(), channel::SkillManager::Traesto(), channel::ActionManager::TransformAction(), channel::EventManager::TransformEvent(), channel::BazaarState::TryBuyItem(), channel::CharacterManager::UnequipItem(), channel::CharacterManager::UpdateBethel(), channel::CharacterManager::UpdateBP(), channel::CharacterManager::UpdateCoinTotal(), channel::ActionManager::UpdateCOMP(), channel::CharacterManager::UpdateCowrieBethel(), channel::ZoneManager::UpdateDeathTimeOut(), channel::EventManager::UpdateDemonQuestCount(), UpdateDemonSkill(), channel::DemonState::UpdateDemonState(), channel::CharacterManager::UpdateDigitalizePoints(), channel::CharacterManager::UpdateDurability(), channel::CharacterManager::UpdateEventCounter(), channel::CharacterManager::UpdateExpertise(), channel::CharacterManager::UpdateExpertisePoints(), channel::CharacterManager::UpdateFamiliarity(), channel::CharacterManager::UpdateFusionGauge(), channel::CharacterManager::UpdateItems(), channel::CharacterManager::UpdateLNC(), channel::TokuseiManager::UpdateMovementDecay(), channel::ActionManager::UpdatePoints(), channel::MatchManager::UpdatePvPMatches(), channel::MatchManager::UpdatePvPPoints(), channel::SkillManager::UpdatePvPStats(), channel::EventManager::UpdateQuest(), channel::EventManager::UpdateQuestKillCount(), channel::EventManager::UpdateQuestTargetEnemies(), channel::DemonState::UpdateSharedState(), channel::CharacterManager::UpdateSkillPoints(), channel::CharacterManager::UpdateSoulPoints(), channel::ZoneManager::UpdateSpawnGroups(), channel::ZoneManager::UpdateTrackedTeam(), channel::ZoneManager::UpdateTrackedZone(), channel::MatchManager::UpdateUBPoints(), channel::ActionManager::UpdateZoneFlags(), channel::ActionManager::UpdateZoneInstance(), channel::ManagerClientPacket::ValidateConnectionState(), channel::MatchManager::ValidateMatchEntries(), channel::EventManager::VerifyITime(), channel::SkillManager::XPUp(), and channel::ActionManager::ZoneChange().
Variable Documentation
AI_SKILL_TYPE_CLSR
const uint16_t channel::AI_SKILL_TYPE_CLSR = 0x01
AI skill type for close ranged attacks.
Definition at line 48 of file AIState.h.
Referenced by channel::AIManager::RefreshSkillMap().
AI_SKILL_TYPE_DEF
const uint16_t channel::AI_SKILL_TYPE_DEF = 0x04
AI skill type for defensive skills.
Definition at line 54 of file AIState.h.
Referenced by channel::AIManager::PrepareSkillUsage(), and channel::AIManager::RefreshSkillMap().
AI_SKILL_TYPE_HEAL
const uint16_t channel::AI_SKILL_TYPE_HEAL = 0x08
AI skill type for healing skills.
Definition at line 57 of file AIState.h.
Referenced by channel::AIManager::PrepareSkillUsage(), and channel::AIManager::RefreshSkillMap().
AI_SKILL_TYPE_LNGR
const uint16_t channel::AI_SKILL_TYPE_LNGR = 0x02
AI skill type for long ranged attacks.
Definition at line 51 of file AIState.h.
Referenced by channel::AIManager::RefreshSkillMap().
AI_SKILL_TYPE_SUPPORT
const uint16_t channel::AI_SKILL_TYPE_SUPPORT = 0x10
AI skill type for support skills.
Definition at line 60 of file AIState.h.
Referenced by channel::AIManager::PrepareSkillUsage(), and channel::AIManager::RefreshSkillMap().
AI_SKILL_TYPES_ALL
const uint16_t channel::AI_SKILL_TYPES_ALL = 0x1F
AI skill type mask for all skills.
Definition at line 69 of file AIState.h.
AI_SKILL_TYPES_ALLY
const uint16_t channel::AI_SKILL_TYPES_ALLY = 0x1C
AI skill type mask for ally affecting skills.
Definition at line 66 of file AIState.h.
Referenced by channel::AIManager::RefreshSkillMap().
AI_SKILL_TYPES_ENEMY
const uint16_t channel::AI_SKILL_TYPES_ENEMY = 0x03
AI skill type mask for enemy affecting skills.
Definition at line 63 of file AIState.h.
Referenced by channel::AIManager::RefreshSkillMap().