COMP_hack: SendData.cpp File Reference
SendData.cpp File Reference
Request from the client to get updated data from the server. This can be thought of as the sign that the client is ready to receive regular updates but also involves certain packets that should always send at this point.
#include "Packets.h"
#include <Log.h>
#include <ManagerPacket.h>
#include <PacketCodes.h>
#include <ServerConstants.h>
#include <ServerDataManager.h>
#include <Account.h>
#include <ChannelConfig.h>
#include <ChannelLogin.h>
#include <InstanceAccess.h>
#include <ServerZone.h>
#include <ServerZoneInstance.h>
#include <WorldSharedConfig.h>
#include "ChannelServer.h"
#include "CharacterManager.h"
#include "ZoneManager.h"
Functions
void SendClientReadyData (std::shared_ptr< ChannelServer > server, const std::shared_ptr< ChannelClientConnection > client)
Detailed Description
Request from the client to get updated data from the server. This can be thought of as the sign that the client is ready to receive regular updates but also involves certain packets that should always send at this point.
Author
HACKfrost
This file is part of the Channel Server (channel).
Copyright (C) 2012-2018 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file SendData.cpp.
Function Documentation
void SendClientReadyData (std::shared_ptr< ChannelServer > server, const std::shared_ptr< ChannelClientConnection > client)
Todo:
: identify more of these
Definition at line 55 of file SendData.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetObjectID(), libcomp::ManagerPacket::GetServer(), channel::ChannelServer::GetServerTime(), libcomp::String::IsEmpty(), LOG_ERROR, libcomp::BaseServer::QueueWork(), channel::state(), channel::ClientState::ToClientTime(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), and libcomp::Packet::WriteS8().