COMP_hack: SetWorldInfo.cpp File Reference
SetWorldInfo.cpp File Reference
Response packet from the world detailing itself to the channel.
#include "Packets.h"
#include <DatabaseConfigMariaDB.h>
#include <DatabaseConfigSQLite3.h>
#include <Decrypt.h>
#include <Log.h>
#include <ManagerPacket.h>
#include <Packet.h>
#include <PacketCodes.h>
#include <ReadOnlyPacket.h>
#include <TcpConnection.h>
#include <ChannelConfig.h>
#include <WorldSharedConfig.h>
#include "ChannelServer.h"
#include "ChannelSyncManager.h"
#include "ManagerConnection.h"
#include "ZoneManager.h"
Functions
std::shared_ptr< libcomp::Database > ParseDatabase (const std::shared_ptr< ChannelServer > &server, libcomp::ReadOnlyPacket &p)
bool SetWorldInfoFromPacket (libcomp::ManagerPacket *pPacketManager, const std::shared_ptr< libcomp::TcpConnection > &connection, libcomp::ReadOnlyPacket &p)
Detailed Description
Response packet from the world detailing itself to the channel.
Author
HACKfrost
This file is part of the Channel Server (channel).
Copyright (C) 2012-2018 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file SetWorldInfo.cpp.
Function Documentation
ParseDatabase()
std::shared_ptr<libcomp::Database> ParseDatabase (const std::shared_ptr< ChannelServer > & server, libcomp::ReadOnlyPacket & p)
Definition at line 52 of file SetWorldInfo.cpp.
References LOG_CRITICAL.
Referenced by SetWorldInfoFromPacket().
SetWorldInfoFromPacket()
bool SetWorldInfoFromPacket (libcomp::ManagerPacket * pPacketManager, const std::shared_ptr< libcomp::TcpConnection > & connection, libcomp::ReadOnlyPacket & p)
Definition at line 86 of file SetWorldInfo.cpp.
References libcomp::ManagerPacket::GetServer(), LOG_CRITICAL, LOG_DEBUG, ParseDatabase(), libcomp::ReadOnlyPacket::ReadU8(), libcomp::ReadOnlyPacket::Size(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteU8().