COMP_hack: ShopBuy.cpp File Reference
ShopBuy.cpp File Reference
Request from the client to buy an item from a shop.
#include "Packets.h"
#include <DefinitionManager.h>
#include <ManagerPacket.h>
#include <Packet.h>
#include <PacketCodes.h>
#include <ServerConstants.h>
#include <ServerDataManager.h>
#include <math.h>
#include <random>
#include <Account.h>
#include <EventInstance.h>
#include <EventState.h>
#include <Item.h>
#include <ItemBox.h>
#include <MiItemBasicData.h>
#include <MiItemData.h>
#include <MiPossessionData.h>
#include <MiShopProductData.h>
#include <PostItem.h>
#include <ServerShop.h>
#include <ServerShopProduct.h>
#include <ServerShopTab.h>
#include "ChannelServer.h"
#include "ChannelSyncManager.h"
#include "CharacterManager.h"
Functions
void HandleShopPurchase (const std::shared_ptr< ChannelServer > server, const std::shared_ptr< ChannelClientConnection > client, int32_t shopID, int32_t clientTrendTime, int32_t productID, int32_t quantity, libcomp::String gifteeName, libcomp::String giftMessage)
void SendShopPurchaseReply (const std::shared_ptr< ChannelClientConnection > client, int32_t shopID, int32_t productID, int32_t result, bool queue)
Detailed Description
Request from the client to buy an item from a shop.
Author
HACKfrost
This file is part of the Channel Server (channel).
Copyright (C) 2012-2018 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file ShopBuy.cpp.
Function Documentation
void HandleShopPurchase (const std::shared_ptr< ChannelServer > server, const std::shared_ptr< ChannelClientConnection > client, int32_t shopID, int32_t clientTrendTime, int32_t productID, int32_t quantity, libcomp::String gifteeName, libcomp::String giftMessage)
Definition at line 90 of file ShopBuy.cpp.
References channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), libcomp::ManagerPacket::GetServer(), libcomp::String::IsEmpty(), libcomp::ReadOnlyPacket::Left(), LOG_ERROR, libcomp::ReadOnlyPacket::PeekU16Little(), libcomp::BaseServer::QueueWork(), libcomp::ReadOnlyPacket::ReadS32Little(), libcomp::ReadOnlyPacket::ReadString16Little(), SendShopPurchaseReply(), libcomp::ReadOnlyPacket::Size(), and channel::state().
void SendShopPurchaseReply (const std::shared_ptr< ChannelClientConnection > client, int32_t shopID, int32_t productID, int32_t result, bool queue)
Definition at line 69 of file ShopBuy.cpp.
References libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by HandleShopPurchase().