COMP_hack: UpdateDemonSkill.cpp File Reference
UpdateDemonSkill.cpp File Reference
#include "Packets.h"
#include <DefinitionManager.h>
#include <Log.h>
#include <ManagerPacket.h>
#include <Packet.h>
#include <PacketCodes.h>
#include <InheritedSkill.h>
#include "ChannelServer.h"
#include "CharacterManager.h"
#include "TokuseiManager.h"
Functions
void DemonSkillUpdate (const std::shared_ptr< ChannelServer > server, const std::shared_ptr< ChannelClientConnection > client, int32_t entityID, int8_t skillSlot, uint32_t skillID)
Variables
const int8_t ACTION_LEARN_ACQUIRED = 0
const int8_t ACTION_LEARN_INHERITED = 1
const int8_t ACTION_MOVE = 2
Function Documentation
void DemonSkillUpdate (const std::shared_ptr< ChannelServer > server, const std::shared_ptr< ChannelClientConnection > client, int32_t entityID, int8_t skillSlot, uint32_t skillID)
Definition at line 51 of file UpdateDemonSkill.cpp.
References ACTION_LEARN_ACQUIRED, ACTION_LEARN_INHERITED, ACTION_MOVE, libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), libcomp::ManagerPacket::GetServer(), LOG_ERROR, libcomp::ReadOnlyPacket::ReadS32Little(), libcomp::ReadOnlyPacket::ReadS8(), libcomp::ReadOnlyPacket::ReadU32Little(), libcomp::ReadOnlyPacket::Size(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU32Little().
Variable Documentation
const int8_t ACTION_LEARN_ACQUIRED = 0
Definition at line 45 of file UpdateDemonSkill.cpp.
Referenced by DemonSkillUpdate().
const int8_t ACTION_LEARN_INHERITED = 1
Definition at line 46 of file UpdateDemonSkill.cpp.
Referenced by DemonSkillUpdate().
const int8_t ACTION_MOVE = 2
Definition at line 47 of file UpdateDemonSkill.cpp.
Referenced by DemonSkillUpdate().